// Code generated by testgen; DO NOT EDIT.

package bid754

import (
	"fmt"
	"path/filepath"
)

type generatedDectestRunSuite struct {
	Name              string
	Pattern           string
	TestType          string
	Files             []string
	IgnoredOperations []string
}

type generatedDectestFlagCheckMode int

const (
	generatedDectestFlagCheckNone generatedDectestFlagCheckMode = iota
	generatedDectestFlagCheckAlways
	generatedDectestFlagCheckNative
)

type generatedDectestExecFunc func(decTestCase, string) (decTestExecResult, error)
type generatedDectestResultCompareFunc func(expected, actual string) bool

func loadGeneratedDectestRunSuites() ([]generatedDectestRunSuite, error) {
	return []generatedDectestRunSuite{
		{
			Name:              "Decimal32",
			Pattern:           "ds*.decTest",
			TestType:          "decimal32",
			Files:             []string{"tests/dsBase.decTest"},
			IgnoredOperations: []string{"apply"},
		},
		{
			Name:              "Decimal64",
			Pattern:           "dd*.decTest",
			TestType:          "decimal64",
			Files:             []string{"tests/ddAbs.decTest", "tests/ddAdd.decTest", "tests/ddBase.decTest", "tests/ddClass.decTest", "tests/ddCompare.decTest", "tests/ddCompareSig.decTest", "tests/ddCompareTotal.decTest", "tests/ddCompareTotalMag.decTest", "tests/ddCopy.decTest", "tests/ddCopyAbs.decTest", "tests/ddCopyNegate.decTest", "tests/ddCopySign.decTest", "tests/ddDivide.decTest", "tests/ddFMA.decTest", "tests/ddLogB.decTest", "tests/ddMax.decTest", "tests/ddMaxMag.decTest", "tests/ddMin.decTest", "tests/ddMinMag.decTest", "tests/ddMinus.decTest", "tests/ddMultiply.decTest", "tests/ddNextMinus.decTest", "tests/ddNextPlus.decTest", "tests/ddNextToward.decTest", "tests/ddPlus.decTest", "tests/ddQuantize.decTest", "tests/ddReduce.decTest", "tests/ddRemainder.decTest", "tests/ddRemainderNear.decTest", "tests/ddSameQuantum.decTest", "tests/ddScaleB.decTest", "tests/ddSubtract.decTest", "tests/ddToIntegral.decTest"},
			IgnoredOperations: []string{"apply"},
		},
		{
			Name:              "Decimal128",
			Pattern:           "dq*.decTest",
			TestType:          "decimal128",
			Files:             []string{"tests/dqAbs.decTest", "tests/dqAdd.decTest", "tests/dqBase.decTest", "tests/dqClass.decTest", "tests/dqCompare.decTest", "tests/dqCompareSig.decTest", "tests/dqCompareTotal.decTest", "tests/dqCompareTotalMag.decTest", "tests/dqCopy.decTest", "tests/dqCopyAbs.decTest", "tests/dqCopyNegate.decTest", "tests/dqCopySign.decTest", "tests/dqDivide.decTest", "tests/dqEncode.decTest", "tests/dqFMA.decTest", "tests/dqLogB.decTest", "tests/dqMax.decTest", "tests/dqMaxMag.decTest", "tests/dqMin.decTest", "tests/dqMinMag.decTest", "tests/dqMinus.decTest", "tests/dqMultiply.decTest", "tests/dqNextMinus.decTest", "tests/dqNextPlus.decTest", "tests/dqNextToward.decTest", "tests/dqPlus.decTest", "tests/dqQuantize.decTest", "tests/dqRemainder.decTest", "tests/dqRemainderNear.decTest", "tests/dqSameQuantum.decTest", "tests/dqScaleB.decTest", "tests/dqSubtract.decTest", "tests/dqToIntegral.decTest"},
			IgnoredOperations: []string{"apply"},
		},
		{
			Name:              "General",
			Pattern:           "*.decTest",
			TestType:          "general",
			Files:             []string{"tests/add.decTest", "tests/base.decTest", "tests/compare.decTest", "tests/comparesig.decTest", "tests/divide.decTest", "tests/multiply.decTest", "tests/quantize.decTest", "tests/subtract.decTest", "tests/tointegral.decTest", "tests/tointegralx.decTest"},
			IgnoredOperations: []string{"apply"},
		},
	}, nil
}

func getTestFiles(dir, pattern string) ([]string, error) {
	switch pattern {
	case "ds*.decTest":
		return []string{filepath.Join(dir, "dsBase.decTest")}, nil
	case "dd*.decTest":
		return []string{filepath.Join(dir, "ddAbs.decTest"), filepath.Join(dir, "ddAdd.decTest"), filepath.Join(dir, "ddBase.decTest"), filepath.Join(dir, "ddClass.decTest"), filepath.Join(dir, "ddCompare.decTest"), filepath.Join(dir, "ddCompareSig.decTest"), filepath.Join(dir, "ddCompareTotal.decTest"), filepath.Join(dir, "ddCompareTotalMag.decTest"), filepath.Join(dir, "ddCopy.decTest"), filepath.Join(dir, "ddCopyAbs.decTest"), filepath.Join(dir, "ddCopyNegate.decTest"), filepath.Join(dir, "ddCopySign.decTest"), filepath.Join(dir, "ddDivide.decTest"), filepath.Join(dir, "ddFMA.decTest"), filepath.Join(dir, "ddLogB.decTest"), filepath.Join(dir, "ddMax.decTest"), filepath.Join(dir, "ddMaxMag.decTest"), filepath.Join(dir, "ddMin.decTest"), filepath.Join(dir, "ddMinMag.decTest"), filepath.Join(dir, "ddMinus.decTest"), filepath.Join(dir, "ddMultiply.decTest"), filepath.Join(dir, "ddNextMinus.decTest"), filepath.Join(dir, "ddNextPlus.decTest"), filepath.Join(dir, "ddNextToward.decTest"), filepath.Join(dir, "ddPlus.decTest"), filepath.Join(dir, "ddQuantize.decTest"), filepath.Join(dir, "ddReduce.decTest"), filepath.Join(dir, "ddRemainder.decTest"), filepath.Join(dir, "ddRemainderNear.decTest"), filepath.Join(dir, "ddSameQuantum.decTest"), filepath.Join(dir, "ddScaleB.decTest"), filepath.Join(dir, "ddSubtract.decTest"), filepath.Join(dir, "ddToIntegral.decTest")}, nil
	case "dq*.decTest":
		return []string{filepath.Join(dir, "dqAbs.decTest"), filepath.Join(dir, "dqAdd.decTest"), filepath.Join(dir, "dqBase.decTest"), filepath.Join(dir, "dqClass.decTest"), filepath.Join(dir, "dqCompare.decTest"), filepath.Join(dir, "dqCompareSig.decTest"), filepath.Join(dir, "dqCompareTotal.decTest"), filepath.Join(dir, "dqCompareTotalMag.decTest"), filepath.Join(dir, "dqCopy.decTest"), filepath.Join(dir, "dqCopyAbs.decTest"), filepath.Join(dir, "dqCopyNegate.decTest"), filepath.Join(dir, "dqCopySign.decTest"), filepath.Join(dir, "dqDivide.decTest"), filepath.Join(dir, "dqEncode.decTest"), filepath.Join(dir, "dqFMA.decTest"), filepath.Join(dir, "dqLogB.decTest"), filepath.Join(dir, "dqMax.decTest"), filepath.Join(dir, "dqMaxMag.decTest"), filepath.Join(dir, "dqMin.decTest"), filepath.Join(dir, "dqMinMag.decTest"), filepath.Join(dir, "dqMinus.decTest"), filepath.Join(dir, "dqMultiply.decTest"), filepath.Join(dir, "dqNextMinus.decTest"), filepath.Join(dir, "dqNextPlus.decTest"), filepath.Join(dir, "dqNextToward.decTest"), filepath.Join(dir, "dqPlus.decTest"), filepath.Join(dir, "dqQuantize.decTest"), filepath.Join(dir, "dqRemainder.decTest"), filepath.Join(dir, "dqRemainderNear.decTest"), filepath.Join(dir, "dqSameQuantum.decTest"), filepath.Join(dir, "dqScaleB.decTest"), filepath.Join(dir, "dqSubtract.decTest"), filepath.Join(dir, "dqToIntegral.decTest")}, nil
	case "*.decTest":
		return []string{filepath.Join(dir, "add.decTest"), filepath.Join(dir, "base.decTest"), filepath.Join(dir, "compare.decTest"), filepath.Join(dir, "comparesig.decTest"), filepath.Join(dir, "divide.decTest"), filepath.Join(dir, "multiply.decTest"), filepath.Join(dir, "quantize.decTest"), filepath.Join(dir, "subtract.decTest"), filepath.Join(dir, "tointegral.decTest"), filepath.Join(dir, "tointegralx.decTest")}, nil
	default:
		return nil, fmt.Errorf("no generated dectest suite for pattern %q", pattern)
	}
}

func runDecTestCaseV2(tc decTestCase, testType string) error {
	switch normalizeDecTestOperation(tc.Operation) {
	case "class":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestClassOperation, generatedDectestCompareTokenResult, generatedDectestFlagCheckNone)
	case "samequantum":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestSameQuantumOperation, generatedDectestCompareTokenResult, generatedDectestFlagCheckNone)
	case "nexttoward":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestNextTowardOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "nextplus", "nextminus":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestNextOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "min", "max", "minmag", "maxmag":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestMinMaxOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "comparetotal", "comparetotmag":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestCompareTotalOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "abs", "plus", "minus":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestUnaryOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "fma":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestFMAOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "logb":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestLogBOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "scaleb":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestScaleBOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "remaindernear":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestRemainderNearOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "remainder":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestRemainderOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "reduce":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestReduceOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckAlways)
	case "copy", "copyabs", "copynegate", "copysign":
		return runGeneratedDectestCase(tc, testType, -1, executeDecTestCopyOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckNone)
	case "add", "subtract", "multiply", "divide", "quantize":
		return runGeneratedDectestCase(tc, testType, 2, executeDecTestOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckNative)
	case "compare", "comparesig":
		return runGeneratedDectestCase(tc, testType, 2, executeDecTestOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckNative)
	case "tosci", "toeng", "tointegral", "tointegralx":
		return runGeneratedDectestCase(tc, testType, 1, executeDecTestReadOperation, generatedDectestCompareDecimalResult, generatedDectestFlagCheckNative)
	default:
		return fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
}

func runGeneratedDectestCase(
	tc decTestCase,
	testType string,
	arity int,
	exec generatedDectestExecFunc,
	resultMatches generatedDectestResultCompareFunc,
	flagCheck generatedDectestFlagCheckMode,
) error {
	if arity >= 0 && len(tc.Operands) != arity {
		return fmt.Errorf("%s requires %d operands, got %d", tc.Operation, arity, len(tc.Operands))
	}

	execResult, err := exec(tc, testType)
	if err != nil {
		return err
	}

	if !resultMatches(tc.Result, execResult.Result) {
		return fmt.Errorf("result mismatch: expected %s, got %s", tc.Result, execResult.Result)
	}

	switch flagCheck {
	case generatedDectestFlagCheckNone:
		return nil
	case generatedDectestFlagCheckAlways:
		if !compareDecTestFlags(tc.Flags, execResult.Flags) {
			return fmt.Errorf("flag mismatch: expected %v, got %s", tc.Flags, execResult.Flags.String())
		}
	case generatedDectestFlagCheckNative:
		if supportsDecTestFlagVerification() && !compareDecTestFlags(tc.Flags, execResult.Flags) {
			return fmt.Errorf("flag mismatch: expected %v, got %s", tc.Flags, execResult.Flags.String())
		}
	default:
		return fmt.Errorf("unsupported generated decTest flag check mode: %d", flagCheck)
	}

	return nil
}

func generatedDectestCompareDecimalResult(expected, actual string) bool {
	return compareDecimalResults(expected, actual)
}

func generatedDectestCompareTokenResult(expected, actual string) bool {
	return compareDecTestTokenResult(expected, actual)
}
