// Code generated by testgen; DO NOT EDIT.
package testspec

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// LoadGenerated reads a spec_index.json file and reconstructs the exact
// SharedSpec by loading every shard in index order and expanding the shard
// header fields back into each case record.
func LoadGenerated(indexPath string) (SharedSpec, error) {
	var spec SharedSpec

	data, err := os.ReadFile(indexPath)
	if err != nil {
		return spec, fmt.Errorf("read generated spec index %q: %w", indexPath, err)
	}
	var index SpecIndex
	if err := decodeStrictJSON(data, &index); err != nil {
		return spec, fmt.Errorf("parse generated spec index %q: %w", indexPath, err)
	}

	spec.DectestSuites = index.DectestSuites
	spec.DectestFileInventories = index.DectestFileInventories
	spec.DectestRuntimeSkipInventory = index.DectestRuntimeSkipInventory
	spec.DectestGoportRuntimeSkipInventory = index.DectestGoportRuntimeSkipInventory
	spec.ReadtestProfileInventory = index.ReadtestProfileInventory
	spec.FuzzCases = index.FuzzCases

	baseDir := filepath.Dir(indexPath)
	for _, shardFile := range index.ReadtestShardFiles {
		shardPath := filepath.Join(baseDir, filepath.FromSlash(shardFile))
		shardData, err := os.ReadFile(shardPath)
		if err != nil {
			return SharedSpec{}, fmt.Errorf("read readtest shard %q: %w", shardPath, err)
		}
		var shard ReadtestShard
		if err := decodeStrictJSON(shardData, &shard); err != nil {
			return SharedSpec{}, fmt.Errorf("parse readtest shard %q: %w", shardPath, err)
		}
		for _, tc := range shard.Cases {
			spec.ReadCases = append(spec.ReadCases, GeneratedReadCase{
				Suite:                   shard.Suite,
				Group:                   shard.Group,
				Format:                  shard.Format,
				Header:                  shard.Header,
				Source:                  shard.Source,
				ID:                      tc.ID,
				Line:                    tc.Line,
				Function:                shard.Function,
				Kind:                    shard.Kind,
				OutputType:              shard.OutputType,
				InputTypes:              append([]string(nil), shard.InputTypes...),
				CompareGroup:            shard.CompareGroup,
				NativeCompareSkipReason: shard.NativeCompareSkipReason,
				Operands:                tc.Operands,
				Expected:                tc.Expected,
				Status:                  tc.Status,
				Rounding:                tc.Rounding,
			})
		}
	}
	for _, shardFile := range index.FFIShardFiles {
		shardPath := filepath.Join(baseDir, filepath.FromSlash(shardFile))
		shardData, err := os.ReadFile(shardPath)
		if err != nil {
			return SharedSpec{}, fmt.Errorf("read ffi shard %q: %w", shardPath, err)
		}
		var shard FFIShard
		if err := decodeStrictJSON(shardData, &shard); err != nil {
			return SharedSpec{}, fmt.Errorf("parse ffi shard %q: %w", shardPath, err)
		}
		for _, tc := range shard.Cases {
			spec.FFICases = append(spec.FFICases, GeneratedFFICase{
				Suite:       shard.Suite,
				ID:          tc.ID,
				Format:      shard.Format,
				ResultBits:  shard.ResultBits,
				OperandBits: append([]int(nil), shard.OperandBits...),
				Operation:   shard.Operation,
				Function:    shard.Function,
				LinkName:    shard.LinkName,
				Declaration: shard.Declaration,
				Source:      shard.Source,
				Probe:       tc.Probe,
				ProbeGroup:  tc.ProbeGroup,
				Expected:    tc.Expected,
				Forbidden:   tc.Forbidden,
				Rounding:    tc.Rounding,
				Operands:    tc.Operands,
			})
		}
	}
	return spec, nil
}

func decodeStrictJSON(data []byte, dst any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(dst); err != nil {
		return err
	}
	var trailing json.RawMessage
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return fmt.Errorf("trailing JSON value")
		}
		return fmt.Errorf("trailing JSON: %w", err)
	}
	return nil
}
