// Code generated by testgen; DO NOT EDIT.
//go:build bid754_bidcodec_vectors

package bidcodec

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math/big"
	"os"
	"strconv"
	"testing"
)

type vectorEntry struct {
	Type          string `json:"type"`
	Hex           string `json:"hex"`
	HexHi         string `json:"hex_hi,omitempty"`
	Sign          bool   `json:"sign"`
	Coefficient   string `json:"coefficient"`
	Exponent      int    `json:"exponent"`
	Kind          string `json:"kind"`
	Payload       string `json:"payload,omitempty"`
	DecimalString string `json:"decimal_string"`
	Canonical     bool   `json:"canonical"`
	EncodedHex    string `json:"encoded_hex"`
	EncodedHi     string `json:"encoded_hi,omitempty"`
}

type vectorFile struct {
	FormatVersion int           `json:"format_version"`
	Vectors       []vectorEntry `json:"vectors"`
	RejectVectors []rejectEntry `json:"reject_vectors"`
	StringVectors []stringEntry `json:"string_vectors"`
}

// stringEntry is one string_vectors success record: FromString(Input) must
// succeed and ToString of the result must equal Expected exactly.
type stringEntry struct {
	Input    string `json:"input"`
	Expected string `json:"expected"`
}

type rejectEntry struct {
	Channel     string `json:"channel"`
	Type        string `json:"type"`
	Input       string `json:"input"`
	Sign        bool   `json:"sign"`
	Kind        string `json:"kind"`
	Coefficient string `json:"coefficient"`
	Exponent    int32  `json:"exponent"`
	Payload     string `json:"payload"`
	Reason      string `json:"reason"`
	Requires    string `json:"requires"`
}

const (
	expectedFormatVersion          = 5
	expectedRejectTotal            = 98
	expectedRejectConsumed         = 98
	expectedRejectSkipped          = 0
	expectedStringVectorTotal      = 20
	expectedVectorTotal            = 23545
	expectedBid32Vectors           = 5019
	expectedBid64Vectors           = 5804
	expectedBid128Vectors          = 12722
	expectedBid32CanonicalVectors  = 4464
	expectedBid64CanonicalVectors  = 4583
	expectedBid128CanonicalVectors = 6047
)

func loadVectors(t *testing.T) []vectorEntry {
	t.Helper()
	data, err := os.ReadFile("../bid754-codec-vectors/vectors.json")
	if err != nil {
		t.Fatalf("failed to read vectors.json: %v", err)
	}
	var file vectorFile
	if err := json.Unmarshal(data, &file); err != nil {
		t.Fatalf("failed to parse vectors.json: %v", err)
	}
	if file.FormatVersion != expectedFormatVersion {
		t.Fatalf("unsupported BID codec vectors format_version %d, want %d", file.FormatVersion, expectedFormatVersion)
	}
	return file.Vectors
}

func loadRejectVectors(t *testing.T) []rejectEntry {
	t.Helper()
	data, err := os.ReadFile("../bid754-codec-vectors/vectors.json")
	if err != nil {
		t.Fatalf("failed to read vectors.json: %v", err)
	}
	var file vectorFile
	if err := json.Unmarshal(data, &file); err != nil {
		t.Fatalf("failed to parse vectors.json: %v", err)
	}
	if file.FormatVersion != expectedFormatVersion {
		t.Fatalf("unsupported BID codec vectors format_version %d, want %d", file.FormatVersion, expectedFormatVersion)
	}
	return file.RejectVectors
}

func loadStringVectors(t *testing.T) []stringEntry {
	t.Helper()
	data, err := os.ReadFile("../bid754-codec-vectors/vectors.json")
	if err != nil {
		t.Fatalf("failed to read vectors.json: %v", err)
	}
	var file vectorFile
	if err := json.Unmarshal(data, &file); err != nil {
		t.Fatalf("failed to parse vectors.json: %v", err)
	}
	if file.FormatVersion != expectedFormatVersion {
		t.Fatalf("unsupported BID codec vectors format_version %d, want %d", file.FormatVersion, expectedFormatVersion)
	}
	return file.StringVectors
}

var anchorVectors = []vectorEntry{
	{Type: "bid32", Hex: "32800001", Sign: false, Coefficient: "1", Exponent: 0, Kind: "normal", DecimalString: "+1E+0", Canonical: true, EncodedHex: "32800001"},
	{Type: "bid32", Hex: "b2800000", Sign: true, Coefficient: "", Exponent: 0, Kind: "zero", DecimalString: "-0", Canonical: true, EncodedHex: "b2800000"},
	{Type: "bid32", Hex: "7c000001", Sign: false, Coefficient: "", Exponent: 0, Kind: "qnan", Payload: "1", DecimalString: "+NaN1", Canonical: true, EncodedHex: "7c000001"},
	{Type: "bid64", Hex: "31c0000000000001", Sign: false, Coefficient: "1", Exponent: 0, Kind: "normal", DecimalString: "+1E+0", Canonical: true, EncodedHex: "31c0000000000001"},
	{Type: "bid64", Hex: "b1c0000000000000", Sign: true, Coefficient: "", Exponent: 0, Kind: "zero", DecimalString: "-0", Canonical: true, EncodedHex: "b1c0000000000000"},
	{Type: "bid64", Hex: "7c00000000000001", Sign: false, Coefficient: "", Exponent: 0, Kind: "qnan", Payload: "1", DecimalString: "+NaN1", Canonical: true, EncodedHex: "7c00000000000001"},
	{Type: "bid128", Hex: "0000000000000001", HexHi: "3040000000000000", Sign: false, Coefficient: "1", Exponent: 0, Kind: "normal", DecimalString: "+1E+0", Canonical: true, EncodedHex: "0000000000000001", EncodedHi: "3040000000000000"},
	{Type: "bid128", Hex: "0000000000000000", HexHi: "8000000000000000", Sign: true, Coefficient: "", Exponent: -6176, Kind: "zero", DecimalString: "-0E-6176", Canonical: true, EncodedHex: "0000000000000000", EncodedHi: "8000000000000000"},
	{Type: "bid128", Hex: "0000000000000001", HexHi: "7c00000000000000", Sign: false, Coefficient: "", Exponent: 0, Kind: "qnan", Payload: "1", DecimalString: "+NaN1", Canonical: true, EncodedHex: "0000000000000001", EncodedHi: "7c00000000000000"},
	{Type: "bid128", Hex: "0000000000000000", HexHi: "7c00000000000001", Sign: false, Coefficient: "", Exponent: 0, Kind: "qnan", Payload: "18446744073709551616", DecimalString: "+NaN18446744073709551616", Canonical: true, EncodedHex: "0000000000000000", EncodedHi: "7c00000000000001"},
}

func parseHex64(s string) uint64 {
	v, _ := strconv.ParseUint(s, 16, 64)
	return v
}

func parseHex32(s string) uint32 {
	v, _ := strconv.ParseUint(s, 16, 32)
	return uint32(v)
}

func parseKind(s string) Kind {
	switch s {
	case "normal":
		return Normal
	case "zero":
		return Zero
	case "inf":
		return Infinity
	case "qnan":
		return QNaN
	case "snan":
		return SNaN
	}
	panic("unknown kind: " + s)
}

func bid32Bytes(s string) []byte {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], parseHex32(s))
	return b[:]
}

func bid64Bytes(s string) []byte {
	var b [8]byte
	binary.LittleEndian.PutUint64(b[:], parseHex64(s))
	return b[:]
}

func bid128Bytes(loHex, hiHex string) []byte {
	var b [16]byte
	binary.LittleEndian.PutUint64(b[0:8], parseHex64(loHex))
	binary.LittleEndian.PutUint64(b[8:16], parseHex64(hiHex))
	return b[:]
}

func TestBidCodecVectors(t *testing.T) {
	vectors := loadVectors(t)

	var bid32Count, bid64Count, bid128Count int
	var bid32CanonicalCount, bid64CanonicalCount, bid128CanonicalCount int
	var bid32NonCanonicalCount, bid64NonCanonicalCount, bid128NonCanonicalCount int
	var decodePass, decodeFail int
	var roundtripPass, roundtripFail int

	for i, v := range vectors {
		label := fmt.Sprintf("[%d] %s hex=%s", i, v.Type, v.Hex)

		switch v.Type {
		case "bid32":
			bid32Count++
			if v.Canonical {
				bid32CanonicalCount++
			} else {
				bid32NonCanonicalCount++
			}
			raw := parseHex32(v.Hex)
			c := Decode32(raw)

			if !checkDecode(t, label, c, v) {
				decodeFail++
			} else {
				decodePass++
			}

			checkStringRoundtrip(t, label, c, v)
			checkBytesRoundtrip(t, label, c, v)

			if v.Canonical {
				encoded, err := Encode32(c)
				gotHex := fmt.Sprintf("%08x", encoded)
				if err != nil || gotHex != v.EncodedHex {
					t.Errorf("%s roundtrip: got %s err=%v, want %s", label, gotHex, err, v.EncodedHex)
					roundtripFail++
				} else {
					roundtripPass++
				}
			}

		case "bid64":
			bid64Count++
			if v.Canonical {
				bid64CanonicalCount++
			} else {
				bid64NonCanonicalCount++
			}
			raw := parseHex64(v.Hex)
			c := Decode64(raw)

			if !checkDecode(t, label, c, v) {
				decodeFail++
			} else {
				decodePass++
			}

			checkStringRoundtrip(t, label, c, v)
			checkBytesRoundtrip(t, label, c, v)

			if v.Canonical {
				encoded, err := Encode64(c)
				gotHex := fmt.Sprintf("%016x", encoded)
				if err != nil || gotHex != v.EncodedHex {
					t.Errorf("%s roundtrip: got %s err=%v, want %s", label, gotHex, err, v.EncodedHex)
					roundtripFail++
				} else {
					roundtripPass++
				}
			}

		case "bid128":
			bid128Count++
			if v.Canonical {
				bid128CanonicalCount++
			} else {
				bid128NonCanonicalCount++
			}
			lo := parseHex64(v.Hex)
			hi := parseHex64(v.HexHi)
			c := Decode128(lo, hi)

			if !checkDecode(t, label, c, v) {
				decodeFail++
			} else {
				decodePass++
			}

			checkStringRoundtrip(t, label, c, v)
			checkBytesRoundtrip(t, label, c, v)

			if v.Canonical {
				gotLo, gotHi, err := Encode128(c)
				gotLoHex := fmt.Sprintf("%016x", gotLo)
				gotHiHex := fmt.Sprintf("%016x", gotHi)
				if err != nil || gotLoHex != v.EncodedHex || gotHiHex != v.EncodedHi {
					t.Errorf("%s roundtrip: got lo=%s hi=%s err=%v, want lo=%s hi=%s",
						label, gotLoHex, gotHiHex, err, v.EncodedHex, v.EncodedHi)
					roundtripFail++
				} else {
					roundtripPass++
				}
			}

		default:
			t.Fatalf("unknown type: %s", v.Type)
		}
	}

	if len(vectors) != expectedVectorTotal {
		t.Fatalf("vector total = %d, want %d", len(vectors), expectedVectorTotal)
	}
	if bid32Count != expectedBid32Vectors || bid64Count != expectedBid64Vectors || bid128Count != expectedBid128Vectors {
		t.Fatalf("per-format vector counts = bid32:%d bid64:%d bid128:%d, want bid32:%d bid64:%d bid128:%d",
			bid32Count, bid64Count, bid128Count, expectedBid32Vectors, expectedBid64Vectors, expectedBid128Vectors)
	}
	if bid32CanonicalCount != expectedBid32CanonicalVectors || bid64CanonicalCount != expectedBid64CanonicalVectors || bid128CanonicalCount != expectedBid128CanonicalVectors {
		t.Fatalf("canonical vector counts = bid32:%d bid64:%d bid128:%d, want bid32:%d bid64:%d bid128:%d",
			bid32CanonicalCount, bid64CanonicalCount, bid128CanonicalCount,
			expectedBid32CanonicalVectors, expectedBid64CanonicalVectors, expectedBid128CanonicalVectors)
	}
	if bid32NonCanonicalCount != expectedBid32Vectors-expectedBid32CanonicalVectors ||
		bid64NonCanonicalCount != expectedBid64Vectors-expectedBid64CanonicalVectors ||
		bid128NonCanonicalCount != expectedBid128Vectors-expectedBid128CanonicalVectors {
		t.Fatalf("non-canonical vector counts = bid32:%d bid64:%d bid128:%d",
			bid32NonCanonicalCount, bid64NonCanonicalCount, bid128NonCanonicalCount)
	}
	if decodePass != expectedVectorTotal || decodeFail != 0 {
		t.Fatalf("decode coverage = %d pass, %d fail; want %d pass, 0 fail", decodePass, decodeFail, expectedVectorTotal)
	}
	if roundtripPass != expectedBid32CanonicalVectors+expectedBid64CanonicalVectors+expectedBid128CanonicalVectors || roundtripFail != 0 {
		t.Fatalf("roundtrip coverage = %d pass, %d fail", roundtripPass, roundtripFail)
	}

	t.Logf("vectors: %d total (bid32=%d, bid64=%d, bid128=%d)",
		len(vectors), bid32Count, bid64Count, bid128Count)
	t.Logf("decode: %d pass, %d fail", decodePass, decodeFail)
	t.Logf("roundtrip: %d pass, %d fail", roundtripPass, roundtripFail)
}

func TestBidCodecAnchorVectors(t *testing.T) {
	for _, v := range anchorVectors {
		label := fmt.Sprintf("anchor %s hex=%s", v.Type, v.Hex)
		if !v.Canonical {
			t.Fatalf("%s canonical = false, want true", label)
		}
		var c Components
		switch v.Type {
		case "bid32":
			c = Decode32(parseHex32(v.Hex))
		case "bid64":
			c = Decode64(parseHex64(v.Hex))
		case "bid128":
			c = Decode128(parseHex64(v.Hex), parseHex64(v.HexHi))
		default:
			t.Fatalf("unknown anchor type: %s", v.Type)
		}
		if !checkDecode(t, label, c, v) {
			continue
		}
		if c.Exponent != int32(v.Exponent) {
			t.Errorf("%s exponent: got %d, want %d", label, c.Exponent, v.Exponent)
		}
		checkStringRoundtrip(t, label, c, v)
		checkBytesRoundtrip(t, label, c, v)
	}
}

func TestBidCodecErrorSemantics(t *testing.T) {
	if _, err := Decode32Bytes(make([]byte, 3)); err == nil {
		t.Fatal("Decode32Bytes short input succeeded, want error")
	}
	if _, err := Decode32Bytes(make([]byte, 5)); err == nil {
		t.Fatal("Decode32Bytes long input succeeded, want error")
	}
	if _, err := Decode64Bytes(make([]byte, 7)); err == nil {
		t.Fatal("Decode64Bytes short input succeeded, want error")
	}
	if _, err := Decode64Bytes(make([]byte, 9)); err == nil {
		t.Fatal("Decode64Bytes long input succeeded, want error")
	}
	if _, err := Decode128Bytes(make([]byte, 15)); err == nil {
		t.Fatal("Decode128Bytes short input succeeded, want error")
	}
	if _, err := Decode128Bytes(make([]byte, 17)); err == nil {
		t.Fatal("Decode128Bytes long input succeeded, want error")
	}
	// reject_vectors: the generated malformed-input and out-of-range-Components
	// reject domain replaces the previous hardcoded malformed list. Each record
	// must fail through the language error mechanism (parse failure for
	// from_string, encode rejection for encode); records whose Components field
	// types this language cannot construct are skipped with a reported reason.
	rejects := loadRejectVectors(t)
	if len(rejects) != expectedRejectTotal {
		t.Fatalf("reject_vectors total = %d, want %d", len(rejects), expectedRejectTotal)
	}
	caps := map[string]bool{}
	for _, capTag := range []string{"bignum_coefficient", "negative_coefficient", "negative_payload"} {
		caps[capTag] = true
	}
	unsupportedCaps := map[string]bool{}
	for _, capTag := range []string{} {
		unsupportedCaps[capTag] = true
	}
	consumed, skipped := 0, 0
	skipReasons := map[string]int{}
	for _, r := range rejects {
		if r.Requires != "" && !caps[r.Requires] {
			if !unsupportedCaps[r.Requires] {
				t.Fatalf("reject record requires tag %q outside the declared capability universe", r.Requires)
			}
			skipped++
			skipReasons[r.Requires]++
			continue
		}
		consumed++
		switch r.Channel {
		case "from_string":
			if _, err := FromString(r.Input); err == nil {
				t.Errorf("reject from_string %q (%s): expected error", r.Input, r.Reason)
			}
		case "encode":
			if err := encodeReject(t, r); err == nil {
				t.Errorf("reject encode %s %s (%s): expected error", r.Type, r.Kind, r.Reason)
			}
		case "to_string":
			if err := toStringReject(t, r); err == nil {
				t.Errorf("reject to_string %s (%s): expected error", r.Kind, r.Reason)
			}
		default:
			t.Fatalf("unknown reject channel %q", r.Channel)
		}
	}
	if consumed != expectedRejectConsumed || skipped != expectedRejectSkipped || consumed+skipped != len(rejects) {
		t.Fatalf("reject consumption = consumed %d skipped %d of %d, want consumed %d skipped %d",
			consumed, skipped, len(rejects), expectedRejectConsumed, expectedRejectSkipped)
	}
	t.Logf("reject_vectors: consumed=%d skipped=%d skipReasons=%v", consumed, skipped, skipReasons)

	// type-domain rejects: values the shared JSON schema cannot express, emitted
	// directly for the languages that can construct them (Go: kind is an integer
	// type, so a value outside the defined set is constructible).
	for _, tc := range []struct {
		id string
		c  Components
	}{
		{"unrecognized_kind", Components{Kind: Kind(99)}},
	} {
		if _, err := Encode32(tc.c); err == nil {
			t.Errorf("type-domain reject %s: Encode32 expected error", tc.id)
		}
		if _, err := ToString(tc.c); err == nil {
			t.Errorf("type-domain reject %s: ToString expected error", tc.id)
		}
	}
}

func TestBidCodecStringVectors(t *testing.T) {
	// string_vectors: the generated SUCCESS channel for the string surface.
	// Each record's input must parse and re-render as the exact expected
	// string. This pins FromString→ToString agreement across all language
	// consumers in the encoding-unreachable Components region (above all
	// int32-extreme exponents, where a 32-bit adjusted-exponent computation
	// silently wraps the rendered sign) plus the successful grammar-edge
	// normalizations — territory neither the bit-decode vectors channel nor
	// the failure-side reject_vectors channel reaches. The closure leg then
	// re-parses the expected rendering itself: FromString(expected) must
	// succeed and ToString must reproduce it exactly (parse(render(x)) is
	// total and expected is a rendering fixed point), so a parser that rejects
	// its own renderer's output fails here in every language.
	stringVectors := loadStringVectors(t)
	if len(stringVectors) != expectedStringVectorTotal {
		t.Fatalf("string_vectors total = %d, want %d", len(stringVectors), expectedStringVectorTotal)
	}
	consumed := 0
	for _, sv := range stringVectors {
		consumed++
		c, err := FromString(sv.Input)
		if err != nil {
			t.Errorf("string_vectors FromString(%q): unexpected error: %v", sv.Input, err)
			continue
		}
		if got, err := ToString(c); err != nil || got != sv.Expected {
			t.Errorf("string_vectors %q: ToString got %q, want %q", sv.Input, got, sv.Expected)
			continue
		}
		reparsed, err := FromString(sv.Expected)
		if err != nil {
			t.Errorf("string_vectors closure FromString(%q): rendering not reparseable: %v", sv.Expected, err)
			continue
		}
		if got, err := ToString(reparsed); err != nil || got != sv.Expected {
			t.Errorf("string_vectors closure %q: re-rendered as %q, not a fixed point", sv.Expected, got)
		}
	}
	if consumed != expectedStringVectorTotal {
		t.Fatalf("string_vectors consumption = %d, want %d", consumed, expectedStringVectorTotal)
	}
	t.Logf("string_vectors: consumed=%d", consumed)
}

func encodeReject(t *testing.T, r rejectEntry) error {
	t.Helper()
	c := rejectComponents(t, r)
	switch r.Type {
	case "bid32":
		_, err := Encode32(c)
		return err
	case "bid64":
		_, err := Encode64(c)
		return err
	case "bid128":
		_, _, err := Encode128(c)
		return err
	default:
		t.Fatalf("reject encode: unknown type %q", r.Type)
		return nil
	}
}

func toStringReject(t *testing.T, r rejectEntry) error {
	t.Helper()
	_, err := ToString(rejectComponents(t, r))
	return err
}

func rejectComponents(t *testing.T, r rejectEntry) Components {
	t.Helper()
	c := Components{Sign: r.Sign, Kind: parseKind(r.Kind), Exponent: r.Exponent}
	if r.Coefficient != "" {
		coeff, ok := new(big.Int).SetString(r.Coefficient, 10)
		if !ok {
			t.Fatalf("reject encode %s: bad coefficient %q", r.Type, r.Coefficient)
		}
		c.Coefficient = coeff
	}
	if r.Payload != "" {
		p, ok := new(big.Int).SetString(r.Payload, 10)
		if !ok {
			t.Fatalf("reject encode %s: bad payload %q", r.Type, r.Payload)
		}
		c.Payload = p
	}
	return c
}

func checkDecode(t *testing.T, label string, c Components, v vectorEntry) bool {
	t.Helper()
	ok := true

	if c.Sign != v.Sign {
		t.Errorf("%s sign: got %v, want %v", label, c.Sign, v.Sign)
		ok = false
	}

	wantKind := parseKind(v.Kind)
	if c.Kind != wantKind {
		t.Errorf("%s kind: got %v, want %v", label, c.Kind, wantKind)
		ok = false
	}

	wantCoeff := v.Coefficient
	var gotCoeff string
	if c.Coefficient != nil {
		gotCoeff = c.Coefficient.String()
	}
	if gotCoeff != wantCoeff {
		t.Errorf("%s coefficient: got %q, want %q", label, gotCoeff, wantCoeff)
		ok = false
	}

	if c.Kind == Normal || c.Kind == Zero {
		wantExp := int32(v.Exponent)
		if c.Exponent != wantExp {
			t.Errorf("%s exponent: got %d, want %d", label, c.Exponent, wantExp)
			ok = false
		}
	}

	if v.Payload != "" {
		wantPayload, valid := new(big.Int).SetString(v.Payload, 10)
		gotPayload := c.Payload
		if gotPayload == nil {
			gotPayload = big.NewInt(0)
		}
		if !valid || gotPayload.Cmp(wantPayload) != 0 {
			t.Errorf("%s payload: got %v, want %s", label, c.Payload, v.Payload)
			ok = false
		}
	}

	return ok
}

func checkBytesRoundtrip(t *testing.T, label string, c Components, v vectorEntry) {
	t.Helper()
	switch v.Type {
	case "bid32":
		decoded, err := Decode32Bytes(bid32Bytes(v.Hex))
		if err != nil {
			t.Errorf("%s decode_bytes32: %v", label, err)
			return
		}
		if !checkDecode(t, label+" decode_bytes32", decoded, v) {
			return
		}
		if v.Canonical {
			got, err := Encode32Bytes(c)
			want := bid32Bytes(v.EncodedHex)
			if err != nil || !bytes.Equal(got[:], want) {
				t.Errorf("%s encode_bytes32: got %x err=%v, want %x", label, got, err, want)
			}
		}
	case "bid64":
		decoded, err := Decode64Bytes(bid64Bytes(v.Hex))
		if err != nil {
			t.Errorf("%s decode_bytes64: %v", label, err)
			return
		}
		if !checkDecode(t, label+" decode_bytes64", decoded, v) {
			return
		}
		if v.Canonical {
			got, err := Encode64Bytes(c)
			want := bid64Bytes(v.EncodedHex)
			if err != nil || !bytes.Equal(got[:], want) {
				t.Errorf("%s encode_bytes64: got %x err=%v, want %x", label, got, err, want)
			}
		}
	case "bid128":
		decoded, err := Decode128Bytes(bid128Bytes(v.Hex, v.HexHi))
		if err != nil {
			t.Errorf("%s decode_bytes128: %v", label, err)
			return
		}
		if !checkDecode(t, label+" decode_bytes128", decoded, v) {
			return
		}
		if v.Canonical {
			got, err := Encode128Bytes(c)
			want := bid128Bytes(v.EncodedHex, v.EncodedHi)
			if err != nil || !bytes.Equal(got[:], want) {
				t.Errorf("%s encode_bytes128: got %x err=%v, want %x", label, got, err, want)
			}
		}
	default:
		t.Fatalf("unknown type: %s", v.Type)
	}
}

func checkStringRoundtrip(t *testing.T, label string, c Components, v vectorEntry) {
	t.Helper()
	gotString, err := ToString(c)
	if err != nil {
		t.Errorf("%s to_string: unexpected error: %v", label, err)
		return
	}
	if gotString != v.DecimalString {
		t.Errorf("%s to_string: got %q, want %q", label, gotString, v.DecimalString)
	}
	parsed, err := FromString(v.DecimalString)
	if err != nil {
		t.Errorf("%s from_string(%q): %v", label, v.DecimalString, err)
		return
	}
	switch v.Type {
	case "bid32":
		enc, err := Encode32(parsed)
		got := fmt.Sprintf("%08x", enc)
		if err != nil || got != v.EncodedHex {
			t.Errorf("%s from_string encode32: got %s err=%v, want %s", label, got, err, v.EncodedHex)
		}
	case "bid64":
		enc, err := Encode64(parsed)
		got := fmt.Sprintf("%016x", enc)
		if err != nil || got != v.EncodedHex {
			t.Errorf("%s from_string encode64: got %s err=%v, want %s", label, got, err, v.EncodedHex)
		}
	case "bid128":
		gotLo, gotHi, err := Encode128(parsed)
		gotLoHex := fmt.Sprintf("%016x", gotLo)
		gotHiHex := fmt.Sprintf("%016x", gotHi)
		if err != nil || gotLoHex != v.EncodedHex || gotHiHex != v.EncodedHi {
			t.Errorf("%s from_string encode128: got lo=%s hi=%s err=%v, want lo=%s hi=%s",
				label, gotLoHex, gotHiHex, err, v.EncodedHex, v.EncodedHi)
		}
	}
}
