// Code generated by testgen; DO NOT EDIT.


use std::io::{self, BufRead, Write};

use bid754::{Decimal128, Decimal32, Decimal64, ExceptionFlags, RoundingMode};
use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Case {
    width: u32,
    op: String,
    mode: String,
    operands: Vec<String>,
}

#[derive(Serialize)]
struct Observation {
    path: String,
    bits: String,
    flags: u32,
    has_flags: bool,
}

fn public_mode(mode: &str) -> Option<RoundingMode> {
    Some(match mode {
        "nearest_even" => RoundingMode::NearestEven,
        "nearest_away" => RoundingMode::NearestAway,
        "toward_zero" => RoundingMode::TowardZero,
        "toward_positive" => RoundingMode::TowardPositive,
        "toward_negative" => RoundingMode::TowardNegative,
        _ => return None,
    })
}

fn port_rounding(mode: &str) -> Option<i64> {
    Some(match mode {
        "nearest_even" => 0,
        "toward_negative" => 1,
        "toward_positive" => 2,
        "toward_zero" => 3,
        "nearest_away" => 4,
        _ => return None,
    })
}

fn map_public_flags(f: ExceptionFlags) -> Result<u32, String> {
    let raw = f.bits();
    if raw & !0x1f != 0 {
        return Err(format!("public flags {raw:#x} carry bits outside the IEEE arithmetic set"));
    }
    let mut native = 0u32;
    if raw & 0x01 != 0 {
        native |= 0x20;
    }
    if raw & 0x02 != 0 {
        native |= 0x10;
    }
    if raw & 0x04 != 0 {
        native |= 0x08;
    }
    if raw & 0x08 != 0 {
        native |= 0x04;
    }
    if raw & 0x10 != 0 {
        native |= 0x01;
    }
    Ok(native)
}

fn hex32(v: u32) -> String {
    format!("{v:08x}")
}

fn hex64(v: u64) -> String {
    format!("{v:016x}")
}

fn hex128(hi: u64, lo: u64) -> String {
    format!("{hi:016x}:{lo:016x}")
}

fn dec128_hex(v: Decimal128) -> String {
    let b = v.to_le_bytes();
    let mut lo = [0u8; 8];
    let mut hi = [0u8; 8];
    lo.copy_from_slice(&b[0..8]);
    hi.copy_from_slice(&b[8..16]);
    hex128(u64::from_le_bytes(hi), u64::from_le_bytes(lo))
}

fn bid128(hi: u64, lo: u64) -> bid754::gen_types::BID_UINT128 {
    bid754::gen_types::BID_UINT128 { lo, hi }
}

fn push_value(obs: &mut Vec<Observation>, path: &str, bits: String) {
    obs.push(Observation {
        path: path.to_string(),
        bits,
        flags: 0,
        has_flags: false,
    });
}

fn push_mapped(
    obs: &mut Vec<Observation>,
    path: &str,
    bits: String,
    f: ExceptionFlags,
) -> Result<(), String> {
    let native = map_public_flags(f)?;
    obs.push(Observation {
        path: path.to_string(),
        bits,
        flags: native,
        has_flags: true,
    });
    Ok(())
}

fn push_port(obs: &mut Vec<Observation>, bits: String, native: u32) {
    obs.push(Observation {
        path: "rust/port".to_string(),
        bits,
        flags: native,
        has_flags: true,
    });
}

fn want_operands(op: &str) -> Result<usize, String> {
    match op {
        "add" | "sub" | "mul" | "div" | "quantize" => Ok(2),
        "fma" => Ok(3),
        _ => Err(format!("unsupported operation {op:?}")),
    }
}

fn observe(case: &Case) -> Result<Vec<Observation>, String> {
    let length = match case.width { 32 => 8, 64 => 16, 128 => 33, other => return Err(format!("unsupported decimal width {other}")) };
    for raw in &case.operands {
        if raw.len() != length { return Err(format!("raw image must have {length} characters")); }
        for (i, b) in raw.bytes().enumerate() {
            if case.width == 128 && i == 16 {
                if b != b':' { return Err("raw image requires hi:lo separator".into()); }
            } else if !b.is_ascii_digit() && !(b'a'..=b'f').contains(&b) { return Err("raw image must be padded lowercase hex".into()); }
        }
    }
    let mode = public_mode(&case.mode)
        .ok_or_else(|| format!("unsupported rounding mode {:?}", case.mode))?;
    let rnd = port_rounding(&case.mode)
        .ok_or_else(|| format!("unsupported rounding mode {:?}", case.mode))?;
    let nearest_even = case.mode == "nearest_even";
    match case.width {
        32 => observe32(case, mode, rnd, nearest_even),
        64 => observe64(case, mode, rnd, nearest_even),
        128 => observe128(case, mode, rnd, nearest_even),
        other => Err(format!("unsupported decimal width {other}")),
    }
}

fn observe32(
    case: &Case,
    mode: RoundingMode,
    rnd: i64,
    nearest_even: bool,
) -> Result<Vec<Observation>, String> {
    let want = want_operands(&case.op)?;
    if case.operands.len() != want {
        return Err(format!(
            "op {:?} requires {} operands, got {}",
            case.op,
            want,
            case.operands.len()
        ));
    }
    let mut raws = Vec::with_capacity(case.operands.len());
    for raw in &case.operands {
        raws.push(
            u32::from_str_radix(raw, 16)
                .map_err(|e| format!("invalid decimal32 raw image {raw:?}: {e}"))?,
        );
    }
    let xb = raws[0];
    let yb = raws[1];
    let x = Decimal32::from_bits(xb);
    let y = Decimal32::from_bits(yb);
    let mut obs = Vec::new();

    match case.op.as_str() {
        "add" => {
            let (mv, mf) = x.add_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_status::bid32_add_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex32(x.add(y).to_bits()));
                let (fv, ff) = x.add_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        "sub" => {
            let (mv, mf) = x.sub_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_status::bid32_sub_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex32(x.sub(y).to_bits()));
                let (fv, ff) = x.sub_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        "mul" => {
            let (mv, mf) = x.mul_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_status::bid32_mul_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex32(x.mul(y).to_bits()));
                let (fv, ff) = x.mul_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        "div" => {
            let (mv, mf) = x.div_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_status::bid32_div_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex32(x.div(y).to_bits()));
                let (fv, ff) = x.div_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        "quantize" => {
            let (mv, mf) = x.quantize_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_quantize::bid32_quantize(xb, yb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex32(x.quantize(y).to_bits()));
                let (fv, ff) = x.quantize_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        "fma" => {
            let zb = raws[2];
            let z = Decimal32::from_bits(zb);
            let (mv, mf) = x.fma_with_mode(y, z, mode);
            push_mapped(&mut obs, "rust/public/mode", hex32(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::bid32_fma::bid32_fma(xb, yb, zb, rnd);
            push_port(&mut obs, hex32(pb), pf);
            if nearest_even {
                let (fv, ff) = x.fma(y, z);
                push_mapped(&mut obs, "rust/public/flags", hex32(fv.to_bits()), ff)?;
            }
        }
        other => return Err(format!("unsupported operation {other:?}")),
    }
    Ok(obs)
}

fn observe64(
    case: &Case,
    mode: RoundingMode,
    rnd: i64,
    nearest_even: bool,
) -> Result<Vec<Observation>, String> {
    let want = want_operands(&case.op)?;
    if case.operands.len() != want {
        return Err(format!(
            "op {:?} requires {} operands, got {}",
            case.op,
            want,
            case.operands.len()
        ));
    }
    let mut raws = Vec::with_capacity(case.operands.len());
    for raw in &case.operands {
        raws.push(
            u64::from_str_radix(raw, 16)
                .map_err(|e| format!("invalid decimal64 raw image {raw:?}: {e}"))?,
        );
    }
    let xb = raws[0];
    let yb = raws[1];
    let x = Decimal64::from_bits(xb);
    let y = Decimal64::from_bits(yb);
    let mut obs = Vec::new();

    match case.op.as_str() {
        "add" => {
            let (mv, mf) = x.add_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::add64::bid64_add_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex64(x.add(y).to_bits()));
                let (fv, ff) = x.add_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        "sub" => {
            let (mv, mf) = x.sub_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::add64::bid64_sub_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex64(x.sub(y).to_bits()));
                let (fv, ff) = x.sub_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        "mul" => {
            let (mv, mf) = x.mul_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::mul64::bid64_mul_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex64(x.mul(y).to_bits()));
                let (fv, ff) = x.mul_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        "div" => {
            let (mv, mf) = x.div_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::div64::bid64_div_with_flags(xb, yb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex64(x.div(y).to_bits()));
                let (fv, ff) = x.div_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        "quantize" => {
            let (mv, mf) = x.quantize_with_mode(y, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::quantize64::bid64_quantize(xb, yb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", hex64(x.quantize(y).to_bits()));
                let (fv, ff) = x.quantize_with_flags(y);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        "fma" => {
            let zb = raws[2];
            let z = Decimal64::from_bits(zb);
            let (mv, mf) = x.fma_with_mode(y, z, mode);
            push_mapped(&mut obs, "rust/public/mode", hex64(mv.to_bits()), mf)?;
            let (pb, pf) = bid754::generated::fma64::bid64_fma(xb, yb, zb, rnd);
            push_port(&mut obs, hex64(pb), pf);
            if nearest_even {
                let (fv, ff) = x.fma(y, z);
                push_mapped(&mut obs, "rust/public/flags", hex64(fv.to_bits()), ff)?;
            }
        }
        other => return Err(format!("unsupported operation {other:?}")),
    }
    Ok(obs)
}

struct Operand128 {
    dec: Decimal128,
    hi: u64,
    lo: u64,
}

fn parse128(operands: &[String]) -> Result<Vec<Operand128>, String> {
    let mut out = Vec::with_capacity(operands.len());
    for raw in operands {
        let parts: Vec<&str> = raw.split(':').collect();
        if parts.len() != 2 {
            return Err(format!("invalid decimal128 raw image {raw:?}"));
        }
        let hi = u64::from_str_radix(parts[0], 16)
            .map_err(|e| format!("invalid decimal128 hi in {raw:?}: {e}"))?;
        let lo = u64::from_str_radix(parts[1], 16)
            .map_err(|e| format!("invalid decimal128 lo in {raw:?}: {e}"))?;
        let mut bytes = [0u8; 16];
        bytes[0..8].copy_from_slice(&lo.to_le_bytes());
        bytes[8..16].copy_from_slice(&hi.to_le_bytes());
        out.push(Operand128 {
            dec: Decimal128::from_le_bytes(bytes),
            hi,
            lo,
        });
    }
    Ok(out)
}

fn observe128(
    case: &Case,
    mode: RoundingMode,
    rnd: i64,
    nearest_even: bool,
) -> Result<Vec<Observation>, String> {
    let want = want_operands(&case.op)?;
    if case.operands.len() != want {
        return Err(format!(
            "op {:?} requires {} operands, got {}",
            case.op,
            want,
            case.operands.len()
        ));
    }
    let ops = parse128(&case.operands)?;
    let x = &ops[0];
    let y = &ops[1];
    let mut obs = Vec::new();

    match case.op.as_str() {
        "add" => {
            let (mv, mf) = x.dec.add_with_mode(y.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let mut pf = 0u32;
            let r = bid754::generated::bid128_add::bid128_add(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                rnd,
                &mut pf,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", dec128_hex(x.dec.add(y.dec)));
                let (fv, ff) = x.dec.add_with_flags(y.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        "sub" => {
            let (mv, mf) = x.dec.sub_with_mode(y.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let mut pf = 0u32;
            let r = bid754::generated::bid128_add::bid128_sub(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                rnd,
                &mut pf,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", dec128_hex(x.dec.sub(y.dec)));
                let (fv, ff) = x.dec.sub_with_flags(y.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        "mul" => {
            let (mv, mf) = x.dec.mul_with_mode(y.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let (r, pf) = bid754::generated::bid128_mul::bid128_mul(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                rnd,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", dec128_hex(x.dec.mul(y.dec)));
                let (fv, ff) = x.dec.mul_with_flags(y.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        "div" => {
            let (mv, mf) = x.dec.div_with_mode(y.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let (r, pf) = bid754::generated::bid128_div::bid128_div(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                rnd,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", dec128_hex(x.dec.div(y.dec)));
                let (fv, ff) = x.dec.div_with_flags(y.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        "quantize" => {
            let (mv, mf) = x.dec.quantize_with_mode(y.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let (r, pf) = bid754::generated::bid128_quantize::bid128_quantize(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                rnd,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                push_value(&mut obs, "rust/public/value", dec128_hex(x.dec.quantize(y.dec)));
                let (fv, ff) = x.dec.quantize_with_flags(y.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        "fma" => {
            let z = &ops[2];
            let (mv, mf) = x.dec.fma_with_mode(y.dec, z.dec, mode);
            push_mapped(&mut obs, "rust/public/mode", dec128_hex(mv), mf)?;
            let (r, pf) = bid754::generated::bid128_fma::bid128_fma(
                bid128(x.hi, x.lo),
                bid128(y.hi, y.lo),
                bid128(z.hi, z.lo),
                rnd,
            );
            push_port(&mut obs, hex128(r.hi, r.lo), pf);
            if nearest_even {
                let (fv, ff) = x.dec.fma(y.dec, z.dec);
                push_mapped(&mut obs, "rust/public/flags", dec128_hex(fv), ff)?;
            }
        }
        other => return Err(format!("unsupported operation {other:?}")),
    }
    Ok(obs)
}

fn run() -> Result<(), String> {
    let stdin = io::stdin();
    let stdout = io::stdout();
    let mut out = stdout.lock();
    for line in stdin.lock().lines() {
        let line = line.map_err(|e| e.to_string())?;
        if line.trim().is_empty() { return Err("empty case record".into()); }
        let case: Case = serde_json::from_str(&line).map_err(|e| format!("parse case: {e}"))?;
        let obs = observe(&case)?;
        let encoded = serde_json::to_string(&obs).map_err(|e| e.to_string())?;
        writeln!(out, "{encoded}").map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn main() {
    if let Err(e) = run() {
        eprintln!("finite_probe: {e}");
        std::process::exit(1);
    }
}
