// Code generated by testgen; DO NOT EDIT.

use std::io::{self, BufRead, Read, Write};
use bid754::{Decimal32,Decimal64,Decimal128,ExceptionFlags,RoundingMode};
use serde::{Deserialize,Serialize};

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Case {
 width: u32,
 op: String,
 mode: String,
 #[serde(deserialize_with="deserialize_operands")]
 operands: Vec<String>,
 param: String,
 target: u32,
}
fn deserialize_operands<'de,D:serde::Deserializer<'de>>(d:D)->Result<Vec<String>,D::Error> {
 match Option::<Vec<String>>::deserialize(d)? {
  Some(operands)=>Ok(operands),
  None=>Ok(Vec::new()),
 }
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Request {version: u32, case: Case}
#[derive(Serialize)]
struct Observation {
 path: String,
 kind: String,
 width: u32,
 value: String,
 flags: u32,
 has_flags: bool,
}
#[derive(Serialize)]
struct Response {version: u32, observations: Vec<Observation>}

fn public_mode(mode: &str) -> Option<RoundingMode> {
 Some(match mode {
 "nearest_even"=>RoundingMode::NearestEven,
 "nearest_away"=>RoundingMode::NearestAway,
 "toward_zero"=>RoundingMode::TowardZero,
 "toward_positive"=>RoundingMode::TowardPositive,
 "toward_negative"=>RoundingMode::TowardNegative,
 _=>return None,
 })
}
fn port_rounding(mode: &str) -> Option<i64> {
 Some(match mode {
 "nearest_even"=>0,"toward_negative"=>1,"toward_positive"=>2,"toward_zero"=>3,"nearest_away"=>4,
 _=>return None,
 })
}
fn map_public_flags(flags: ExceptionFlags) -> Result<u32,String> {
 let raw=flags.bits();
 if raw & !0x1f != 0 {return Err(format!("unexpected public flags {raw:#x}"));}
 let mut native=0;
 for (public,port) in [(1,0x20),(2,0x10),(4,8),(8,4),(16,1)] {
  if raw & public != 0 {native |= port;}
 }
 Ok(native)
}
fn push(obs: &mut Vec<Observation>,path: &str,kind: &str,width: u32,value: String,flags: u32,has_flags: bool) -> Result<(),String> {
 if flags & !0x3d != 0 || !has_flags && flags != 0 {return Err(format!("invalid observation flags {flags:#x}"));}
 obs.push(Observation{path:path.into(),kind:kind.into(),width,value,flags,has_flags});
 Ok(())
}
fn hex32(v:u32)->String {format!("{v:08x}")}
fn hex64(v:u64)->String {format!("{v:016x}")}
fn hex128(hi:u64,lo:u64)->String {format!("{hi:016x}:{lo:016x}")}
fn dec128_hex(v:Decimal128)->String {
 let b=v.to_le_bytes();
 let mut hi=[0;8];let mut lo=[0;8];
 hi.copy_from_slice(&b[8..]);lo.copy_from_slice(&b[..8]);
 hex128(u64::from_le_bytes(hi),u64::from_le_bytes(lo))
}
fn parse128(s:&str)->Result<(Decimal128,bid754::gen_types::BID_UINT128),String> {
 let (h,l)=s.split_once(':').ok_or("invalid decimal128")?;
 let hi=u64::from_str_radix(h,16).map_err(|e|e.to_string())?;
 let lo=u64::from_str_radix(l,16).map_err(|e|e.to_string())?;
 let mut b=[0;16];b[..8].copy_from_slice(&lo.to_le_bytes());b[8..].copy_from_slice(&hi.to_le_bytes());
 Ok((Decimal128::from_le_bytes(b),bid754::gen_types::BID_UINT128{lo,hi}))
}
fn canonical_integer(s:&str,signed:bool,bits:u32)->Result<(),String> {
 if signed {
  let n=s.parse::<i64>().map_err(|e|e.to_string())?;
  if n.to_string()!=s || bits==32 && i32::try_from(n).is_err() {return Err("invalid signed integer parameter".into());}
 } else {
  let n=s.parse::<u64>().map_err(|e|e.to_string())?;
  if n.to_string()!=s || bits==32 && u32::try_from(n).is_err() {return Err("invalid unsigned integer parameter".into());}
 }
 Ok(())
}
fn validate(c:&Case)->Result<(),String> {
 let length=match c.width {32=>8,64=>16,128=>33,_=>return Err("invalid decimal width".into())};
 if public_mode(&c.mode).is_none() {return Err("invalid rounding mode".into());}
 let arity=match c.op.as_str() {
 "from_int"|"from_uint"=>{
  if c.target!=32 && c.target!=64 {return Err("invalid integer input width".into());}
  canonical_integer(&c.param,c.op=="from_int",c.target)?;
  0
 },
 "to_int"|"to_uint"|"to_int_exact"|"to_uint_exact"=>{
  if ![8,16,32,64].contains(&c.target) || !c.param.is_empty() {return Err("invalid integer output shape".into());}
  1
 },
 "convert"=>{
  if ![32,64,128].contains(&c.target) || c.target==c.width || !c.param.is_empty() {return Err("invalid decimal conversion shape".into());}
  1
 },
 "scaleb"=>{
  if c.target!=0 {return Err("invalid scale target".into());}
  canonical_integer(&c.param,true,64)?;
  1
 },
 "rem"|"fmod"|"minnum"|"maxnum"|
 "quiet_equal"|"quiet_not_equal"|"quiet_greater"|"quiet_greater_equal"|"quiet_greater_unordered"|
 "quiet_less"|"quiet_less_equal"|"quiet_less_unordered"|"quiet_not_greater"|"quiet_not_less"|"quiet_ordered"|"quiet_unordered"=>{
  if c.target!=0 || !c.param.is_empty() {return Err("invalid binary operation shape".into());}
  2
 },
 _=>return Err("invalid operation".into()),
 };
 if c.operands.len()!=arity {return Err("invalid operand count".into());}
 for raw in &c.operands {
  if raw.len()!=length {return Err("invalid raw width".into());}
  for (i,b) in raw.bytes().enumerate() {
   if c.width==128 && i==16 {
    if b!=b':' {return Err("invalid hi:lo separator".into());}
   } else if !b.is_ascii_digit() && !(b'a'..=b'f').contains(&b) {return Err("invalid lowercase raw hex".into());}
  }
 }
 Ok(())
}
fn observe(c: &Case) -> Result<Vec<Observation>,String> {
validate(c)?;
let mode=public_mode(&c.mode).ok_or("invalid mode")?;
let rnd=port_rounding(&c.mode).ok_or("invalid mode")?;
match (c.width,c.op.as_str(),c.target) {
(32,"rem",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.remainder(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_rem::bid32_rem(xb, yb);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"fmod",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.fmod(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_misc::bid32_fmod(xb, yb);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"minnum",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.min_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_status::bid32_min_num_with_flags(xb, yb);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"maxnum",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.max_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_status::bid32_max_num_with_flags(xb, yb);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"quiet_equal",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_eq(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_not_equal",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ne(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_not_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_greater",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_greater_equal",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ge(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_greater_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_greater_unordered",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_greater_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_less",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_less_equal",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_le(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_less_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_less_unordered",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_less_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_not_greater",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_not_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_not_less",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_not_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_ordered",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_ordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"quiet_unordered",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let yb=u32::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal32::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare32::bid32_quiet_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(32,"scaleb",0) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=x.scaleb_with_mode(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_status::bid32_scalbln_with_flags(xb, n, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
if c.mode=="nearest_even" {
let (pv,public_flags)=x.scaleb(n); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",32,hex32(pv.to_bits()),mapped,true)?;
}
Ok(obs)
},
(32,"convert",64) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal64(); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_to_bid64::bid32_to_bid64(xb);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(32,"convert",128) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal128(); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_misc::bid32_to_bid128(xb);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(32,"from_int",32) => {
let n=c.param.parse::<i32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal32::from_i32(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_from_int::bid32_from_int32(n, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"from_int",64) => {
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal32::from_i64(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_to_int::bid32_from_int64(n, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"to_int",8) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int8_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int8_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int8_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int8_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int",16) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int16_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int16_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int16_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int16_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int",32) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int32_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int32_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int32_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int32_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int",64) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int64_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int64_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int64_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int64_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int_exact",8) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int8_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int8_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int8_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int8_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int_exact",16) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int16_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int16_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int16_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int16_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int_exact",32) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int32_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int32_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int32_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int32_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_int_exact",64) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_int64_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_int64_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_int64_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_int64_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_int64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"from_uint",32) => {
let n=c.param.parse::<u32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal32::from_u32(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_from_int::bid32_from_uint32(n, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"from_uint",64) => {
let n=c.param.parse::<u64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal32::from_u64(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid32_to_int::bid32_from_uint64(n, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(32,"to_uint",8) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint8_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint8_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint8_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint8_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint",16) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint16_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint16_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint16_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint16_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint",32) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint32_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint32_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint32_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint32_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint",64) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint64_rnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint64_rninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint64_int(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint64_ceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint_exact",8) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint8_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint8_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint8_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint8_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint_exact",16) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint16_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint16_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint16_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint16_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint_exact",32) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint32_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint32_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint32_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint32_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(32,"to_uint_exact",64) => {
let xb=u32::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal32::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid32_to_int::bid32_to_uint64_xrnint(xb),
"nearest_away" => bid754::generated::bid32_to_int::bid32_to_uint64_xrninta(xb),
"toward_zero" => bid754::generated::bid32_to_int::bid32_to_uint64_xint(xb),
"toward_positive" => bid754::generated::bid32_to_int::bid32_to_uint64_xceil(xb),
"toward_negative" => bid754::generated::bid32_to_int::bid32_to_uint64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"rem",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.remainder(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::rem64::bid64_rem(xb, yb);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"fmod",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.fmod(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::fmod64::bid64_fmod(xb, yb);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"minnum",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.min_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::minmax64::bid64_min_num(xb, yb);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"maxnum",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.max_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::minmax64::bid64_max_num(xb, yb);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"quiet_equal",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_eq(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_not_equal",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ne(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_not_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_greater",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_greater_equal",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ge(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_greater_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_greater_unordered",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_greater_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_less",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_less_equal",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_le(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_less_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_less_unordered",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_less_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_not_greater",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_not_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_not_less",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_not_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_ordered",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_ordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"quiet_unordered",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let yb=u64::from_str_radix(&c.operands[1],16).map_err(|e|e.to_string())?;
let y=Decimal64::from_bits(yb);
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::compare64::bid64_quiet_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(64,"scaleb",0) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=x.scaleb_with_mode(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::scalb64::bid64_scalbln(xb, n, rnd);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
if c.mode=="nearest_even" {
let (pv,public_flags)=x.scaleb(n); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",64,hex64(pv.to_bits()),mapped,true)?;
}
Ok(obs)
},
(64,"convert",32) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::to_bid3264::bid64_to_bid32(xb, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(64,"convert",128) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal128(); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let (pr, praw) = bid754::generated::to_bid12864::bid64_to_bid128(xb);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(64,"from_int",32) => {
let n=c.param.parse::<i32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal64::from(n);
push(&mut obs,"rust/public/value","decimal",64,hex64(pv.to_bits()),0,false)?;
let pr=bid754::generated::convert64::bid64_from_int32(n);
push(&mut obs,"rust/port","decimal",64,hex64(pr),0,false)?;
Ok(obs)
},
(64,"from_int",64) => {
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal64::from_i64(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::convert64::bid64_from_int64(n, rnd);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"to_int",8) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int_small::bid64_to_int8_rnint(xb),
"nearest_away" => bid754::generated::to_int_small::bid64_to_int8_rninta(xb),
"toward_zero" => bid754::generated::to_int_small::bid64_to_int8_int(xb),
"toward_positive" => bid754::generated::to_int_small::bid64_to_int8_ceil(xb),
"toward_negative" => bid754::generated::to_int_small::bid64_to_int8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int",16) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int_small::bid64_to_int16_rnint(xb),
"nearest_away" => bid754::generated::to_int_small::bid64_to_int16_rninta(xb),
"toward_zero" => bid754::generated::to_int_small::bid64_to_int16_int(xb),
"toward_positive" => bid754::generated::to_int_small::bid64_to_int16_ceil(xb),
"toward_negative" => bid754::generated::to_int_small::bid64_to_int16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int",32) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int32::bid64_to_int32_rnint(xb),
"nearest_away" => bid754::generated::to_int32_rninta::bid64_to_int32_rninta(xb),
"toward_zero" => bid754::generated::to_int32_int::bid64_to_int32_int(xb),
"toward_positive" => bid754::generated::to_int32_ceil::bid64_to_int32_ceil(xb),
"toward_negative" => bid754::generated::to_int32_floor::bid64_to_int32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int",64) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int64_signed::bid64_to_int64_rnint(xb),
"nearest_away" => bid754::generated::to_int64_signed::bid64_to_int64_rninta(xb),
"toward_zero" => bid754::generated::to_int64_int::bid64_to_int64_int(xb),
"toward_positive" => bid754::generated::to_int64_ceil::bid64_to_int64_ceil(xb),
"toward_negative" => bid754::generated::to_int64_floor::bid64_to_int64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int_exact",8) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int_small::bid64_to_int8_xrnint(xb),
"nearest_away" => bid754::generated::to_int_small::bid64_to_int8_xrninta(xb),
"toward_zero" => bid754::generated::to_int_small::bid64_to_int8_xint(xb),
"toward_positive" => bid754::generated::to_int_small::bid64_to_int8_xceil(xb),
"toward_negative" => bid754::generated::to_int_small::bid64_to_int8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int_exact",16) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int_small::bid64_to_int16_xrnint(xb),
"nearest_away" => bid754::generated::to_int_small::bid64_to_int16_xrninta(xb),
"toward_zero" => bid754::generated::to_int_small::bid64_to_int16_xint(xb),
"toward_positive" => bid754::generated::to_int_small::bid64_to_int16_xceil(xb),
"toward_negative" => bid754::generated::to_int_small::bid64_to_int16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int_exact",32) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int32::bid64_to_int32_xrnint(xb),
"nearest_away" => bid754::generated::to_int32_rninta::bid64_to_int32_xrninta(xb),
"toward_zero" => bid754::generated::to_int32_int::bid64_to_int32_xint(xb),
"toward_positive" => bid754::generated::to_int32_ceil::bid64_to_int32_xceil(xb),
"toward_negative" => bid754::generated::to_int32_floor::bid64_to_int32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_int_exact",64) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_int64_signed::bid64_to_int64_xrnint(xb),
"nearest_away" => bid754::generated::to_int64_signed::bid64_to_int64_xrninta(xb),
"toward_zero" => bid754::generated::to_int64_int::bid64_to_int64_xint(xb),
"toward_positive" => bid754::generated::to_int64_ceil::bid64_to_int64_xceil(xb),
"toward_negative" => bid754::generated::to_int64_floor::bid64_to_int64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"from_uint",32) => {
let n=c.param.parse::<u32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal64::from(n);
push(&mut obs,"rust/public/value","decimal",64,hex64(pv.to_bits()),0,false)?;
let pr=bid754::generated::convert64::bid64_from_uint32(n);
push(&mut obs,"rust/port","decimal",64,hex64(pr),0,false)?;
Ok(obs)
},
(64,"from_uint",64) => {
let n=c.param.parse::<u64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=Decimal64::from_u64(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::convert64::bid64_from_uint64(n, rnd);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(64,"to_uint",8) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint_small::bid64_to_uint8_rnint(xb),
"nearest_away" => bid754::generated::to_uint_small::bid64_to_uint8_rninta(xb),
"toward_zero" => bid754::generated::to_uint_small::bid64_to_uint8_int(xb),
"toward_positive" => bid754::generated::to_uint_small::bid64_to_uint8_ceil(xb),
"toward_negative" => bid754::generated::to_uint_small::bid64_to_uint8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint",16) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint_small::bid64_to_uint16_rnint(xb),
"nearest_away" => bid754::generated::to_uint_small::bid64_to_uint16_rninta(xb),
"toward_zero" => bid754::generated::to_uint_small::bid64_to_uint16_int(xb),
"toward_positive" => bid754::generated::to_uint_small::bid64_to_uint16_ceil(xb),
"toward_negative" => bid754::generated::to_uint_small::bid64_to_uint16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint",32) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint32_rnint::bid64_to_uint32_rnint(xb),
"nearest_away" => bid754::generated::to_uint32_rninta::bid64_to_uint32_rninta(xb),
"toward_zero" => bid754::generated::to_uint32_int::bid64_to_uint32_int(xb),
"toward_positive" => bid754::generated::to_uint32_ceil::bid64_to_uint32_ceil(xb),
"toward_negative" => bid754::generated::to_uint32_floor::bid64_to_uint32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint",64) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint64_rnint::bid64_to_uint64_rnint(xb),
"nearest_away" => bid754::generated::to_uint64_rninta::bid64_to_uint64_rninta(xb),
"toward_zero" => bid754::generated::to_uint64_int::bid64_to_uint64_int(xb),
"toward_positive" => bid754::generated::to_uint64_ceil::bid64_to_uint64_ceil(xb),
"toward_negative" => bid754::generated::to_uint64_floor::bid64_to_uint64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint_exact",8) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint_small::bid64_to_uint8_xrnint(xb),
"nearest_away" => bid754::generated::to_uint_small::bid64_to_uint8_xrninta(xb),
"toward_zero" => bid754::generated::to_uint_small::bid64_to_uint8_xint(xb),
"toward_positive" => bid754::generated::to_uint_small::bid64_to_uint8_xceil(xb),
"toward_negative" => bid754::generated::to_uint_small::bid64_to_uint8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint_exact",16) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint_small::bid64_to_uint16_xrnint(xb),
"nearest_away" => bid754::generated::to_uint_small::bid64_to_uint16_xrninta(xb),
"toward_zero" => bid754::generated::to_uint_small::bid64_to_uint16_xint(xb),
"toward_positive" => bid754::generated::to_uint_small::bid64_to_uint16_xceil(xb),
"toward_negative" => bid754::generated::to_uint_small::bid64_to_uint16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint_exact",32) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint32_rnint::bid64_to_uint32_xrnint(xb),
"nearest_away" => bid754::generated::to_uint32_rninta::bid64_to_uint32_xrninta(xb),
"toward_zero" => bid754::generated::to_uint32_int::bid64_to_uint32_xint(xb),
"toward_positive" => bid754::generated::to_uint32_ceil::bid64_to_uint32_xceil(xb),
"toward_negative" => bid754::generated::to_uint32_floor::bid64_to_uint32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(64,"to_uint_exact",64) => {
let xb=u64::from_str_radix(&c.operands[0],16).map_err(|e|e.to_string())?;
let x=Decimal64::from_bits(xb);
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::to_uint64_rnint::bid64_to_uint64_xrnint(xb),
"nearest_away" => bid754::generated::to_uint64_rninta::bid64_to_uint64_xrninta(xb),
"toward_zero" => bid754::generated::to_uint64_int::bid64_to_uint64_xint(xb),
"toward_positive" => bid754::generated::to_uint64_ceil::bid64_to_uint64_xceil(xb),
"toward_negative" => bid754::generated::to_uint64_floor::bid64_to_uint64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"rem",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.remainder(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_rem::bid128_rem(xb, yb);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(128,"fmod",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.fmod(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_rem::bid128_fmod(xb, yb);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(128,"minnum",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.min_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let mut praw = 0u32;
        let pr = bid754::generated::bid128_minmax::bid128_minnum(xb, yb, &mut praw);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(128,"maxnum",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.max_num(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
let mut praw = 0u32;
        let pr = bid754::generated::bid128_minmax::bid128_maxnum(xb, yb, &mut praw);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
Ok(obs)
},
(128,"quiet_equal",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_eq(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_not_equal",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ne(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_not_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_greater",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_greater_equal",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ge(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_greater_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_greater_unordered",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_gt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_greater_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_less",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_less_equal",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_le(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_less_equal(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_less_unordered",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_lt_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_less_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_not_greater",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_gt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_not_greater(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_not_less",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_not_lt(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_not_less(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_ordered",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_ordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_ordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"quiet_unordered",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let (y,yb)=parse128(&c.operands[1])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.quiet_unordered(y); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","bool",0,pv.to_string(),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_compare::bid128_quiet_unordered(xb, yb);
push(&mut obs,"rust/port","bool",0,(pr != 0).to_string(),praw,true)?;
Ok(obs)
},
(128,"scaleb",0) => {
let (x,xb)=parse128(&c.operands[0])?;
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let (pv,public_flags)=x.scaleb_with_mode(n,mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",128,dec128_hex(pv),mapped,true)?;
let mut praw = 0u32;
        let pr = bid754::generated::bid128_misc::bid128_scalbln(xb, n, rnd, &mut praw);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),praw,true)?;
if c.mode=="nearest_even" {
let (pv,public_flags)=x.scaleb(n); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/flags","decimal",128,dec128_hex(pv),mapped,true)?;
}
Ok(obs)
},
(128,"convert",32) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",32,hex32(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_conversions::bid128_to_bid32(xb, rnd);
push(&mut obs,"rust/port","decimal",32,hex32(pr),praw,true)?;
Ok(obs)
},
(128,"convert",64) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_decimal64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","decimal",64,hex64(pv.to_bits()),mapped,true)?;
let (pr, praw) = bid754::generated::bid128_conversions::bid128_to_bid64(xb, rnd);
push(&mut obs,"rust/port","decimal",64,hex64(pr),praw,true)?;
Ok(obs)
},
(128,"from_int",32) => {
let n=c.param.parse::<i32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal128::from(n);
push(&mut obs,"rust/public/value","decimal",128,dec128_hex(pv),0,false)?;
let pr=bid754::generated::bid128_from_int::bid128_from_int32(n);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),0,false)?;
Ok(obs)
},
(128,"from_int",64) => {
let n=c.param.parse::<i64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal128::from(n);
push(&mut obs,"rust/public/value","decimal",128,dec128_hex(pv),0,false)?;
let pr=bid754::generated::bid128_from_int::bid128_from_int64(n);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),0,false)?;
Ok(obs)
},
(128,"to_int",8) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int8_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int8_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int8_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int8_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int",16) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int16_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int16_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int16_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int16_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int",32) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int32_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int32_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int32_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int32_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int",64) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int64_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int64_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int64_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int64_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int_exact",8) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int8_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int8_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int8_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int8_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int_exact",16) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int16_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int16_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int16_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int16_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int_exact",32) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int32_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int32_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int32_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int32_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_int_exact",64) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_i64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_int64_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_int64_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_int64_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_int64_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_int64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"from_uint",32) => {
let n=c.param.parse::<u32>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal128::from(n);
push(&mut obs,"rust/public/value","decimal",128,dec128_hex(pv),0,false)?;
let pr=bid754::generated::bid128_from_int::bid128_from_uint32(n);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),0,false)?;
Ok(obs)
},
(128,"from_uint",64) => {
let n=c.param.parse::<u64>().map_err(|e|e.to_string())?;
let mut obs=Vec::new();
let pv=Decimal128::from(n);
push(&mut obs,"rust/public/value","decimal",128,dec128_hex(pv),0,false)?;
let pr=bid754::generated::bid128_from_int::bid128_from_uint64(n);
push(&mut obs,"rust/port","decimal",128,hex128(pr.hi,pr.lo),0,false)?;
Ok(obs)
},
(128,"to_uint",8) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint8_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint8_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint8_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint8_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint8_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint",16) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint16_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint16_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint16_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint16_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint16_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint",32) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint32_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint32_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint32_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint32_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint32_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint",64) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint64_rnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint64_rninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint64_int(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint64_ceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint64_floor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint_exact",8) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u8_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",8,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint8_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint8_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint8_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint8_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint8_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",8,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint_exact",16) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u16_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",16,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint16_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint16_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint16_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint16_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint16_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",16,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint_exact",32) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u32_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",32,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint32_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint32_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint32_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint32_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint32_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",32,pr.to_string(),praw,true)?;
Ok(obs)
},
(128,"to_uint_exact",64) => {
let (x,xb)=parse128(&c.operands[0])?;
let mut obs=Vec::new();
let (pv,public_flags)=x.to_u64_exact(mode); let mapped=map_public_flags(public_flags)?;
push(&mut obs,"rust/public/mode","integer",64,pv.to_string(),mapped,true)?;
let (pr,praw)=match c.mode.as_str() {
"nearest_even" => bid754::generated::bid128_to_int::bid128_to_uint64_xrnint(xb),
"nearest_away" => bid754::generated::bid128_to_int::bid128_to_uint64_xrninta(xb),
"toward_zero" => bid754::generated::bid128_to_int::bid128_to_uint64_xint(xb),
"toward_positive" => bid754::generated::bid128_to_int::bid128_to_uint64_xceil(xb),
"toward_negative" => bid754::generated::bid128_to_int::bid128_to_uint64_xfloor(xb),
_ => return Err("invalid integer rounding mode".into()),
};
push(&mut obs,"rust/port","integer",64,pr.to_string(),praw,true)?;
Ok(obs)
},
_ => Err("unsupported Tier1 case".into()),
}
}

fn run()->Result<(),String> {
 const MAX_RECORD:u64=4096;
 let stdin=io::stdin();let mut input=stdin.lock();
 let stdout=io::stdout();let mut output=stdout.lock();
 loop {
  let mut record=Vec::new();
  let size=(&mut input).take(MAX_RECORD+1).read_until(b'\n',&mut record).map_err(|e|e.to_string())?;
  if size==0 {break;}
  if size as u64>MAX_RECORD {return Err("record exceeds 4096 bytes".into());}
  let request:Request=serde_json::from_slice(&record).map_err(|e|format!("invalid request: {e}"))?;
  if request.version!=1 {return Err("unsupported protocol version".into());}
  let response=Response{version:1,observations:observe(&request.case)?};
  serde_json::to_writer(&mut output,&response).map_err(|e|e.to_string())?;
  output.write_all(b"\n").map_err(|e|e.to_string())?;
  output.flush().map_err(|e|e.to_string())?;
 }
 Ok(())
}
fn main() {
 if let Err(e)=run() {
  eprintln!("tier1_probe: {e}");
  std::process::exit(1);
 }
}
