// Code generated by testgen; DO NOT EDIT.
import { Buffer } from "node:buffer";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { runInNewContext } from "node:vm";
import { describe, expect, it } from "vitest";
import {
  Kind,
  type Components,
  decode32,
  decodeBytes32,
  encode32,
  encodeBytes32,
  decode64,
  decodeBytes64,
  encode64,
  encodeBytes64,
  decode128,
  decodeBytes128,
  encode128,
  encodeBytes128,
  fromString,
  toString,
} from "./index.js";

interface Vector {
  type: "bid32" | "bid64" | "bid128";
  hex: string;
  hex_hi?: string;
  sign: boolean;
  coefficient: string; // "" for zero/inf/nan-without-payload
  exponent: number;
  kind: string; // "zero" | "normal" | "inf" | "qnan" | "snan"
  payload?: string;
  decimal_string: string;
  canonical: boolean;
  encoded_hex: string;
  encoded_hi?: string;
}

interface RejectVector {
  channel: "from_string" | "encode";
  type?: "bid32" | "bid64" | "bid128";
  input?: string;
  sign?: boolean;
  kind?: string;
  coefficient?: string;
  exponent?: number;
  payload?: string;
  reason: string;
  requires?: string;
}

interface StringVector {
  input: string;
  expected: string;
}

interface VectorFile {
  format_version: number;
  vectors: Vector[];
  reject_vectors: RejectVector[];
  string_vectors: StringVector[];
}

const vectorsPath = resolve(__dirname, "../../bid754-codec-vectors/vectors.json");
const vectorFile: VectorFile = JSON.parse(readFileSync(vectorsPath, "utf-8"));
const expectedFormatVersion = 5;
if (vectorFile.format_version !== expectedFormatVersion) {
  throw new Error(`unsupported BID codec vectors format_version ${vectorFile.format_version}, want ${expectedFormatVersion}`);
}
const vectors: Vector[] = vectorFile.vectors;
const anchorVectors: Vector[] = [
  {
    "type": "bid32",
    "hex": "32800001",
    "sign": false,
    "coefficient": "1",
    "exponent": 0,
    "kind": "normal",
    "decimal_string": "+1E+0",
    "canonical": true,
    "encoded_hex": "32800001"
  },
  {
    "type": "bid32",
    "hex": "b2800000",
    "sign": true,
    "coefficient": "",
    "exponent": 0,
    "kind": "zero",
    "decimal_string": "-0",
    "canonical": true,
    "encoded_hex": "b2800000"
  },
  {
    "type": "bid32",
    "hex": "7c000001",
    "sign": false,
    "coefficient": "",
    "exponent": 0,
    "kind": "qnan",
    "payload": "1",
    "decimal_string": "+NaN1",
    "canonical": true,
    "encoded_hex": "7c000001"
  },
  {
    "type": "bid64",
    "hex": "31c0000000000001",
    "sign": false,
    "coefficient": "1",
    "exponent": 0,
    "kind": "normal",
    "decimal_string": "+1E+0",
    "canonical": true,
    "encoded_hex": "31c0000000000001"
  },
  {
    "type": "bid64",
    "hex": "b1c0000000000000",
    "sign": true,
    "coefficient": "",
    "exponent": 0,
    "kind": "zero",
    "decimal_string": "-0",
    "canonical": true,
    "encoded_hex": "b1c0000000000000"
  },
  {
    "type": "bid64",
    "hex": "7c00000000000001",
    "sign": false,
    "coefficient": "",
    "exponent": 0,
    "kind": "qnan",
    "payload": "1",
    "decimal_string": "+NaN1",
    "canonical": true,
    "encoded_hex": "7c00000000000001"
  },
  {
    "type": "bid128",
    "hex": "0000000000000001",
    "hex_hi": "3040000000000000",
    "sign": false,
    "coefficient": "1",
    "exponent": 0,
    "kind": "normal",
    "decimal_string": "+1E+0",
    "canonical": true,
    "encoded_hex": "0000000000000001",
    "encoded_hi": "3040000000000000"
  },
  {
    "type": "bid128",
    "hex": "0000000000000000",
    "hex_hi": "8000000000000000",
    "sign": true,
    "coefficient": "",
    "exponent": -6176,
    "kind": "zero",
    "decimal_string": "-0E-6176",
    "canonical": true,
    "encoded_hex": "0000000000000000",
    "encoded_hi": "8000000000000000"
  },
  {
    "type": "bid128",
    "hex": "0000000000000001",
    "hex_hi": "7c00000000000000",
    "sign": false,
    "coefficient": "",
    "exponent": 0,
    "kind": "qnan",
    "payload": "1",
    "decimal_string": "+NaN1",
    "canonical": true,
    "encoded_hex": "0000000000000001",
    "encoded_hi": "7c00000000000000"
  },
  {
    "type": "bid128",
    "hex": "0000000000000000",
    "hex_hi": "7c00000000000001",
    "sign": false,
    "coefficient": "",
    "exponent": 0,
    "kind": "qnan",
    "payload": "18446744073709551616",
    "decimal_string": "+NaN18446744073709551616",
    "canonical": true,
    "encoded_hex": "0000000000000000",
    "encoded_hi": "7c00000000000001"
  }
];

function kindFromString(s: string): Kind {
  switch (s) {
    case "zero":
      return Kind.Zero;
    case "normal":
      return Kind.Normal;
    case "inf":
      return Kind.Infinity;
    case "qnan":
      return Kind.QNaN;
    case "snan":
      return Kind.SNaN;
    default:
      throw new Error(`unknown kind: ${s}`);
  }
}

const bid32Vectors = vectors.filter((v) => v.type === "bid32");
const bid64Vectors = vectors.filter((v) => v.type === "bid64");
const bid128Vectors = vectors.filter((v) => v.type === "bid128");
const bid32Canonical = bid32Vectors.filter((v) => v.canonical);
const bid64Canonical = bid64Vectors.filter((v) => v.canonical);
const bid128Canonical = bid128Vectors.filter((v) => v.canonical);

const expectedTotal = 23545;
const expectedBid32 = 5019;
const expectedBid64 = 5804;
const expectedBid128 = 12722;
const expectedBid32Canonical = 4464;
const expectedBid64Canonical = 4583;
const expectedBid128Canonical = 6047;

describe("vectors: coverage profile", () => {
  it("matches generated vector counts", () => {
    expect(vectors).toHaveLength(expectedTotal);
    expect(bid32Vectors).toHaveLength(expectedBid32);
    expect(bid64Vectors).toHaveLength(expectedBid64);
    expect(bid128Vectors).toHaveLength(expectedBid128);
    expect(bid32Canonical).toHaveLength(expectedBid32Canonical);
    expect(bid64Canonical).toHaveLength(expectedBid64Canonical);
    expect(bid128Canonical).toHaveLength(expectedBid128Canonical);
  });
});

describe("vectors: anchor contract", () => {
  it.each(anchorVectors)("matches hardcoded anchor $type $hex", (vec) => {
    let c;
    if (vec.type === "bid32") {
      c = decode32(Number(BigInt("0x" + vec.hex)));
      expect(encode32(c)).toBe(Number(BigInt("0x" + vec.encoded_hex)) >>> 0);
    } else if (vec.type === "bid64") {
      c = decode64(BigInt("0x" + vec.hex));
      expect(encode64(c)).toBe(BigInt("0x" + vec.encoded_hex));
    } else {
      c = decode128(BigInt("0x" + vec.hex), BigInt("0x" + vec.hex_hi!));
      const [lo, hi] = encode128(c);
      expect(lo).toBe(BigInt("0x" + vec.encoded_hex));
      expect(hi).toBe(BigInt("0x" + vec.encoded_hi!));
    }
    expect(vec.canonical).toBe(true);
    expect(c.sign).toBe(vec.sign);
    expect(c.kind).toBe(kindFromString(vec.kind));
    expect(c.exponent).toBe(vec.exponent);
    if (vec.kind !== "qnan" && vec.kind !== "snan") {
      expect(c.coefficient).toBe(vec.coefficient === "" ? 0n : BigInt(vec.coefficient));
    }
    expect(c.payload ?? 0n).toBe(vec.payload === undefined ? 0n : BigInt(vec.payload));
    expect(toString(c)).toBe(vec.decimal_string);
  });
});

describe("vectors: error semantics", () => {
  it("rejects invalid byte lengths", () => {
    expect(() => decodeBytes32(new Uint8Array(3))).toThrow();
    expect(() => decodeBytes32(new Uint8Array(5))).toThrow();
    expect(() => decodeBytes64(new Uint8Array(7))).toThrow();
    expect(() => decodeBytes64(new Uint8Array(9))).toThrow();
    expect(() => decodeBytes128(new Uint8Array(15))).toThrow();
    expect(() => decodeBytes128(new Uint8Array(17))).toThrow();
  });

  // Malformed from_string inputs and out-of-range encode Components are the
  // generated reject_vectors domain (below), not a hardcoded list.
});

const expectedRejectTotal = 145;
const expectedRejectConsumed = 145;
const expectedRejectSkipped = 0;
const rejectCapabilities = new Set<string>(["bignum_coefficient", "negative_coefficient", "negative_payload"]);
const rejectUnsupported = new Set<string>([]);
const rejectVectors: RejectVector[] = vectorFile.reject_vectors;
const consumedRejects = rejectVectors.filter((r) => !r.requires || rejectCapabilities.has(r.requires));
const skippedRejects = rejectVectors.filter((r) => r.requires && !rejectCapabilities.has(r.requires));

function rejectComponents(r: RejectVector): Components {
  return {
    sign: r.sign ?? false,
    kind: kindFromString(r.kind ?? ""),
    coefficient: r.coefficient ? BigInt(r.coefficient) : 0n,
    exponent: r.exponent ?? 0,
    payload: r.payload ? BigInt(r.payload) : 0n,
  };
}

describe("vectors: reject domain", () => {
  it("has the pinned reject count and consumption split", () => {
    expect(rejectVectors).toHaveLength(expectedRejectTotal);
    expect(consumedRejects).toHaveLength(expectedRejectConsumed);
    expect(skippedRejects).toHaveLength(expectedRejectSkipped);
    expect(consumedRejects.length + skippedRejects.length).toBe(rejectVectors.length);
  });

  it("skips only records whose requires tag is a declared-unsupported capability", () => {
    for (const r of skippedRejects) {
      expect(r.requires !== undefined && rejectUnsupported.has(r.requires)).toBe(true);
    }
  });

  it.each(consumedRejects)(
    "rejects $channel $reason",
    (r: RejectVector) => {
      // Record-field access, kind parsing, and Components construction happen
      // outside expect().toThrow() (their failures fail the test as harness
      // failures); only the public API call sits inside the error-expectation
      // callback, so an altered record cannot pass as a rejection.
      if (r.channel === "from_string") {
        const input = r.input ?? "";
        expect(() => fromString(input)).toThrow();
      } else if (r.channel === "encode") {
        const c = rejectComponents(r);
        switch (r.type) {
          case "bid32":
            expect(() => encode32(c)).toThrow();
            break;
          case "bid64":
            expect(() => encode64(c)).toThrow();
            break;
          case "bid128":
            expect(() => encode128(c)).toThrow();
            break;
          default:
            throw new Error(`unknown reject encode type: ${String(r.type)}`);
        }
      } else if (r.channel === "to_string") {
        const c = rejectComponents(r);
        expect(() => toString(c)).toThrow();
      } else {
        throw new Error(`unknown reject channel: ${String(r.channel)}`);
      }
    },
  );
});

const expectedStringTotal = 62;
const stringVectors: StringVector[] = vectorFile.string_vectors;

describe("vectors: string success channel", () => {
  // string_vectors: the generated SUCCESS channel for the string surface. Each
  // record's input must parse and re-render as the exact expected string,
  // pinning fromString→toString agreement across all language consumers in the
  // encoding-unreachable Components region (above all int32-extreme exponents
  // whose adjusted exponent exceeds int32) plus the successful grammar-edge
  // normalizations. The closure leg then re-parses the expected rendering
  // itself: fromString(expected) must succeed and toString must reproduce it
  // exactly (parse(render(x)) is total and expected is a rendering fixed
  // point), so a parser that rejects its own renderer's output fails here.
  // The channel is capability-ungated: every record is consumed.
  it("has the pinned string vector count", () => {
    expect(stringVectors).toHaveLength(expectedStringTotal);
  });

  it.each(stringVectors)("round-trips $input", (sv: StringVector) => {
    const c = fromString(sv.input); // must succeed; a throw fails the harness
    expect(toString(c)).toBe(sv.expected);
    const reparsed = fromString(sv.expected); // closure: rendering must reparse
    expect(toString(reparsed)).toBe(sv.expected); // fixed point
  });
});

const typeDomainRejects: [string, unknown][] = [
  ["non_boolean_sign", { sign: 1, kind: Kind.Normal, coefficient: 1n, exponent: 0, payload: 0n }],
  ["non_integral_exponent", { sign: false, kind: Kind.Normal, coefficient: 1n, exponent: 1.5, payload: 0n }],
  ["nan_exponent", { sign: false, kind: Kind.Normal, coefficient: 1n, exponent: Number.NaN, payload: 0n }],
  ["exponent_above_int32", { sign: false, kind: Kind.Normal, coefficient: 1n, exponent: 2147483648, payload: 0n }],
  ["exponent_below_int32", { sign: false, kind: Kind.Normal, coefficient: 1n, exponent: -2147483649, payload: 0n }],
  ["non_integer_coefficient", { sign: false, kind: Kind.Normal, coefficient: 1, exponent: 0, payload: 0n }],
  ["non_integer_payload", { sign: false, kind: Kind.QNaN, coefficient: 0n, exponent: 0, payload: 1 }],
  ["boolean_coefficient", { sign: false, kind: Kind.Normal, coefficient: true, exponent: 0, payload: 0n }],
  ["boolean_exponent", { sign: false, kind: Kind.Zero, coefficient: 0n, exponent: true, payload: 0n }],
  ["boolean_payload", { sign: false, kind: Kind.QNaN, coefficient: 0n, exponent: 0, payload: true }],
  ["unrecognized_kind", { sign: false, kind: 99, coefficient: 1n, exponent: 0, payload: 0n }],
];

describe("vectors: reject type domain", () => {
  // Reject values the shared JSON schema cannot express, constructible only in
  // dynamically-typed languages (a non-boolean sign, wrong numeric field type,
  // out-of-int32/non-finite exponent, or kind outside the defined set).
  it.each(typeDomainRejects)("rejects %s", (_id, comp) => {
    expect(() => encode32(comp as Components)).toThrow();
    expect(() => toString(comp as Components)).toThrow();
  });
});

const rawDecodeRejects: [string, () => unknown][] = [
  ["decode32_boolean", () => Reflect.apply(decode32, undefined, [true])],
  ["decode32_string", () => Reflect.apply(decode32, undefined, ["1"])],
  ["decode32_fraction", () => Reflect.apply(decode32, undefined, [1.5])],
  ["decode32_nan", () => Reflect.apply(decode32, undefined, [Number.NaN])],
  ["decode32_infinity", () => Reflect.apply(decode32, undefined, [Number.POSITIVE_INFINITY])],
  ["decode32_negative", () => Reflect.apply(decode32, undefined, [-1])],
  ["decode32_overflow", () => Reflect.apply(decode32, undefined, [2 ** 32])],
  ["decode32_bigint", () => Reflect.apply(decode32, undefined, [1n])],
  ["decode64_boolean", () => Reflect.apply(decode64, undefined, [true])],
  ["decode64_string", () => Reflect.apply(decode64, undefined, ["1"])],
  ["decode64_wrong_numeric_type", () => Reflect.apply(decode64, undefined, [1])],
  ["decode64_negative", () => Reflect.apply(decode64, undefined, [-1n])],
  ["decode64_overflow", () => Reflect.apply(decode64, undefined, [1n << 64n])],
  ["decode128_lo_boolean", () => Reflect.apply(decode128, undefined, [true, 0n])],
  ["decode128_lo_string", () => Reflect.apply(decode128, undefined, ["1", 0n])],
  ["decode128_lo_wrong_numeric_type", () => Reflect.apply(decode128, undefined, [1, 0n])],
  ["decode128_lo_negative", () => Reflect.apply(decode128, undefined, [-1n, 0n])],
  ["decode128_lo_overflow", () => Reflect.apply(decode128, undefined, [1n << 64n, 0n])],
  ["decode128_hi_boolean", () => Reflect.apply(decode128, undefined, [0n, true])],
  ["decode128_hi_string", () => Reflect.apply(decode128, undefined, [0n, "1"])],
  ["decode128_hi_wrong_numeric_type", () => Reflect.apply(decode128, undefined, [0n, 1])],
  ["decode128_hi_negative", () => Reflect.apply(decode128, undefined, [0n, -1n])],
  ["decode128_hi_overflow", () => Reflect.apply(decode128, undefined, [0n, 1n << 64n])],
];

describe("vectors: reject raw decode domain", () => {
  // TypeScript declarations do not constrain runtime JavaScript callers. Require an
  // exact uint32 number or uint64 bigint before any narrowing/coercing bit op.
  it.each(rawDecodeRejects)("rejects %s", (_id, invoke) => {
    expect(invoke).toThrow();
  });
});

const byteDecodeRejects: [string, () => unknown][] = [
  ["decodeBytes32_plain_array_nan", () => Reflect.apply(decodeBytes32, undefined, [[Number.NaN, 0, 0, 0]])],
  ["decodeBytes32_plain_array", () => Reflect.apply(decodeBytes32, undefined, [[1, 2, 3, 4]])],
  ["decodeBytes32_duck_length", () => Reflect.apply(decodeBytes32, undefined, [{ length: 4 }])],
  ["decodeBytes32_fractional_element", () => Reflect.apply(decodeBytes32, undefined, [[1.5, 0, 0, 0]])],
  ["decodeBytes32_huge_element", () => Reflect.apply(decodeBytes32, undefined, [[4294967296, 0, 0, 0]])],
  ["decodeBytes32_dataview", () => Reflect.apply(decodeBytes32, undefined, [new DataView(new ArrayBuffer(4))])],
  ["decodeBytes32_uint16array", () => Reflect.apply(decodeBytes32, undefined, [new Uint16Array(4)])],
  ["decodeBytes32_int8array", () => Reflect.apply(decodeBytes32, undefined, [new Int8Array(4)])],
  ["decodeBytes32_uint8clamped", () => Reflect.apply(decodeBytes32, undefined, [new Uint8ClampedArray(4)])],
  ["decodeBytes64_plain_array", () => Reflect.apply(decodeBytes64, undefined, [[0, 0, 0, 0, 0, 0, 0, 0]])],
  ["decodeBytes64_duck_length", () => Reflect.apply(decodeBytes64, undefined, [{ length: 8 }])],
  ["decodeBytes64_dataview", () => Reflect.apply(decodeBytes64, undefined, [new DataView(new ArrayBuffer(8))])],
  ["decodeBytes64_uint16array", () => Reflect.apply(decodeBytes64, undefined, [new Uint16Array(8)])],
  ["decodeBytes64_uint8array_wrong_len", () => Reflect.apply(decodeBytes64, undefined, [new Uint8Array(4)])],
  ["decodeBytes128_plain_array", () => Reflect.apply(decodeBytes128, undefined, [new Array(16).fill(0)])],
  ["decodeBytes128_duck_length", () => Reflect.apply(decodeBytes128, undefined, [{ length: 16 }])],
  ["decodeBytes128_dataview", () => Reflect.apply(decodeBytes128, undefined, [new DataView(new ArrayBuffer(16))])],
  ["decodeBytes128_uint16array", () => Reflect.apply(decodeBytes128, undefined, [new Uint16Array(16)])],
  ["decodeBytes128_uint8array_wrong_len", () => Reflect.apply(decodeBytes128, undefined, [new Uint8Array(8)])],
  ["decodeBytes32_forged_wide_tag", () => { const a = new Uint16Array(4); Object.defineProperty(a, Symbol.toStringTag, { value: "Uint8Array", configurable: true }); return Reflect.apply(decodeBytes32, undefined, [a]); }],
  ["decodeBytes64_forged_wide_tag", () => { const a = new Uint16Array(8); Object.defineProperty(a, Symbol.toStringTag, { value: "Uint8Array", configurable: true }); return Reflect.apply(decodeBytes64, undefined, [a]); }],
  ["decodeBytes128_forged_wide_tag", () => { const a = new Uint16Array(16); Object.defineProperty(a, Symbol.toStringTag, { value: "Uint8Array", configurable: true }); return Reflect.apply(decodeBytes128, undefined, [a]); }],
  ["decodeBytes32_shadowed_length", () => { const a = new Uint8Array(8); Object.defineProperty(a, "length", { value: 4, configurable: true }); return Reflect.apply(decodeBytes32, undefined, [a]); }],
  ["decodeBytes64_shadowed_length", () => { const a = new Uint8Array(16); Object.defineProperty(a, "length", { value: 8, configurable: true }); return Reflect.apply(decodeBytes64, undefined, [a]); }],
  ["decodeBytes128_shadowed_length", () => { const a = new Uint8Array(32); Object.defineProperty(a, "length", { value: 16, configurable: true }); return Reflect.apply(decodeBytes128, undefined, [a]); }],
];

describe("vectors: reject byte decode domain", () => {
  // TypeScript's Uint8Array parameter type does not constrain runtime callers.
  // decodeBytes* must require a genuine, exact-length Uint8Array before any
  // bitwise read or DataView view: a plain array or duck object would be
  // bit-coerced, and a wider typed array (e.g. Uint16Array of N elements = 2N
  // bytes) or a DataView would have its backing bytes truncated by a bare
  // length check. Each case must fail through the error channel.
  it.each(byteDecodeRejects)("rejects %s", (_id, invoke) => {
    expect(invoke).toThrow();
  });
});

describe("vectors: byte decode accepts non-plain Uint8Array views", () => {
  // The guard must not over-reject: a genuine exact-length Uint8Array reached
  // through a Node Buffer (Uint8Array subclass), a nonzero-byteOffset subarray,
  // or a cross-realm constructor (where instanceof fails but the value is a real
  // Uint8Array) must decode to the same Components as a plain Uint8Array of the
  // same bytes. decode is total over all bit patterns, so any bytes are valid.
  const CrossRealmUint8Array = runInNewContext("Uint8Array") as Uint8ArrayConstructor;

  function sampleBytes(len: number): number[] {
    const out: number[] = [];
    for (let i = 0; i < len; i++) out.push((i * 37 + 5) & 0xff);
    return out;
  }

  const widths: [string, number, (buf: Uint8Array) => Components][] = [
    ["bid32", 4, decodeBytes32],
    ["bid64", 8, decodeBytes64],
    ["bid128", 16, decodeBytes128],
  ];

  it.each(widths)("accepts %s Buffer, subarray, and cross-realm views", (_name, len, decode) => {
    const raw = sampleBytes(len);
    const expected = decode(new Uint8Array(raw));

    expect(decode(Buffer.from(raw))).toEqual(expected);

    const backing = new Uint8Array(len + 3);
    backing.set(raw, 2);
    expect(decode(backing.subarray(2, 2 + len))).toEqual(expected);

    expect(decode(CrossRealmUint8Array.from(raw))).toEqual(expected);
  });

  it.each(widths)("reads %s actual slot bytes despite forged own metadata", (_name, len, decode) => {
    // A genuine, exact-length Uint8Array whose own Symbol.toStringTag, length,
    // byteLength, byteOffset, and buffer data properties all lie. The guard must
    // read the real element type, length, and backing bytes through the intrinsic
    // %TypedArray%.prototype getters, never the forged own metadata, so it decodes
    // to the same Components as the un-forged bytes rather than a decoy buffer.
    const raw = sampleBytes(len);
    const expected = decode(new Uint8Array(raw));

    const forged = new Uint8Array(raw);
    const decoy = new Uint8Array(len).fill(0xff);
    Object.defineProperty(forged, Symbol.toStringTag, { value: "Uint16Array", configurable: true });
    Object.defineProperty(forged, "length", { value: len * 2, configurable: true });
    Object.defineProperty(forged, "byteLength", { value: len * 2, configurable: true });
    Object.defineProperty(forged, "byteOffset", { value: 1, configurable: true });
    Object.defineProperty(forged, "buffer", { value: decoy.buffer, configurable: true });

    expect(decode(forged)).toEqual(expected);
  });
});

function leBytes32(hex: string): Uint8Array {
  const value = Number(BigInt("0x" + hex));
  return new Uint8Array([
    value & 0xff,
    (value >>> 8) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 24) & 0xff,
  ]);
}

function leBytes64(hex: string): Uint8Array {
  const value = BigInt("0x" + hex);
  const bytes = new Uint8Array(8);
  const dv = new DataView(bytes.buffer);
  dv.setBigUint64(0, value, true);
  return bytes;
}

function leBytes128(loHex: string, hiHex: string): Uint8Array {
  const bytes = new Uint8Array(16);
  bytes.set(leBytes64(loHex), 0);
  bytes.set(leBytes64(hiHex), 8);
  return bytes;
}

// --- BID32 ---

describe("vectors: bid32 decode", () => {
  it.each(bid32Vectors)("decode $hex", (vec) => {
    const bits = Number(BigInt("0x" + vec.hex));
    const c = decode32(bits);

    expect(c.sign).toBe(vec.sign);
    expect(c.kind).toBe(kindFromString(vec.kind));
    expect(c.exponent).toBe(vec.exponent);

    const expectedCoeff = vec.coefficient === "" ? 0n : BigInt(vec.coefficient);
    expect(c.coefficient).toBe(expectedCoeff);

    if (vec.payload !== undefined) {
      expect(c.payload).toBe(BigInt(vec.payload));
    }
    expect(decodeBytes32(leBytes32(vec.hex))).toEqual(c);
    expect(toString(c)).toBe(vec.decimal_string);
    expect(encode32(fromString(vec.decimal_string))).toBe(Number(BigInt("0x" + vec.encoded_hex)) >>> 0);
  });
});

describe("vectors: bid32 roundtrip", () => {
  it.each(bid32Canonical)("roundtrip $hex", (vec) => {
    const bits = Number(BigInt("0x" + vec.hex));
    const c = decode32(bits);
    const encoded = encode32(c);
    const expectedBits = Number(BigInt("0x" + vec.encoded_hex));
    expect(encoded).toBe(expectedBits >>> 0);
    expect(encodeBytes32(c)).toEqual(leBytes32(vec.encoded_hex));
  });
});

// --- BID64 ---

describe("vectors: bid64 decode", () => {
  it.each(bid64Vectors)("decode $hex", (vec) => {
    const bits = BigInt("0x" + vec.hex);
    const c = decode64(bits);

    expect(c.sign).toBe(vec.sign);
    expect(c.kind).toBe(kindFromString(vec.kind));
    expect(c.exponent).toBe(vec.exponent);

    const expectedCoeff = vec.coefficient === "" ? 0n : BigInt(vec.coefficient);
    expect(c.coefficient).toBe(expectedCoeff);

    if (vec.payload !== undefined) {
      expect(c.payload).toBe(BigInt(vec.payload));
    }
    expect(decodeBytes64(leBytes64(vec.hex))).toEqual(c);
    expect(toString(c)).toBe(vec.decimal_string);
    expect(encode64(fromString(vec.decimal_string))).toBe(BigInt("0x" + vec.encoded_hex));
  });
});

describe("vectors: bid64 roundtrip", () => {
  it.each(bid64Canonical)("roundtrip $hex", (vec) => {
    const bits = BigInt("0x" + vec.hex);
    const c = decode64(bits);
    const encoded = encode64(c);
    const expectedBits = BigInt("0x" + vec.encoded_hex);
    expect(encoded).toBe(expectedBits);
    expect(encodeBytes64(c)).toEqual(leBytes64(vec.encoded_hex));
  });
});

// --- BID128 ---

describe("vectors: bid128 decode", () => {
  it.each(bid128Vectors)("decode $hex/$hex_hi", (vec) => {
    const lo = BigInt("0x" + vec.hex);
    const hi = BigInt("0x" + vec.hex_hi!);
    const c = decode128(lo, hi);

    expect(c.sign).toBe(vec.sign);
    expect(c.kind).toBe(kindFromString(vec.kind));
    expect(c.exponent).toBe(vec.exponent);

    const expectedCoeff = vec.coefficient === "" ? 0n : BigInt(vec.coefficient);
    expect(c.coefficient).toBe(expectedCoeff);

    if (vec.payload !== undefined) {
      expect(c.payload).toBe(BigInt(vec.payload));
    }
    expect(decodeBytes128(leBytes128(vec.hex, vec.hex_hi!))).toEqual(c);
    expect(toString(c)).toBe(vec.decimal_string);
    const [parsedLo, parsedHi] = encode128(fromString(vec.decimal_string));
    expect(parsedLo).toBe(BigInt("0x" + vec.encoded_hex));
    expect(parsedHi).toBe(BigInt("0x" + vec.encoded_hi!));
  });
});

describe("vectors: bid128 roundtrip", () => {
  it.each(bid128Canonical)("roundtrip $hex/$hex_hi", (vec) => {
    const lo = BigInt("0x" + vec.hex);
    const hi = BigInt("0x" + vec.hex_hi!);
    const c = decode128(lo, hi);
    const [encodedLo, encodedHi] = encode128(c);
    const expectedLo = BigInt("0x" + vec.encoded_hex);
    const expectedHi = BigInt("0x" + vec.encoded_hi!);
    expect(encodedLo).toBe(expectedLo);
    expect(encodedHi).toBe(expectedHi);
    expect(encodeBytes128(c)).toEqual(leBytes128(vec.encoded_hex, vec.encoded_hi!));
  });
});
