// Code generated by testgen; DO NOT EDIT.
use bid754::bid_codec::{decode128, decode32, decode64, encode128, encode32, encode64, from_string, to_string, Kind};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Vector {
    #[serde(rename = "type")]
    typ: String,
    hex: String,
    #[serde(default)]
    hex_hi: Option<String>,
    sign: bool,
    #[serde(default)]
    coefficient: String,
    exponent: i32,
    kind: String,
    decimal_string: String,
    canonical: bool,
    #[serde(default)]
    payload: Option<String>,
    #[serde(default)]
    encoded_hex: Option<String>,
    #[serde(default)]
    encoded_hi: Option<String>,
}

#[derive(Debug, Deserialize)]
struct VectorFile {
    format_version: u32,
    vectors: Vec<Vector>,
}

const EXPECTED_FORMAT_VERSION: u32 = 1;
const EXPECTED_TOTAL: usize = 15_046;
const EXPECTED_BID32: usize = 5_019;
const EXPECTED_BID64: usize = 5_017;
const EXPECTED_BID128: usize = 5_010;
const EXPECTED_BID32_CANONICAL: usize = 4_464;
const EXPECTED_BID64_CANONICAL: usize = 4_210;
const EXPECTED_BID128_CANONICAL: usize = 3_641;

fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../bid-codec-vectors/vectors.json")
}

fn load_vectors() -> Vec<Vector> {
    let data = fs::read_to_string(vectors_path()).expect("failed to read BID codec vectors");
    let file: VectorFile = serde_json::from_str(&data).expect("failed to parse BID codec vectors");
    assert_eq!(
        file.format_version, EXPECTED_FORMAT_VERSION,
        "unsupported BID codec vectors format_version"
    );
    file.vectors
}

fn anchor_vectors() -> Vec<Vector> {
    vec![
        Vector { typ: "bid32".to_string(), hex: "32800001".to_string(), hex_hi: None, sign: false, coefficient: "1".to_string(), exponent: 0, kind: "normal".to_string(), decimal_string: "+1E+0".to_string(), canonical: true, payload: None, encoded_hex: Some("32800001".to_string()), encoded_hi: None },
        Vector { typ: "bid32".to_string(), hex: "b2800000".to_string(), hex_hi: None, sign: true, coefficient: "".to_string(), exponent: 0, kind: "zero".to_string(), decimal_string: "-0".to_string(), canonical: true, payload: None, encoded_hex: Some("b2800000".to_string()), encoded_hi: None },
        Vector { typ: "bid32".to_string(), hex: "7c000001".to_string(), hex_hi: None, sign: false, coefficient: "".to_string(), exponent: 0, kind: "qnan".to_string(), decimal_string: "+NaN1".to_string(), canonical: true, payload: Some("1".to_string()), encoded_hex: Some("7c000001".to_string()), encoded_hi: None },
        Vector { typ: "bid64".to_string(), hex: "31c0000000000001".to_string(), hex_hi: None, sign: false, coefficient: "1".to_string(), exponent: 0, kind: "normal".to_string(), decimal_string: "+1E+0".to_string(), canonical: true, payload: None, encoded_hex: Some("31c0000000000001".to_string()), encoded_hi: None },
        Vector { typ: "bid64".to_string(), hex: "b1c0000000000000".to_string(), hex_hi: None, sign: true, coefficient: "".to_string(), exponent: 0, kind: "zero".to_string(), decimal_string: "-0".to_string(), canonical: true, payload: None, encoded_hex: Some("b1c0000000000000".to_string()), encoded_hi: None },
        Vector { typ: "bid64".to_string(), hex: "7c00000000000001".to_string(), hex_hi: None, sign: false, coefficient: "".to_string(), exponent: 0, kind: "qnan".to_string(), decimal_string: "+NaN1".to_string(), canonical: true, payload: Some("1".to_string()), encoded_hex: Some("7c00000000000001".to_string()), encoded_hi: None },
        Vector { typ: "bid128".to_string(), hex: "0000000000000001".to_string(), hex_hi: Some("3040000000000000".to_string()), sign: false, coefficient: "1".to_string(), exponent: 0, kind: "normal".to_string(), decimal_string: "+1E+0".to_string(), canonical: true, payload: None, encoded_hex: Some("0000000000000001".to_string()), encoded_hi: Some("3040000000000000".to_string()) },
        Vector { typ: "bid128".to_string(), hex: "0000000000000000".to_string(), hex_hi: Some("8000000000000000".to_string()), sign: true, coefficient: "".to_string(), exponent: -6176, kind: "zero".to_string(), decimal_string: "-0E-6176".to_string(), canonical: true, payload: None, encoded_hex: Some("0000000000000000".to_string()), encoded_hi: Some("8000000000000000".to_string()) },
        Vector { typ: "bid128".to_string(), hex: "0000000000000001".to_string(), hex_hi: Some("7c00000000000000".to_string()), sign: false, coefficient: "".to_string(), exponent: 0, kind: "qnan".to_string(), decimal_string: "+NaN1".to_string(), canonical: true, payload: Some("1".to_string()), encoded_hex: Some("0000000000000001".to_string()), encoded_hi: Some("7c00000000000000".to_string()) },
    ]
}


fn parse_kind(kind: &str) -> Kind {
    match kind {
        "zero" => Kind::Zero,
        "normal" => Kind::Normal,
        "inf" => Kind::Infinity,
        "qnan" => Kind::QNaN,
        "snan" => Kind::SNaN,
        other => panic!("unknown kind: {other}"),
    }
}

fn hex_u32(s: &str) -> u32 {
    u32::from_str_radix(s, 16).unwrap()
}

fn hex_u64(s: &str) -> u64 {
    u64::from_str_radix(s, 16).unwrap()
}

fn coeff_u128(s: &str) -> u128 {
    if s.is_empty() {
        0
    } else {
        s.parse().unwrap()
    }
}

fn payload_u64(v: &Vector) -> u64 {
    v.payload
        .as_deref()
        .map(|s| s.parse().unwrap_or(0))
        .unwrap_or(0)
}

#[test]
fn test_bid_codec_anchor_vectors() {
    let vectors = anchor_vectors();
    assert_eq!(vectors.len(), 9, "BID codec anchor count changed");
    let mut failures = Vec::new();
    for vector in &vectors {
        let expected_kind = parse_kind(&vector.kind);
        match vector.typ.as_str() {
            "bid32" => {
                let decoded = decode32(hex_u32(&vector.hex));
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || decoded.coefficient != coeff_u128(&vector.coefficient)
                    || payload_u64(vector) != decoded.payload
                    || to_string(&decoded) != vector.decimal_string
                    || encode32(&decoded) != hex_u32(vector.encoded_hex.as_deref().unwrap())
                {
                    failures.push(format!("bid32 anchor {} mismatch: got {:?}", vector.hex, decoded));
                }
            }
            "bid64" => {
                let decoded = decode64(hex_u64(&vector.hex));
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || decoded.coefficient != coeff_u128(&vector.coefficient)
                    || payload_u64(vector) != decoded.payload
                    || to_string(&decoded) != vector.decimal_string
                    || encode64(&decoded) != hex_u64(vector.encoded_hex.as_deref().unwrap())
                {
                    failures.push(format!("bid64 anchor {} mismatch: got {:?}", vector.hex, decoded));
                }
            }
            "bid128" => {
                let decoded = decode128(hex_u64(&vector.hex), hex_u64(vector.hex_hi.as_deref().unwrap()));
                let (encoded_lo, encoded_hi) = encode128(&decoded);
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || (!matches!(decoded.kind, Kind::QNaN | Kind::SNaN)
                        && decoded.coefficient != coeff_u128(&vector.coefficient))
                    || payload_u64(vector) != decoded.payload
                    || to_string(&decoded) != vector.decimal_string
                    || encoded_lo != hex_u64(vector.encoded_hex.as_deref().unwrap())
                    || encoded_hi != hex_u64(vector.encoded_hi.as_deref().unwrap())
                {
                    failures.push(format!(
                        "bid128 anchor {}_{} mismatch: got {:?}",
                        vector.hex_hi.as_deref().unwrap_or(""),
                        vector.hex,
                        decoded
                    ));
                }
            }
            other => failures.push(format!("unknown anchor vector type: {other}")),
        }
    }
    assert!(failures.is_empty(), "BID codec anchor failures:\n{}", failures.join("\n"));
}

#[test]
fn test_bid_codec_vectors_encode_decode() {
    let vectors = load_vectors();
    let mut bid32 = 0usize;
    let mut bid64 = 0usize;
    let mut bid128 = 0usize;
    let mut bid32_canonical = 0usize;
    let mut bid64_canonical = 0usize;
    let mut bid128_canonical = 0usize;
    let mut decode_passed = 0usize;
    let mut encode_passed = 0usize;
    let mut skipped = 0usize;
    let mut failures = Vec::new();

    for vector in &vectors {
        let expected_kind = parse_kind(&vector.kind);
        match vector.typ.as_str() {
            "bid32" => {
                bid32 += 1;
                if vector.canonical {
                    bid32_canonical += 1;
                }
                let bits = hex_u32(&vector.hex);
                let decoded = decode32(bits);
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || decoded.coefficient != coeff_u128(&vector.coefficient)
                {
                    failures.push(format!(
                        "bid32 decode {}: got kind={:?} sign={} coeff={} exp={}, want kind={:?} sign={} coeff={} exp={}",
                        vector.hex,
                        decoded.kind,
                        decoded.sign,
                        decoded.coefficient,
                        decoded.exponent,
                        expected_kind,
                        vector.sign,
                        coeff_u128(&vector.coefficient),
                        vector.exponent,
                    ));
                    continue;
                }
                if matches!(decoded.kind, Kind::QNaN | Kind::SNaN) && decoded.payload != payload_u64(vector) {
                    failures.push(format!(
                        "bid32 decode payload {}: got {}, want {}",
                        vector.hex,
                        decoded.payload,
                        payload_u64(vector)
                    ));
                    continue;
                }
                decode_passed += 1;
                if to_string(&decoded) != vector.decimal_string {
                    failures.push(format!(
                        "bid32 to_string {}: got {}, want {}",
                        vector.hex,
                        to_string(&decoded),
                        vector.decimal_string
                    ));
                    continue;
                }
                let parsed = from_string(&vector.decimal_string).unwrap_or_else(|err| {
                    panic!("bid32 from_string {} failed: {}", vector.decimal_string, err)
                });
                let parsed_encoded = encode32(&parsed);
                let expected_from_string = hex_u32(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                if parsed_encoded != expected_from_string {
                    failures.push(format!(
                        "bid32 from_string {}: got {:08x}, want {:08x}",
                        vector.decimal_string,
                        parsed_encoded,
                        expected_from_string
                    ));
                    continue;
                }

                if vector.canonical {
                    let encoded = encode32(&decoded);
                    let expected = hex_u32(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                    if encoded != expected {
                        failures.push(format!(
                            "bid32 encode {}: got {:08x}, want {:08x}",
                            vector.hex, encoded, expected
                        ));
                        continue;
                    }
                    encode_passed += 1;
                } else {
                    skipped += 1;
                }
            }
            "bid64" => {
                bid64 += 1;
                if vector.canonical {
                    bid64_canonical += 1;
                }
                let bits = hex_u64(&vector.hex);
                let decoded = decode64(bits);
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || decoded.coefficient != coeff_u128(&vector.coefficient)
                {
                    failures.push(format!(
                        "bid64 decode {}: got kind={:?} sign={} coeff={} exp={}, want kind={:?} sign={} coeff={} exp={}",
                        vector.hex,
                        decoded.kind,
                        decoded.sign,
                        decoded.coefficient,
                        decoded.exponent,
                        expected_kind,
                        vector.sign,
                        coeff_u128(&vector.coefficient),
                        vector.exponent,
                    ));
                    continue;
                }
                if matches!(decoded.kind, Kind::QNaN | Kind::SNaN) && decoded.payload != payload_u64(vector) {
                    failures.push(format!(
                        "bid64 decode payload {}: got {}, want {}",
                        vector.hex,
                        decoded.payload,
                        payload_u64(vector)
                    ));
                    continue;
                }
                decode_passed += 1;
                if to_string(&decoded) != vector.decimal_string {
                    failures.push(format!(
                        "bid64 to_string {}: got {}, want {}",
                        vector.hex,
                        to_string(&decoded),
                        vector.decimal_string
                    ));
                    continue;
                }
                let parsed = from_string(&vector.decimal_string).unwrap_or_else(|err| {
                    panic!("bid64 from_string {} failed: {}", vector.decimal_string, err)
                });
                let parsed_encoded = encode64(&parsed);
                let expected_from_string = hex_u64(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                if parsed_encoded != expected_from_string {
                    failures.push(format!(
                        "bid64 from_string {}: got {:016x}, want {:016x}",
                        vector.decimal_string,
                        parsed_encoded,
                        expected_from_string
                    ));
                    continue;
                }

                if vector.canonical {
                    let encoded = encode64(&decoded);
                    let expected = hex_u64(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                    if encoded != expected {
                        failures.push(format!(
                            "bid64 encode {}: got {:016x}, want {:016x}",
                            vector.hex, encoded, expected
                        ));
                        continue;
                    }
                    encode_passed += 1;
                } else {
                    skipped += 1;
                }
            }
            "bid128" => {
                bid128 += 1;
                if vector.canonical {
                    bid128_canonical += 1;
                }
                let lo = hex_u64(&vector.hex);
                let hi = hex_u64(vector.hex_hi.as_deref().expect("missing bid128 hex_hi"));
                let decoded = decode128(lo, hi);
                if decoded.kind != expected_kind
                    || decoded.sign != vector.sign
                    || decoded.exponent != vector.exponent
                    || (!matches!(decoded.kind, Kind::QNaN | Kind::SNaN)
                        && decoded.coefficient != coeff_u128(&vector.coefficient))
                {
                    failures.push(format!(
                        "bid128 decode {}_{}: got kind={:?} sign={} coeff={} exp={}, want kind={:?} sign={} coeff={} exp={}",
                        vector.hex_hi.as_deref().unwrap_or(""),
                        vector.hex,
                        decoded.kind,
                        decoded.sign,
                        decoded.coefficient,
                        decoded.exponent,
                        expected_kind,
                        vector.sign,
                        coeff_u128(&vector.coefficient),
                        vector.exponent,
                    ));
                    continue;
                }
                if matches!(decoded.kind, Kind::QNaN | Kind::SNaN) && decoded.payload != payload_u64(vector) {
                    failures.push(format!(
                        "bid128 decode payload {}_{}: got {}, want {}",
                        vector.hex_hi.as_deref().unwrap_or(""),
                        vector.hex,
                        decoded.payload,
                        payload_u64(vector)
                    ));
                    continue;
                }
                decode_passed += 1;
                if to_string(&decoded) != vector.decimal_string {
                    failures.push(format!(
                        "bid128 to_string {}_{}: got {}, want {}",
                        vector.hex_hi.as_deref().unwrap_or(""),
                        vector.hex,
                        to_string(&decoded),
                        vector.decimal_string
                    ));
                    continue;
                }
                let parsed = from_string(&vector.decimal_string).unwrap_or_else(|err| {
                    panic!("bid128 from_string {} failed: {}", vector.decimal_string, err)
                });
                let (parsed_lo, parsed_hi) = encode128(&parsed);
                let expected_lo = hex_u64(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                let expected_hi = hex_u64(vector.encoded_hi.as_deref().unwrap_or_else(|| vector.hex_hi.as_deref().unwrap()));
                if parsed_lo != expected_lo || parsed_hi != expected_hi {
                    failures.push(format!(
                        "bid128 from_string {}: got {:016x}_{:016x}, want {:016x}_{:016x}",
                        vector.decimal_string,
                        parsed_hi,
                        parsed_lo,
                        expected_hi,
                        expected_lo,
                    ));
                    continue;
                }

                if vector.canonical {
                    let (enc_lo, enc_hi) = encode128(&decoded);
                    let exp_lo = hex_u64(vector.encoded_hex.as_deref().unwrap_or(&vector.hex));
                    let exp_hi = hex_u64(vector.encoded_hi.as_deref().unwrap_or_else(|| vector.hex_hi.as_deref().unwrap()));
                    if enc_lo != exp_lo || enc_hi != exp_hi {
                        failures.push(format!(
                            "bid128 encode {}_{}: got {:016x}_{:016x}, want {:016x}_{:016x}",
                            vector.hex_hi.as_deref().unwrap_or(""),
                            vector.hex,
                            enc_hi,
                            enc_lo,
                            exp_hi,
                            exp_lo,
                        ));
                        continue;
                    }
                    encode_passed += 1;
                } else {
                    skipped += 1;
                }
            }
            other => failures.push(format!("unknown vector type: {other}")),
        }
    }

    assert_eq!(vectors.len(), EXPECTED_TOTAL, "BID codec vector total changed");
    assert_eq!(bid32, EXPECTED_BID32, "BID32 vector count changed");
    assert_eq!(bid64, EXPECTED_BID64, "BID64 vector count changed");
    assert_eq!(bid128, EXPECTED_BID128, "BID128 vector count changed");
    assert_eq!(bid32_canonical, EXPECTED_BID32_CANONICAL, "BID32 canonical vector count changed");
    assert_eq!(bid64_canonical, EXPECTED_BID64_CANONICAL, "BID64 canonical vector count changed");
    assert_eq!(bid128_canonical, EXPECTED_BID128_CANONICAL, "BID128 canonical vector count changed");
    assert_eq!(skipped, EXPECTED_TOTAL - EXPECTED_BID32_CANONICAL - EXPECTED_BID64_CANONICAL - EXPECTED_BID128_CANONICAL, "non-canonical skip count changed");
    assert_eq!(decode_passed, EXPECTED_TOTAL, "decode coverage changed");
    assert_eq!(encode_passed, EXPECTED_BID32_CANONICAL + EXPECTED_BID64_CANONICAL + EXPECTED_BID128_CANONICAL, "encode coverage changed");

    if !failures.is_empty() {
        let preview = failures.into_iter().take(50).collect::<Vec<_>>().join("\n");
        panic!(
            "BID codec vectors failed: decode_passed={} encode_passed={} skipped={} failures_preview:\n{}",
            decode_passed,
            encode_passed,
            skipped,
            preview,
        );
    }

    eprintln!(
        "BID codec vectors: decode_passed={} encode_passed={} skipped={}",
        decode_passed,
        encode_passed,
        skipped,
    );
}
