// Code generated by testgen; DO NOT EDIT.

use bid754::bid64_from_string_raw;
use bid754::gen_types::BID_UINT128;
use bid754::generated::bid128_string::{bid128_from_string, bid128_to_string};
use bid754::generated::bid32_string::{bid32_from_string_raw, bid32_to_string_raw};
use bid754::generated::string64::bid64_to_string;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

/// Readtest shard files of every from_string/to_string suite, relative to
/// generated/testspec, in generation order.
const GENERATED_BID_STRING_SHARD_FILES: &[&str] = &[
    "readtest/bid64_from_string.json",
    "readtest/bid128_from_string.json",
    "readtest/bid64_to_string.json",
    "readtest/bid128_to_string.json",
    "readtest/bid32_to_string.json",
    "readtest/bid32_from_string.json",
    "readtest/bid32_from_string_ieee754_overflow_cdiverge.json",
    "readtest/bid32_from_string_ieee754_overflow_cmatch.json",
    "readtest/bid64_from_string_ieee754_overflow_cdiverge.json",
    "readtest/bid64_from_string_ieee754_overflow_cmatch.json",
    "readtest/bid128_from_string_ieee754_overflow_cmatch.json",
];

#[derive(Deserialize)]
struct ReadtestShard {
    format: String,
    function: String,
    kind: String,
    cases: Vec<ReadtestShardCase>,
}

#[derive(Deserialize)]
struct ReadtestShardCase {
    id: String,
    line: usize,
    operands: Vec<String>,
    expected: String,
    status: String,
    rounding: i64,
}

struct ReadCase {
    id: String,
    line: usize,
    format: String,
    function: String,
    kind: String,
    operands: Vec<String>,
    expected: String,
    status: String,
    rounding: i64,
}

#[derive(Debug, Default, PartialEq, Eq)]
struct GeneratedBIDStringCounts {
    total: usize,
    from_string: usize,
    to_string: usize,
    decimal32: usize,
    decimal64: usize,
    decimal128: usize,
    decimal32_from_string: usize,
    decimal64_from_string: usize,
    decimal128_from_string: usize,
    decimal32_to_string: usize,
    decimal64_to_string: usize,
    decimal128_to_string: usize,
}

const EXPECTED_GENERATED_BID_STRING_COUNTS: GeneratedBIDStringCounts = GeneratedBIDStringCounts {
    total: 305,
    from_string: 242,
    to_string: 63,
    decimal32: 111,
    decimal64: 89,
    decimal128: 105,
    decimal32_from_string: 91,
    decimal64_from_string: 77,
    decimal128_from_string: 74,
    decimal32_to_string: 20,
    decimal64_to_string: 12,
    decimal128_to_string: 31,
};

#[test]
fn test_generated_bid_string_vectors() {
    let read_cases = load_string_read_cases();
    let mut counts = GeneratedBIDStringCounts::default();
    for tc in read_cases.iter().filter(|tc| tc.kind == "from_string" || tc.kind == "to_string") {
        count_bid_string_case(&mut counts, tc);
        match tc.kind.as_str() {
            "from_string" => {
                let (got_bits, flags) = bid_string_from_string(tc);
                if tc.expected.trim_start().starts_with('[') {
                    assert_eq!(
                        normalize_bits(&got_bits),
                        normalize_bits(&tc.expected),
                        "{} line {} bits",
                        tc.function,
                        tc.line
                    );
                } else {
                    let rendered = render_bits(&tc.format, &got_bits);
                    assert_eq!(
                        normalize_decimal(&rendered),
                        normalize_decimal(&tc.expected),
                        "{} line {} rendered",
                        tc.function,
                        tc.line
                    );
                }
                assert_eq!(
                    normalize_status(&flags),
                    normalize_status(&tc.status),
                    "{} line {} status",
                    tc.function,
                    tc.line
                );
            }
            "to_string" => {
                let (got, flags) = bid_string_to_string(tc);
                assert_eq!(
                    normalize_decimal(&got),
                    normalize_decimal(&tc.expected),
                    "{} line {} result",
                    tc.function,
                    tc.line
                );
                assert_eq!(
                    normalize_status(&flags),
                    normalize_status(&tc.status),
                    "{} line {} status",
                    tc.function,
                    tc.line
                );
            }
            _ => unreachable!(),
        }
    }
    assert_eq!(
        counts, EXPECTED_GENERATED_BID_STRING_COUNTS,
        "generated BID string read case counts changed"
    );
}

fn count_bid_string_case(counts: &mut GeneratedBIDStringCounts, tc: &ReadCase) {
    counts.total += 1;
    match tc.kind.as_str() {
        "from_string" => counts.from_string += 1,
        "to_string" => counts.to_string += 1,
        _ => {}
    }
    match tc.format.as_str() {
        "decimal32" => {
            counts.decimal32 += 1;
            match tc.kind.as_str() {
                "from_string" => counts.decimal32_from_string += 1,
                "to_string" => counts.decimal32_to_string += 1,
                _ => {}
            }
        }
        "decimal64" => {
            counts.decimal64 += 1;
            match tc.kind.as_str() {
                "from_string" => counts.decimal64_from_string += 1,
                "to_string" => counts.decimal64_to_string += 1,
                _ => {}
            }
        }
        "decimal128" => {
            counts.decimal128 += 1;
            match tc.kind.as_str() {
                "from_string" => counts.decimal128_from_string += 1,
                "to_string" => counts.decimal128_to_string += 1,
                _ => {}
            }
        }
        _ => {}
    }
}

fn testspec_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../generated/testspec")
}

fn load_string_read_cases() -> Vec<ReadCase> {
    let base_dir = testspec_dir();
    let mut read_cases = Vec::new();
    for shard_file in GENERATED_BID_STRING_SHARD_FILES {
        let path = base_dir.join(shard_file);
        let data = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read string shard {}: {err}", path.display()));
        let shard: ReadtestShard = serde_json::from_str(&data)
            .unwrap_or_else(|err| panic!("parse string shard {}: {err}", path.display()));
        for tc in shard.cases {
            read_cases.push(ReadCase {
                id: tc.id,
                line: tc.line,
                format: shard.format.clone(),
                function: shard.function.clone(),
                kind: shard.kind.clone(),
                operands: tc.operands,
                expected: tc.expected,
                status: tc.status,
                rounding: tc.rounding,
            });
        }
    }
    read_cases
}

fn bid_string_from_string(tc: &ReadCase) -> (String, String) {
    assert_eq!(tc.operands.len(), 1, "{} expects one operand", tc.id);
    match tc.format.as_str() {
        "decimal32" => {
            let (got, flags) = bid32_from_string_raw(tc.operands[0].clone(), tc.rounding);
            (format!("[{got:08x}]"), format!("{flags:02X}"))
        }
        "decimal64" => {
            let (got, flags) = bid64_from_string_raw(tc.operands[0].clone(), tc.rounding as i32);
            (format!("[{got:016x}]"), format!("{flags:02X}"))
        }
        "decimal128" => {
            let (got, flags) = bid128_from_string(tc.operands[0].clone(), tc.rounding);
            (format_bits128(got), format!("{flags:02X}"))
        }
        other => panic!("unsupported format {other}"),
    }
}

fn bid_string_to_string(tc: &ReadCase) -> (String, String) {
    assert_eq!(tc.operands.len(), 1, "{} expects one operand", tc.id);
    match tc.format.as_str() {
        "decimal32" => (bid32_to_string_raw(parse_u32_bits(&tc.operands[0])), String::from("00")),
        "decimal64" => (bid64_to_string(parse_u64_bits(&tc.operands[0])), String::from("00")),
        "decimal128" => (bid128_to_string(parse_bits128(&tc.operands[0])), String::from("00")),
        other => panic!("unsupported format {other}"),
    }
}

fn render_bits(format: &str, bits: &str) -> String {
    match format {
        "decimal32" => bid32_to_string_raw(parse_u32_bits(bits)),
        "decimal64" => bid64_to_string(parse_u64_bits(bits)),
        "decimal128" => bid128_to_string(parse_bits128(bits)),
        other => panic!("unsupported format {other}"),
    }
}

fn parse_u32_bits(input: &str) -> u32 {
    u32::from_str_radix(&normalize_hex(input), 16).unwrap()
}

fn parse_u64_bits(input: &str) -> u64 {
    u64::from_str_radix(&normalize_hex(input), 16).unwrap()
}

fn parse_bits128(input: &str) -> BID_UINT128 {
    let compact = normalize_hex(input);
    assert!(compact.len() > 16 && compact.len() <= 32, "invalid BID128 literal {input}");
    let padded = format!("{compact:0>32}");
    let hi = u64::from_str_radix(&padded[..16], 16).unwrap();
    let lo = u64::from_str_radix(&padded[16..], 16).unwrap();
    BID_UINT128 { w: [lo, hi] }
}

fn format_bits128(raw: BID_UINT128) -> String {
    format!("[{:016x}{:016x}]", raw.w[1], raw.w[0])
}

fn normalize_hex(input: &str) -> String {
    input.trim().trim_start_matches('[').trim_end_matches(']').replace(',', "").to_ascii_lowercase()
}

fn normalize_bits(input: &str) -> String {
    let trimmed = normalize_hex(input);
    let stripped = trimmed.trim_start_matches('0');
    if stripped.is_empty() {
        String::from("[0]")
    } else {
        format!("[{stripped}]")
    }
}

fn normalize_status(input: &str) -> String {
    let mut s = input.trim().trim_start_matches("0x").trim_start_matches("0X").to_ascii_uppercase();
    if s.is_empty() {
        return String::from("00");
    }
    if s.len() % 2 != 0 {
        s = format!("0{s}");
    }
    s
}

fn normalize_decimal(input: &str) -> String {
    let mut s = input.trim().trim_matches(|c| c == '\'' || c == '"').to_string();
    if s.is_empty() {
        return s;
    }
    let mut sign = "+";
    if let Some(rest) = s.strip_prefix('+') {
        s = rest.to_string();
    } else if let Some(rest) = s.strip_prefix('-') {
        sign = "-";
        s = rest.to_string();
    }
    let lower = s.to_ascii_lowercase();
    if lower == "inf" || lower == "infinity" {
        return format!("{sign}Inf");
    }
    if lower.starts_with("snan") {
        return format!("{sign}SNaN{}", normalize_payload(&s[4..]));
    }
    if lower.starts_with("nan") {
        return format!("{sign}NaN{}", normalize_payload(&s[3..]));
    }
    let parts: Vec<&str> = s.split(['e', 'E']).collect();
    if parts.len() == 1 {
        return format!("{sign}{}E+0", parts[0]);
    }
    let exp = parts[1].trim_start_matches('+').parse::<i32>();
    match exp {
        Ok(exp) => format!("{sign}{}E{exp:+}", parts[0]),
        Err(_) => format!("{sign}{}", s.to_ascii_uppercase()),
    }
}

fn normalize_payload(input: &str) -> String {
    let stripped = input.trim_start_matches('0');
    if stripped.is_empty() {
        String::new()
    } else {
        stripped.to_string()
    }
}
