package testgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The Rust public-API parity gate is the Rust sibling of the Go public-API
// parity gate (public_parity_codegen.go / public_parity_runner_*.go). Where
// the Go leg derives its own census (public_api_routing_inventory.json) from the
// Go module-root source tree, this leg's census input is already generated by
// go2rs apiemit: devtools/generated/testspec/rust_api_surface_inventory.json
// records, per Go symbol, whether apiemit emitted a Rust wrapper for it and,
// if so, which rust_owner/rust_surface/shape/bidgo_function. This generator
// reads every "emitted" row and emits one independent parity check per row.
// Regeneration after go2rs apiemit expands the emitted set automatically (see
// the rust_owner check below): this
// generator is driven by the inventory's emitted population, not a hardcoded
// symbol list.
//
// Independent-mapping requirement (mirrors the Go leg's mapPortFlagsForParity
// / publicParityModes): the generated runner's flag-bit and rounding-mode
// mappings are hardcoded numeric literals, NOT the wrapper's own
// ExceptionFlags::from_bidgo / to_bidgo_rounding converters
// (bid754-rs/src/generated/api/types.rs), so a shared-converter bug stays
// visible in this gate. The crate::generated::* port ADDRESS resolution
// (which Rust module/function a bidgo name maps to) is reused from
// apiemit.PortPathFor: that is routing metadata (the same table apiemit
// itself used to write the wrapper call site), not a flag/rounding semantic
// mapping, so sharing it does not relax the independent-mapping guarantee --
// it only avoids a second hand-copied module/function table that could drift
// from what the wrapper actually calls.
const (
	rustAPISurfaceInventoryPath = "generated/testspec/rust_api_surface_inventory.json"
	rustPublicParityRunnerPath  = "../bid754-rs/tests/public_parity_generated.rs"
)

// rustParityInventoryRow mirrors one mapped wrapper row of
// rust_api_surface_inventory.json.
type rustParityInventoryRow struct {
	GoSymbol      string `json:"go_symbol"`
	Status        string `json:"status"`
	RustOwner     string `json:"rust_owner,omitempty"`
	RustSurface   string `json:"rust_surface,omitempty"`
	Shape         string `json:"shape,omitempty"`
	BidgoFunction string `json:"bidgo_function"`
}

// rustConstInventoryRow mirrors one row of rust_api_surface_inventory.json's
// separate "constants" section:
// the 12 ZERO/ONE/PI/E associated consts go2rs apiemit emits from
// devtools/tools/registry/rust_api_manifest.json's "constants" rows. This is
// a distinct exhaustive set from rustParityInventoryRow's mapped wrapper rows above (see
// apiemit.resolveConstantsClosure), read here to drive the const-parity gate
// (emitRustConstParityTests in rust_public_parity_emit.go) rather than folded
// into the wrapper-shape dispatch.
type rustConstInventoryRow struct {
	GoSymbol  string `json:"go_symbol"`
	Status    string `json:"status"`
	RustOwner string `json:"rust_owner,omitempty"`
	RustConst string `json:"rust_const,omitempty"`
	Literal   string `json:"literal,omitempty"`
}

type rustParityInventory struct {
	Version     string                   `json:"version"`
	Kind        string                   `json:"kind"`
	Source      string                   `json:"source"`
	MappedTotal int                      `json:"mapped_total"`
	Emitted     int                      `json:"emitted"`
	Deferred    int                      `json:"deferred"`
	Rows        []rustParityInventoryRow `json:"rows"`

	ConstantsTotal   int                     `json:"constants_total"`
	ConstantsEmitted int                     `json:"constants_emitted"`
	Constants        []rustConstInventoryRow `json:"constants"`
}

func loadRustAPISurfaceInventory(path string) (rustParityInventory, error) {
	var inventory rustParityInventory
	data, err := os.ReadFile(path)
	if err != nil {
		return inventory, fmt.Errorf("read rust API surface inventory %q: %w", path, err)
	}
	if err := json.Unmarshal(data, &inventory); err != nil {
		return inventory, fmt.Errorf("parse rust API surface inventory %q: %w", path, err)
	}
	return inventory, nil
}

// WriteRustPublicParityOutputs regenerates the Rust public-API parity gate
// runner from the pinned rust_api_surface_inventory.json emitted-symbol set.
func WriteRustPublicParityOutputs(repoRoot string) error {
	files, err := GenerateRustPublicParityOutputs(repoRoot)
	if err != nil {
		return err
	}
	for path, data := range files {
		fullPath := filepath.Join(repoRoot, path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("mkdir %q: %w", filepath.Dir(fullPath), err)
		}
		if err := os.WriteFile(fullPath, data, 0o644); err != nil {
			return fmt.Errorf("write generated rust public parity output %q: %w", fullPath, err)
		}
	}
	return nil
}

// GenerateRustPublicParityOutputs returns the generated Rust public-API
// parity runner keyed by repo-relative path. It reuses the Go parity leg's
// bit-literal corpus (buildPublicParityCorpus) and Intel exception-mask
// loader (loadBidExceptionMasks) verbatim, so both language legs exercise the
// identical operand bit patterns.
func GenerateRustPublicParityOutputs(repoRoot string) (map[string][]byte, error) {
	inventory, err := loadRustAPISurfaceInventory(filepath.Join(repoRoot, rustAPISurfaceInventoryPath))
	if err != nil {
		return nil, err
	}
	masks, err := loadBidExceptionMasks(filepath.Join(repoRoot, publicParityHeaderPath))
	if err != nil {
		return nil, err
	}
	corpus, err := buildPublicParityCorpus()
	if err != nil {
		return nil, err
	}

	var emittedRows []rustParityInventoryRow
	for _, row := range inventory.Rows {
		if row.Status != "emitted" {
			continue
		}
		// Strict width check: every emitted row is width-64 (Decimal64,
		// Context), width-32 (Decimal32), or width-128 (Decimal128 and the
		// width-128 Context::add128). Decimal128's 128-bit
		// port convention (pfpsf pointer flags on a per-function subset,
		// tuple return on the rest -- resolved via apiemit.PortPfpsf) and
		// byte-accessor names (to_le_bytes/from_le_bytes rather than
		// to_bits/from_bits) are handled by the width helpers in
		// rust_public_parity_emit.go (parityWidth.pubFrom/portArg/
		// pubBitsExpr/portBitsExpr and portCallStmt). A row for any owner
		// beyond these four is still a generation-time hard failure that
		// names the extension point instead of guessing.
		if row.RustOwner != "Decimal64" && row.RustOwner != "Decimal32" && row.RustOwner != "Decimal128" && row.RustOwner != "Context" {
			return nil, fmt.Errorf("rust public parity: emitted row %q has rust_owner %q; the generator supports Decimal64, Decimal32, Decimal128, and Context owners -- extend the per-shape emitters in rust_public_parity_emit.go for a new owner rather than guessing its calling convention", row.GoSymbol, row.RustOwner)
		}
		emittedRows = append(emittedRows, row)
	}
	if len(emittedRows) == 0 {
		return nil, fmt.Errorf("rust public parity: no emitted rows found in %s", rustAPISurfaceInventoryPath)
	}
	sort.Slice(emittedRows, func(i, j int) bool { return emittedRows[i].GoSymbol < emittedRows[j].GoSymbol })

	var emittedConstRows []rustConstInventoryRow
	for _, row := range inventory.Constants {
		if row.Status != "emitted" {
			continue
		}
		emittedConstRows = append(emittedConstRows, row)
	}
	if len(emittedConstRows) == 0 {
		return nil, fmt.Errorf("rust public parity: no emitted constants rows found in %s", rustAPISurfaceInventoryPath)
	}
	sort.Slice(emittedConstRows, func(i, j int) bool { return emittedConstRows[i].GoSymbol < emittedConstRows[j].GoSymbol })

	out, err := emitRustParityFile(emittedRows, emittedConstRows, corpus, masks)
	if err != nil {
		return nil, err
	}
	formatted, err := formatGeneratedRustOutput(out)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{rustPublicParityRunnerPath: formatted}, nil
}

// formatGeneratedRustOutput is a light hygiene pass (not rustfmt -- no
// generator in this repo shells out to rustfmt; bid754-go/generated_public_*
// and bid754-rs/tests/bid_string_vectors.rs are likewise emitted as
// already-laid-out text). It only collapses accidental blank-line runs the
// per-shape emitters may introduce when a section contributes zero lines.
func formatGeneratedRustOutput(src []byte) ([]byte, error) {
	lines := strings.Split(string(src), "\n")
	var out []string
	blank := 0
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			blank++
			if blank > 1 {
				continue
			}
		} else {
			blank = 0
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n")), nil
}

// normalizeRustFnName turns a go_symbol census key ("Decimal64BID.ConvertToInt16",
// "NewDecimal64FromInt32") into a valid, readable Rust snake_case identifier
// ("parity_decimal64_bid_convert_to_int16", "parity_new_decimal64_from_int32").
// Uniqueness across the emitted-row population is enforced by the caller
// (duplicate function names would be a Rust compile error, which is itself a
// strict backstop, but the assembly step checks explicitly for a clear
// generation-time message instead of an opaque rustc error).
func normalizeRustFnName(goSymbol string) string {
	var b strings.Builder
	var prevLower, prevDigit bool
	for _, r := range goSymbol {
		switch {
		case r >= 'A' && r <= 'Z':
			if b.Len() > 0 && (prevLower || prevDigit) {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
			prevLower, prevDigit = false, false
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			prevLower, prevDigit = true, false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			prevLower, prevDigit = false, true
		default:
			if b.Len() > 0 && !strings.HasSuffix(b.String(), "_") {
				b.WriteByte('_')
			}
			prevLower, prevDigit = false, false
		}
	}
	name := strings.Trim(b.String(), "_")
	return "parity_" + name
}
