// tools/go2rs_tables/main.go - Build the Rust compat layer over canonical C-generated tables.
//
// The table architecture is C -> Go/Rust direct generation, not Go -> Rust conversion.
// This tool creates bid754-rs/src/tables.rs as a compatibility layer:
// canonical upper-case tables are included from generated/rust/intel_dfp_tables.rs,
// then lower-case Go-style aliases/wrappers are exposed for the go2rs output.
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	projectRoot := findProjectRoot()
	outPath := filepath.Join(projectRoot, "..", "bid754-rs", "src", "tables.rs")
	content := `// Code generated by tools/go2rs_tables. DO NOT EDIT.
// Canonical source tables come from Intel BID C via generated/rust/intel_dfp_tables.rs.
// This file provides Go-style lower-case compat names for go2rs-generated Rust code.
#![allow(dead_code, non_upper_case_globals)]

use crate::gen_types::{BID_UINT128, BID_UINT192, BID_UINT256, DEC_DIGITS};

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../devtools/generated/rust/intel_dfp_tables.rs"));

const fn wrap_u128<const N: usize>(src: [UInt128Words; N]) -> [BID_UINT128; N] {
    let mut out = [BID_UINT128 { w: [0u64, 0u64] }; N];
    let mut i = 0;
    while i < N {
        out[i] = BID_UINT128 { w: src[i] };
        i += 1;
    }
    out
}

const fn wrap_u192<const N: usize>(src: [UInt192Words; N]) -> [BID_UINT192; N] {
    let mut out = [BID_UINT192 { w: [0u64, 0u64, 0u64] }; N];
    let mut i = 0;
    while i < N {
        out[i] = BID_UINT192 { w: src[i] };
        i += 1;
    }
    out
}

const fn wrap_u256<const N: usize>(src: [UInt256Words; N]) -> [BID_UINT256; N] {
    let mut out = [BID_UINT256 { w: [0u64, 0u64, 0u64, 0u64] }; N];
    let mut i = 0;
    while i < N {
        out[i] = BID_UINT256 { w: src[i] };
        i += 1;
    }
    out
}

const fn wrap_u128_2d<const N: usize, const M: usize>(src: [[UInt128Words; M]; N]) -> [[BID_UINT128; M]; N] {
    let mut out = [[BID_UINT128 { w: [0u64, 0u64] }; M]; N];
    let mut i = 0;
    while i < N {
        let mut j = 0;
        while j < M {
            out[i][j] = BID_UINT128 { w: src[i][j] };
            j += 1;
        }
        i += 1;
    }
    out
}

const fn wrap_dec_digits<const N: usize>(src: [DecDigitsWords; N]) -> [DEC_DIGITS; N] {
    let mut out = [DEC_DIGITS {
        digits: 0u32,
        threshold_hi: 0u64,
        threshold_lo: 0u64,
        digits1: 0u32,
    }; N];
    let mut i = 0;
    while i < N {
        out[i] = DEC_DIGITS {
            digits: src[i].digits,
            threshold_hi: src[i].threshold_hi,
            threshold_lo: src[i].threshold_lo,
            digits1: src[i].digits1,
        };
        i += 1;
    }
    out
}

const fn widen_i8_pairs<const N: usize>(src: [[i8; 2]; N]) -> [[i32; 2]; N] {
    let mut out = [[0i32; 2]; N];
    let mut i = 0;
    while i < N {
        out[i][0] = src[i][0] as i32;
        out[i][1] = src[i][1] as i32;
        i += 1;
    }
    out
}

const fn take_u128_prefix_19_from_37(src: [BID_UINT128; 37]) -> [BID_UINT128; 19] {
    let mut out = [BID_UINT128 { w: [0u64, 0u64] }; 19];
    let mut i = 0;
    while i < 19 {
        out[i] = src[i];
        i += 1;
    }
    out
}

const fn take_u128_range_19_from_39_start20(src: [BID_UINT128; 39]) -> [BID_UINT128; 19] {
    let mut out = [BID_UINT128 { w: [0u64, 0u64] }; 19];
    let mut i = 0;
    while i < 19 {
        out[i] = src[i + 20];
        i += 1;
    }
    out
}

const fn take_u32_prefix_19_from_37(src: [u32; 37]) -> [u32; 19] {
    let mut out = [0u32; 19];
    let mut i = 0;
    while i < 19 {
        out[i] = src[i];
        i += 1;
    }
    out
}

const fn take_u64_prefix_19_from_37(src: [u64; 37]) -> [u64; 19] {
    let mut out = [0u64; 19];
    let mut i = 0;
    while i < 19 {
        out[i] = src[i];
        i += 1;
    }
    out
}

const fn widen_u32_to_u64<const N: usize>(src: [u32; N]) -> [u64; N] {
    let mut out = [0u64; N];
    let mut i = 0;
    while i < N {
        out[i] = src[i] as u64;
        i += 1;
    }
    out
}

pub const bid_bid_bid_recip_scale32: [i32; BID_BID_BID_RECIP_SCALE32.len()] = BID_BID_BID_RECIP_SCALE32;
pub const bid_bid_reciprocals10_32: [u64; BID_BID_RECIPROCALS10_32.len()] = BID_BID_RECIPROCALS10_32;
pub const bid_convert_table: [[[u32; 2]; 128]; 5] = BID_CONVERT_TABLE;
pub const bid_estimate_bin_expon: [i32; BID_ESTIMATE_BIN_EXPON.len()] = BID_ESTIMATE_BIN_EXPON;
pub const bid_estimate_decimal_digits: [i32; BID_ESTIMATE_DECIMAL_DIGITS.len()] = BID_ESTIMATE_DECIMAL_DIGITS;
pub const bid_Ex128m128: [u32; BID_EX128M128.len()] = BID_EX128M128;
pub const bid_Ex128m128_for64: [u32; 19] = take_u32_prefix_19_from_37(bid_Ex128m128);
pub const bid_Ex192m192: [u32; BID_EX192M192.len()] = BID_EX192M192;
pub const bid_Ex256m256: [u32; BID_EX256M256.len()] = BID_EX256M256;
pub const bid_Ex64m64: [u32; BID_EX64M64.len()] = BID_EX64M64;
pub const bid32_mult_factor: [u64; BID_MULT_FACTOR_NONCOMP32.len()] = widen_u32_to_u64(BID_MULT_FACTOR_NONCOMP32);
pub const bid_factors: [[i8; 2]; BID_FACTORS.len()] = BID_FACTORS;
pub const bid_factors32: [[i32; 2]; BID_FACTORS.len()] = widen_i8_pairs(BID_FACTORS);
pub const bid_half128: [u64; BID_HALF128.len()] = BID_HALF128;
pub const bid_half128_for64: [u64; 19] = take_u64_prefix_19_from_37(bid_half128);
pub const bid_half192: [u64; BID_HALF192.len()] = BID_HALF192;
pub const bid_half256: [u64; BID_HALF256.len()] = BID_HALF256;
pub const bid_half64: [u64; BID_HALF64.len()] = BID_HALF64;
pub const bid_Kx128: [BID_UINT128; BID_KX128.len()] = wrap_u128(BID_KX128);
pub const bid_Kx128_for64: [BID_UINT128; 19] = take_u128_prefix_19_from_37(bid_Kx128);
pub const bid_Kx192: [BID_UINT192; BID_KX192.len()] = wrap_u192(BID_KX192);
pub const bid_Kx256: [BID_UINT256; BID_KX256.len()] = wrap_u256(BID_KX256);
pub const bid_Kx64: [u64; BID_KX64.len()] = BID_KX64;
pub const bid_maskhigh128: [u64; BID_MASKHIGH128.len()] = BID_MASKHIGH128;
pub const bid_maskhigh128_round64: [u64; BID_MASKHIGH128.len()] = BID_MASKHIGH128;
pub const bid_mask128: [u64; BID_MASK128.len()] = BID_MASK128;
pub const bid_mask128_for64: [u64; 19] = take_u64_prefix_19_from_37(bid_mask128);
pub const bid_mask192: [u64; BID_MASK192.len()] = BID_MASK192;
pub const bid_mask256: [u64; BID_MASK256.len()] = BID_MASK256;
pub const bid_mask64: [u64; BID_MASK64.len()] = BID_MASK64;
pub const bid_midi_tbl: [[u8; 3]; BID_MIDI_TBL.len()] = BID_MIDI_TBL;
pub const bid_midpoint128: [BID_UINT128; BID_MIDPOINT128.len()] = wrap_u128(BID_MIDPOINT128);
pub const bid_midpoint192: [BID_UINT192; BID_MIDPOINT192.len()] = wrap_u192(BID_MIDPOINT192);
pub const bid_midpoint256: [BID_UINT256; BID_MIDPOINT256.len()] = wrap_u256(BID_MIDPOINT256);
pub const bid_midpoint64: [u64; BID_MIDPOINT64.len()] = BID_MIDPOINT64;
pub const bid_mult_factor: [u64; BID_MULT_FACTOR_COMPARE64.len()] = BID_MULT_FACTOR_COMPARE64;
pub const bid_mult_factor32: [u32; BID_MULT_FACTOR_MINMAX32.len()] = BID_MULT_FACTOR_MINMAX32;
pub const bid_mult_factor_minmax: [u64; BID_MULT_FACTOR_MINMAX64.len()] = BID_MULT_FACTOR_MINMAX64;
pub const bid_nr_digits: [DEC_DIGITS; BID_NR_DIGITS.len()] = wrap_dec_digits(BID_NR_DIGITS);
pub const mod10_18_tbl: [[u64; 128]; MOD10_18_TBL.len()] = MOD10_18_TBL;
pub const bid_onehalf128: [u64; BID_ONEHALF128.len()] = BID_ONEHALF128;
pub const bid_onehalf128_round64: [u64; BID_ONEHALF128.len()] = BID_ONEHALF128;
pub const bid_packed_10000_zeros: [u8; BID_PACKED_10000_ZEROS.len()] = BID_PACKED_10000_ZEROS;
pub const bid_power10_index_binexp: [u64; BID_POWER10_INDEX_BINEXP.len()] = BID_POWER10_INDEX_BINEXP;
pub const bid_power10_index_binexp_128: [BID_UINT128; BID_POWER10_INDEX_BINEXP_128.len()] = wrap_u128(BID_POWER10_INDEX_BINEXP_128);
pub const bid_power10_table_128: [BID_UINT128; BID_POWER10_TABLE_128.len()] = wrap_u128(BID_POWER10_TABLE_128);
pub const bid_reciprocals10_128: [BID_UINT128; BID_RECIPROCALS10_128.len()] = wrap_u128(BID_RECIPROCALS10_128);
pub const bid_reciprocals10_64: [u64; BID_RECIPROCALS10_64.len()] = BID_RECIPROCALS10_64;
pub const bid_recip_scale: [i32; BID_RECIP_SCALE.len()] = BID_RECIP_SCALE;
pub const bid_round_const_table: [[u64; 19]; 5] = BID_ROUND_CONST_TABLE;
pub const bid_round_const_table_128: [[BID_UINT128; 36]; 5] = wrap_u128_2d(BID_ROUND_CONST_TABLE_128);
pub const bid_shiftright128: [i32; BID_SHIFTRIGHT128.len()] = BID_SHIFTRIGHT128;
pub const bid_shiftright128_round64: [i32; BID_SHIFTRIGHT128.len()] = BID_SHIFTRIGHT128;
pub const bid_short_recip_scale: [i32; BID_SHORT_RECIP_SCALE.len()] = BID_SHORT_RECIP_SCALE;
pub const bid_ten2k128: [BID_UINT128; 19] = take_u128_range_19_from_39_start20(bid_power10_table_128);
pub const bid_ten2k256: [BID_UINT256; BID_TEN2K256.len()] = wrap_u256(BID_TEN2K256);
pub const bid_ten2k64: [u64; BID_TEN2K64.len()] = BID_TEN2K64;
pub const bid_ten2mxtrunc128: [BID_UINT128; BID_TEN2MXTRUNC128.len()] = wrap_u128(BID_TEN2MXTRUNC128);
pub const bid_ten2mxtrunc128_for64: [BID_UINT128; 19] = take_u128_prefix_19_from_37(bid_ten2mxtrunc128);
pub const bid_ten2mxtrunc192: [BID_UINT192; BID_TEN2MXTRUNC192.len()] = wrap_u192(BID_TEN2MXTRUNC192);
pub const bid_ten2mxtrunc256: [BID_UINT256; BID_TEN2MXTRUNC256.len()] = wrap_u256(BID_TEN2MXTRUNC256);
pub const bid_ten2mxtrunc64: [u64; BID_TEN2MXTRUNC64.len()] = BID_TEN2MXTRUNC64;
pub const bid_ten2mk128: [BID_UINT128; BID_TEN2MK128.len()] = wrap_u128(BID_TEN2MK128);
pub const bid_ten2mk128trunc: [BID_UINT128; BID_TEN2MK128TRUNC.len()] = wrap_u128(BID_TEN2MK128TRUNC);
pub const bid_ten2mk64: [u64; BID_TEN2MK64.len()] = BID_TEN2MK64;
pub const bid_ten2mk64_round64: [u64; BID_TEN2MK64.len()] = BID_TEN2MK64;
pub const bid_roundbound_128: [BID_UINT128; BID_ROUNDBOUND_128.len()] = wrap_u128(BID_ROUNDBOUND_128);
pub const bid_breakpoints_binary32: [BID_UINT128; BID_BREAKPOINTS_BINARY32.len()] = wrap_u128(BID_BREAKPOINTS_BINARY32);
pub const bid_exponents_binary32: [i32; BID_EXPONENTS_BINARY32.len()] = BID_EXPONENTS_BINARY32;
pub const bid_multipliers1_binary32: [BID_UINT256; BID_MULTIPLIERS1_BINARY32.len()] = wrap_u256(BID_MULTIPLIERS1_BINARY32);
pub const bid_multipliers2_binary32: [BID_UINT256; BID_MULTIPLIERS2_BINARY32.len()] = wrap_u256(BID_MULTIPLIERS2_BINARY32);
pub const bid_breakpoints_binary64: [BID_UINT128; BID_BREAKPOINTS_BINARY64.len()] = wrap_u128(BID_BREAKPOINTS_BINARY64);
pub const bid_exponents_binary64: [i32; BID_EXPONENTS_BINARY64.len()] = BID_EXPONENTS_BINARY64;
pub const bid_multipliers1_binary64: [BID_UINT256; BID_MULTIPLIERS1_BINARY64.len()] = wrap_u256(BID_MULTIPLIERS1_BINARY64);
pub const bid_multipliers2_binary64: [BID_UINT256; BID_MULTIPLIERS2_BINARY64.len()] = wrap_u256(BID_MULTIPLIERS2_BINARY64);
`
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", filepath.Dir(outPath), err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s\n", outPath)
}

func findProjectRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "cannot find project root")
			os.Exit(1)
		}
		dir = parent
	}
}
