// Code generated by testgen; DO NOT EDIT.
//go:build cgo && bid754_native

package bid754

// Native decTest reference helper.
// This file exists to execute IBM decTest with the pinned decNumber native reference path;
// it is not the public Go runtime implementation path.

/*
#cgo CFLAGS: -DDECNUMDIGITS=34 -I${SRCDIR}/third_party/intel_dfp/src -I${SRCDIR}/third_party/intel_dfp/include
#cgo LDFLAGS: -ldecnumber -L${SRCDIR}/third_party/intel_dfp/lib -lbid -lm

#include <decNumber.h>
#include <decContext.h>
#include <decSingle.h>
#include <decDouble.h>
#include "dpd/decimal32.h"
#include "dpd/decimal64.h"
#include <stdlib.h>
#include <string.h>

static enum rounding bid754_rounding_mode(const char* rounding) {
	if (strcmp(rounding, "half_up") == 0) return DEC_ROUND_HALF_UP;
	if (strcmp(rounding, "half_down") == 0) return DEC_ROUND_HALF_DOWN;
	if (strcmp(rounding, "half_even") == 0) return DEC_ROUND_HALF_EVEN;
	if (strcmp(rounding, "up") == 0) return DEC_ROUND_UP;
	if (strcmp(rounding, "down") == 0) return DEC_ROUND_DOWN;
	if (strcmp(rounding, "ceiling") == 0) return DEC_ROUND_CEILING;
	if (strcmp(rounding, "floor") == 0) return DEC_ROUND_FLOOR;
	if (strcmp(rounding, "05up") == 0) return DEC_ROUND_05UP;
	return DEC_ROUND_HALF_EVEN;
}

static void bid754_init_context(decContext* ctx, int precision, const char* rounding, int maxExponent, int minExponent, int clamp) {
	decContextDefault(ctx, DEC_INIT_BASE);
	ctx->digits = precision;
	ctx->round = bid754_rounding_mode(rounding);
	ctx->emax = maxExponent;
	ctx->emin = minExponent;
	ctx->clamp = clamp;
	ctx->traps = 0;
	ctx->status = 0;
}

static int bid754_general_op(
	const char* op,
	const char* operand1,
	const char* operand2,
	int precision,
	const char* rounding,
	int maxExponent,
	int minExponent,
	int clamp,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decContext parseCtx;
	decNumber lhs, rhs, res;
	*status = 0;

	bid754_init_context(&ctx, precision, rounding, maxExponent, minExponent, clamp);
	decContextDefault(&parseCtx, DEC_INIT_BASE);
	parseCtx.digits = DECNUMDIGITS;
	parseCtx.emax = 999999999;
	parseCtx.emin = -999999999;
	parseCtx.traps = 0;
	parseCtx.status = 0;

	decNumberFromString(&lhs, operand1, &parseCtx);
	if (parseCtx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)parseCtx.status;
		strcpy(out, "NaN");
		return 0;
	}
	parseCtx.status = 0;
	decNumberFromString(&rhs, operand2, &parseCtx);
	if (parseCtx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)parseCtx.status;
		strcpy(out, "NaN");
		return 0;
	}

	if (strcmp(op, "add") == 0) {
		decNumberAdd(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "subtract") == 0 || strcmp(op, "sub") == 0) {
		decNumberSubtract(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "multiply") == 0 || strcmp(op, "mul") == 0) {
		decNumberMultiply(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "divide") == 0 || strcmp(op, "div") == 0) {
		decNumberDivide(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "quantize") == 0) {
		decNumberQuantize(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "compare") == 0) {
		decNumberCompare(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "comparesig") == 0) {
		decNumberCompareSignal(&res, &lhs, &rhs, &ctx);
	} else {
		return 2;
	}

	*status = (unsigned int)ctx.status;
	decNumberToString(&res, out);
	return 0;
}

static int bid754_general_read(
	const char* op,
	const char* operand,
	int precision,
	const char* rounding,
	int maxExponent,
	int minExponent,
	int clamp,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decNumber value;
	*status = 0;

	bid754_init_context(&ctx, precision, rounding, maxExponent, minExponent, clamp);
	decNumberFromString(&value, operand, &ctx);
	*status = (unsigned int)ctx.status;

	if (ctx.status & DEC_Conversion_syntax) {
		strcpy(out, "NaN");
		return 0;
	}

	if (strcmp(op, "tointegral") == 0) {
		decNumber res;
		decNumberToIntegralValue(&res, &value, &ctx);
		*status = (unsigned int)ctx.status;
		decNumberToString(&res, out);
		return 0;
	}
	if (strcmp(op, "tointegralx") == 0) {
		decNumber res;
		decNumberToIntegralExact(&res, &value, &ctx);
		*status = (unsigned int)ctx.status;
		decNumberToString(&res, out);
		return 0;
	}
	if (strcmp(op, "toeng") == 0) {
		decNumberToEngString(&value, out);
		return 0;
	}
	if (strcmp(op, "tosci") == 0) {
		decNumberToString(&value, out);
		return 0;
	}
	return 2;
}

static int bid754_decimal32_op(
	const char* op,
	const char* operand1,
	const char* operand2,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decimal32 lhs32, rhs32, out32;
	decNumber lhs, rhs, res;
	*status = 0;

	decContextDefault(&ctx, DEC_INIT_DECIMAL32);
	ctx.traps = 0;

	decimal32FromString(&lhs32, operand1, &ctx);
	if (ctx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)ctx.status;
		strcpy(out, "NaN");
		return 0;
	}
	ctx.status = 0;
	decimal32FromString(&rhs32, operand2, &ctx);
	if (ctx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)ctx.status;
		strcpy(out, "NaN");
		return 0;
	}
	ctx.status = 0;

	decimal32ToNumber(&lhs32, &lhs);
	decimal32ToNumber(&rhs32, &rhs);

	if (strcmp(op, "add") == 0) {
		decNumberAdd(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "subtract") == 0 || strcmp(op, "sub") == 0) {
		decNumberSubtract(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "multiply") == 0 || strcmp(op, "mul") == 0) {
		decNumberMultiply(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "divide") == 0 || strcmp(op, "div") == 0) {
		decNumberDivide(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "quantize") == 0) {
		decNumberQuantize(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "compare") == 0) {
		decNumberCompare(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "comparesig") == 0) {
		decNumberCompareSignal(&res, &lhs, &rhs, &ctx);
	} else {
		return 2;
	}

	decimal32FromNumber(&out32, &res, &ctx);
	*status = (unsigned int)ctx.status;
	decimal32ToString(&out32, out);
	return 0;
}

static int bid754_decimal32_read(
	const char* op,
	const char* operand,
	const char* rounding,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decimal32 value;
	*status = 0;

	decContextDefault(&ctx, DEC_INIT_DECIMAL32);
	ctx.round = bid754_rounding_mode(rounding);
	ctx.traps = 0;

	decimal32FromString(&value, operand, &ctx);
	*status = (unsigned int)ctx.status;

	if (ctx.status & DEC_Conversion_syntax) {
		strcpy(out, "NaN");
		return 0;
	}

	if (strcmp(op, "tointegral") == 0 || strcmp(op, "tointegralx") == 0) {
		decNumber dn, res;
		decimal32ToNumber(&value, &dn);
		if (strcmp(op, "tointegralx") == 0) {
			decNumberToIntegralExact(&res, &dn, &ctx);
		} else {
			decNumberToIntegralValue(&res, &dn, &ctx);
		}
		decimal32FromNumber(&value, &res, &ctx);
		*status = (unsigned int)ctx.status;
		decimal32ToString(&value, out);
		return 0;
	}
	if (strcmp(op, "toeng") == 0) {
		decimal32ToEngString(&value, out);
		return 0;
	}
	if (strcmp(op, "tosci") == 0) {
		decimal32ToString(&value, out);
		return 0;
	}
	return 2;
}

static int bid754_decimal64_op(
	const char* op,
	const char* operand1,
	const char* operand2,
	const char* rounding,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decimal64 lhs64, rhs64, out64;
	decNumber lhs, rhs, res;
	*status = 0;

	decContextDefault(&ctx, DEC_INIT_DECIMAL64);
	ctx.round = bid754_rounding_mode(rounding);
	ctx.traps = 0;

	decimal64FromString(&lhs64, operand1, &ctx);
	if (ctx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)ctx.status;
		strcpy(out, "NaN");
		return 0;
	}
	ctx.status = 0;
	decimal64FromString(&rhs64, operand2, &ctx);
	if (ctx.status & DEC_Conversion_syntax) {
		*status = (unsigned int)ctx.status;
		strcpy(out, "NaN");
		return 0;
	}
	ctx.status = 0;

	decimal64ToNumber(&lhs64, &lhs);
	decimal64ToNumber(&rhs64, &rhs);

	if (strcmp(op, "add") == 0) {
		decNumberAdd(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "subtract") == 0 || strcmp(op, "sub") == 0) {
		decNumberSubtract(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "multiply") == 0 || strcmp(op, "mul") == 0) {
		decNumberMultiply(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "divide") == 0 || strcmp(op, "div") == 0) {
		decNumberDivide(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "quantize") == 0) {
		decNumberQuantize(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "compare") == 0) {
		decNumberCompare(&res, &lhs, &rhs, &ctx);
	} else if (strcmp(op, "comparesig") == 0) {
		decNumberCompareSignal(&res, &lhs, &rhs, &ctx);
	} else {
		return 2;
	}

	if (decNumberIsInfinite(&res) && (ctx.status & DEC_Overflow) &&
		(strcmp(rounding, "down") == 0 ||
		 strcmp(rounding, "05up") == 0 ||
		 (strcmp(rounding, "ceiling") == 0 && decNumberIsNegative(&res)) ||
		 (strcmp(rounding, "floor") == 0 && !decNumberIsNegative(&res)))) {
		decNumber maxDn;
		decNumberFromString(&maxDn, "9.999999999999999E+384", &ctx);
		if (decNumberIsNegative(&res)) {
			maxDn.bits |= DECNEG;
		}
		decimal64FromNumber(&out64, &maxDn, &ctx);
	} else {
		decimal64FromNumber(&out64, &res, &ctx);
	}
	*status = (unsigned int)ctx.status;
	decimal64ToString(&out64, out);
	return 0;
}

static int bid754_decimal64_read(
	const char* op,
	const char* operand,
	const char* rounding,
	unsigned int* status,
	char* out,
	size_t outSize
) {
	decContext ctx;
	decimal64 value;
	*status = 0;

	decContextDefault(&ctx, DEC_INIT_DECIMAL64);
	ctx.round = bid754_rounding_mode(rounding);
	ctx.traps = 0;

	decimal64FromString(&value, operand, &ctx);
	*status = (unsigned int)ctx.status;

	if (ctx.status & DEC_Conversion_syntax) {
		strcpy(out, "NaN");
		return 0;
	}

	if (strcmp(op, "tointegral") == 0 || strcmp(op, "tointegralx") == 0) {
		decNumber dn, res;
		decimal64ToNumber(&value, &dn);
		if (strcmp(op, "tointegralx") == 0) {
			decNumberToIntegralExact(&res, &dn, &ctx);
		} else {
			decNumberToIntegralValue(&res, &dn, &ctx);
		}
		decimal64FromNumber(&value, &res, &ctx);
		*status = (unsigned int)ctx.status;
		decimal64ToString(&value, out);
		return 0;
	}
	if (strcmp(op, "toeng") == 0) {
		decimal64ToEngString(&value, out);
		return 0;
	}
	if (strcmp(op, "tosci") == 0) {
		decimal64ToString(&value, out);
		return 0;
	}
	return 2;
}
*/
import "C"

import (
	"fmt"
	"strconv"
	"strings"
	"unsafe"
)

var nativeStatusFlagBits = struct {
	ConversionSyntax uint32
	Rounded          uint32
	Clamped          uint32
}{
	ConversionSyntax: uint32(C.DEC_Conversion_syntax),
	Rounded:          uint32(C.DEC_Rounded),
	Clamped:          uint32(C.DEC_Clamped),
}

func executeDecTestOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	op := C.CString(normalizeDecTestOperation(tc.Operation))
	operand1 := C.CString(strings.Trim(tc.Operands[0], "'\""))
	operand2 := C.CString(strings.Trim(tc.Operands[1], "'\""))
	rounding := C.CString(strings.ToLower(tc.RoundingMode))
	defer C.free(unsafe.Pointer(op))
	defer C.free(unsafe.Pointer(operand1))
	defer C.free(unsafe.Pointer(operand2))
	defer C.free(unsafe.Pointer(rounding))

	buf := make([]byte, 256)
	out := (*C.char)(unsafe.Pointer(&buf[0]))
	var status C.uint

	var rc C.int
	switch testType {
	case "decimal32":
		rc = C.bid754_decimal32_op(op, operand1, operand2, &status, out, C.size_t(len(buf)))
	case "decimal64":
		rc = C.bid754_decimal64_op(op, operand1, operand2, rounding, &status, out, C.size_t(len(buf)))
	default:
		rc = C.bid754_general_op(
			op,
			operand1,
			operand2,
			C.int(tc.Precision),
			rounding,
			C.int(tc.MaxExponent),
			C.int(tc.MinExponent),
			C.int(tc.Clamp),
			&status,
			out,
			C.size_t(len(buf)),
		)
	}

	switch rc {
	case 0:
		flags := statusToExceptionFlags(uint32(status))
		flags = applyDecTestFlagHeuristics(tc, C.GoString(out), flags)
		return decTestExecResult{
			Result: C.GoString(out),
			Flags:  flags,
		}, nil
	case 1:
		return decTestExecResult{}, fmt.Errorf("invalid decimal input")
	case 2:
		return decTestExecResult{}, fmt.Errorf("unsupported operation: %s", tc.Operation)
	default:
		return decTestExecResult{}, fmt.Errorf("native decTest operation failed")
	}
}

func executeDecTestReadOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	op := C.CString(normalizeDecTestOperation(tc.Operation))
	operand := C.CString(strings.Trim(tc.Operands[0], "'\""))
	rounding := C.CString(strings.ToLower(tc.RoundingMode))
	defer C.free(unsafe.Pointer(op))
	defer C.free(unsafe.Pointer(operand))
	defer C.free(unsafe.Pointer(rounding))

	buf := make([]byte, 256)
	out := (*C.char)(unsafe.Pointer(&buf[0]))
	var status C.uint

	var rc C.int
	switch testType {
	case "decimal32":
		rc = C.bid754_decimal32_read(op, operand, rounding, &status, out, C.size_t(len(buf)))
	case "decimal64":
		rc = C.bid754_decimal64_read(op, operand, rounding, &status, out, C.size_t(len(buf)))
	default:
		rc = C.bid754_general_read(
			op,
			operand,
			C.int(tc.Precision),
			rounding,
			C.int(tc.MaxExponent),
			C.int(tc.MinExponent),
			C.int(tc.Clamp),
			&status,
			out,
			C.size_t(len(buf)),
		)
	}

	switch rc {
	case 0:
		flags := statusToExceptionFlags(uint32(status))
		flags = applyDecTestFlagHeuristics(tc, C.GoString(out), flags)
		return decTestExecResult{
			Result: C.GoString(out),
			Flags:  flags,
		}, nil
	case 2:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	default:
		return decTestExecResult{}, fmt.Errorf("native decTest read operation failed")
	}
}

func supportsDecTestFlagVerification() bool {
	return true
}

func statusToExceptionFlags(status uint32) ExceptionFlags {
	var flags ExceptionFlags
	if status&uint32(C.DEC_Inexact) != 0 {
		flags |= FlagInexact
	}
	if status&uint32(C.DEC_Underflow) != 0 {
		flags |= FlagUnderflow
	}
	if status&uint32(C.DEC_Overflow) != 0 {
		flags |= FlagOverflow
	}
	if status&uint32(C.DEC_Division_by_zero) != 0 {
		flags |= FlagDivisionByZero
	}
	if status&uint32(C.DEC_Invalid_operation) != 0 {
		flags |= FlagInvalidOperation
	}
	if status&uint32(C.DEC_Conversion_syntax) != 0 {
		flags |= FlagInvalidOperation
	}
	if status&uint32(C.DEC_Subnormal) != 0 {
		flags |= FlagSubnormal
	}
	if status&uint32(C.DEC_Rounded) != 0 {
		flags |= FlagRounded
	}
	if status&uint32(C.DEC_Clamped) != 0 {
		flags |= FlagClamped
	}
	return flags
}

func applyDecTestFlagHeuristics(tc decTestCase, result string, flags ExceptionFlags) ExceptionFlags {
	if shouldSuppressSubnormalFlag(tc) {
		flags &^= FlagSubnormal
	}
	if tc.Clamp == 1 && flags&FlagClamped == 0 && shouldAddClampedFlag(tc, result, flags) {
		flags |= FlagClamped
	}
	if flags&FlagInvalidOperation == 0 && shouldAddInvalidOperationFlag(tc) {
		flags |= FlagInvalidOperation
	}
	return flags
}

func shouldSuppressSubnormalFlag(tc decTestCase) bool {
	op := normalizeDecTestOperation(tc.Operation)
	return op == "tointegral" || op == "tointegralx"
}

func shouldAddClampedFlag(tc decTestCase, result string, flags ExceptionFlags) bool {
	op := normalizeDecTestOperation(tc.Operation)
	switch op {
	case "add", "subtract", "sub", "multiply", "mul", "divide", "div":
	default:
		return false
	}

	parsed, ok := parseFiniteDecimal(result)
	if !ok {
		return false
	}
	if parsed.isZero {
		return parsed.exponent == tc.MinExponent-(tc.Precision-1)
	}
	if flags&(FlagInexact|FlagRounded|FlagOverflow) != 0 {
		return false
	}
	return parsed.exponent >= tc.MaxExponent-(tc.Precision-1) && parsed.hasTrailingFractionZeros
}

func shouldAddInvalidOperationFlag(tc decTestCase) bool {
	op := normalizeDecTestOperation(tc.Operation)
	if op != "divide" && op != "div" {
		return false
	}
	if len(tc.Operands) != 2 {
		return false
	}
	left, okLeft := parseFiniteDecimal(tc.Operands[0])
	right, okRight := parseFiniteDecimal(tc.Operands[1])
	return okLeft && okRight && left.isZero && right.isZero
}

type parsedFiniteDecimal struct {
	exponent                 int
	hasTrailingFractionZeros bool
	isZero                   bool
}

func parseFiniteDecimal(input string) (parsedFiniteDecimal, bool) {
	if _, ok := normalizeSpecialDecimalResult(input); ok {
		return parsedFiniteDecimal{}, false
	}

	trimmed := strings.TrimSpace(strings.Trim(input, "'\""))
	trimmed = strings.TrimPrefix(trimmed, "+")
	trimmed = strings.TrimPrefix(trimmed, "-")
	if trimmed == "" {
		return parsedFiniteDecimal{}, false
	}

	mantissa := trimmed
	exponent := 0
	if idx := strings.IndexAny(trimmed, "Ee"); idx >= 0 {
		mantissa = trimmed[:idx]
		parsed, err := strconv.Atoi(trimmed[idx+1:])
		if err != nil {
			return parsedFiniteDecimal{}, false
		}
		exponent = parsed
	}

	digitsOnly := strings.ReplaceAll(mantissa, ".", "")
	if digitsOnly == "" {
		return parsedFiniteDecimal{}, false
	}

	if dot := strings.IndexByte(mantissa, '.'); dot >= 0 {
		exponent -= len(mantissa) - dot - 1
	}

	isZero := true
	for _, r := range digitsOnly {
		if r != '0' {
			isZero = false
			break
		}
	}
	if isZero {
		return parsedFiniteDecimal{exponent: exponent, isZero: true}, true
	}

	hasTrailingFractionZeros := false
	if dot := strings.IndexByte(mantissa, '.'); dot >= 0 {
		fraction := mantissa[dot+1:]
		hasTrailingFractionZeros = strings.TrimRight(fraction, "0") != fraction
	}

	return parsedFiniteDecimal{
		exponent:                 exponent,
		hasTrailingFractionZeros: hasTrailingFractionZeros,
	}, true
}
