// Code generated by testgen; DO NOT EDIT.
package bid754

import (
	"fmt"
	"strconv"
)

func executeDecTestCompareTotalOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	op := normalizeDecTestOperation(tc.Operation)
	if op != "comparetotal" && op != "comparetotmag" {
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
	if len(tc.Operands) != 2 {
		return decTestExecResult{}, fmt.Errorf("%s requires 2 operands, got %d", tc.Operation, len(tc.Operands))
	}
	if decTestOperandString(tc.Operands[0]) == "#" || decTestOperandString(tc.Operands[1]) == "#" {
		return decTestExecResult{Result: "NaN", Flags: FlagInvalidOperation}, nil
	}

	var result int
	switch testType {
	case "decimal32":
		a, err := NewDecimal32BIDDirect(decTestOperandString(tc.Operands[0]))
		if err != nil {
			return decTestExecResult{}, err
		}
		b, err := NewDecimal32BIDDirect(decTestOperandString(tc.Operands[1]))
		if err != nil {
			return decTestExecResult{}, err
		}
		result = executeDecimal32CompareTotalOperation(op, a, b)
	case "decimal64":
		a, err := NewDecimal64BIDDirect(decTestOperandString(tc.Operands[0]))
		if err != nil {
			return decTestExecResult{}, err
		}
		b, err := NewDecimal64BIDDirect(decTestOperandString(tc.Operands[1]))
		if err != nil {
			return decTestExecResult{}, err
		}
		result = executeDecimal64CompareTotalOperation(op, a, b)
	case "decimal128":
		a, err := NewDecimal128BIDDirect(decTestOperandString(tc.Operands[0]))
		if err != nil {
			return decTestExecResult{}, err
		}
		b, err := NewDecimal128BIDDirect(decTestOperandString(tc.Operands[1]))
		if err != nil {
			return decTestExecResult{}, err
		}
		result = executeDecimal128CompareTotalOperation(op, a, b)
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}

	return decTestExecResult{Result: strconv.Itoa(result)}, nil
}

func executeDecimal32CompareTotalOperation(op string, a, b Decimal32BID) int {
	if op == "comparetotmag" {
		return a.CompareTotalMag(b)
	}
	return a.CompareTotal(b)
}

func executeDecimal64CompareTotalOperation(op string, a, b Decimal64BID) int {
	if op == "comparetotmag" {
		return a.CompareTotalMag(b)
	}
	return a.CompareTotal(b)
}

func executeDecimal128CompareTotalOperation(op string, a, b Decimal128BID) int {
	if op == "comparetotmag" {
		return a.CompareTotalMag(b)
	}
	return a.CompareTotal(b)
}
