// Code generated by testgen; DO NOT EDIT.
package bid754

import (
	"fmt"
	"strings"
)

func executeDecTestNextTowardOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	if len(tc.Operands) != 2 {
		return decTestExecResult{}, fmt.Errorf("%s requires 2 operands, got %d", tc.Operation, len(tc.Operands))
	}
	if decTestOperandString(tc.Operands[0]) == "#" || decTestOperandString(tc.Operands[1]) == "#" {
		return decTestExecResult{Result: "NaN", Flags: FlagInvalidOperation}, nil
	}
	rndMode, err := decTestCaseRoundingMode(tc)
	if err != nil {
		return decTestExecResult{}, err
	}

	switch testType {
	case "decimal32":
		a, target32, parseFlags := parseDecTestDecimal32Pair(tc.Operands, rndMode)
		target, _ := target32.ToDecimal128()
		result, flags := a.NextToward(target)
		flags |= parseFlags
		resultString := result.String()
		return decTestExecResult{Result: resultString, Flags: decTestNextTowardFlags(flags, resultString, tc.Operands)}, nil
	case "decimal64":
		a, target64, parseFlags := parseDecTestDecimal64Pair(tc.Operands, rndMode)
		target, _ := target64.ToDecimal128()
		result, flags := a.NextToward(target)
		flags |= parseFlags
		resultString := result.String()
		return decTestExecResult{Result: resultString, Flags: decTestNextTowardFlags(flags, resultString, tc.Operands)}, nil
	case "decimal128":
		a, b, parseFlags := parseDecTestDecimal128Pair(tc.Operands, rndMode)
		result, flags := a.NextToward(b)
		flags |= parseFlags
		resultString := result.String()
		return decTestExecResult{Result: resultString, Flags: decTestNextTowardFlags(flags, resultString, tc.Operands)}, nil
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
}

func decTestNextTowardFlags(flags ExceptionFlags, result string, operands []string) ExceptionFlags {
	for _, operand := range operands {
		if strings.Contains(strings.ToLower(decTestOperandString(operand)), "snan") {
			flags |= FlagInvalidOperation
		}
	}
	if flags&FlagInexact != 0 {
		flags |= FlagRounded
	}
	if flags&FlagUnderflow != 0 {
		flags |= FlagSubnormal
		if parsed, ok := parseComparableDecimal(result); ok && parsed.isZero {
			flags |= FlagClamped
		}
	}
	return flags
}
