// Code generated by testgen; DO NOT EDIT.
package bid754

import (
	"fmt"
	"strings"
)

func executeDecTestClassOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	if len(tc.Operands) != 1 {
		return decTestExecResult{}, fmt.Errorf("%s requires 1 operand, got %d", tc.Operation, len(tc.Operands))
	}

	operand := decTestOperandString(tc.Operands[0])
	var result DecimalClass
	switch testType {
	case "decimal32":
		d, err := NewDecimal32BIDDirect(operand)
		if err != nil {
			return decTestExecResult{}, err
		}
		result = d.Class()
	case "decimal64":
		d, err := NewDecimal64BIDDirect(operand)
		if err != nil {
			return decTestExecResult{}, err
		}
		result = d.Class()
	case "decimal128":
		d, err := NewDecimal128BIDDirect(operand)
		if err != nil {
			return decTestExecResult{}, err
		}
		result = d.Class()
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}

	return decTestExecResult{Result: result.String()}, nil
}

func compareDecTestTokenResult(expected, actual string) bool {
	return strings.Trim(expected, "'\"") == strings.Trim(actual, "'\"")
}
