// Code generated by testgen; DO NOT EDIT.
package bid754

import "fmt"

func executeDecTestMinMaxOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	op := normalizeDecTestOperation(tc.Operation)
	switch op {
	case "min", "max", "minmag", "maxmag":
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
	if len(tc.Operands) != 2 {
		return decTestExecResult{}, fmt.Errorf("%s requires 2 operands, got %d", tc.Operation, len(tc.Operands))
	}
	if decTestOperandString(tc.Operands[0]) == "#" || decTestOperandString(tc.Operands[1]) == "#" {
		return decTestExecResult{Result: "NaN", Flags: FlagInvalidOperation}, nil
	}
	rndMode, err := decTestCaseRoundingMode(tc)
	if err != nil {
		return decTestExecResult{}, err
	}

	switch testType {
	case "decimal32":
		a, b, parseFlags := parseDecTestDecimal32Pair(tc.Operands, rndMode)
		result, flags := executeDecimal32MinMaxOperation(op, a, b)
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: decTestFlagsWithSubnormalClass(flags, result.Class())}, nil
	case "decimal64":
		a, b, parseFlags := parseDecTestDecimal64Pair(tc.Operands, rndMode)
		result, flags := executeDecimal64MinMaxOperation(op, a, b)
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: decTestFlagsWithSubnormalClass(flags, result.Class())}, nil
	case "decimal128":
		a, b, parseFlags := parseDecTestDecimal128Pair(tc.Operands, rndMode)
		result, flags := executeDecimal128MinMaxOperation(op, a, b)
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: decTestFlagsWithSubnormalClass(flags, result.Class())}, nil
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
}

func executeDecimal32MinMaxOperation(op string, a, b Decimal32BID) (Decimal32BID, ExceptionFlags) {
	switch op {
	case "min":
		return a.MinNum(b)
	case "max":
		return a.MaxNum(b)
	case "minmag":
		return a.MinNumMag(b)
	default:
		return a.MaxNumMag(b)
	}
}

func executeDecimal64MinMaxOperation(op string, a, b Decimal64BID) (Decimal64BID, ExceptionFlags) {
	switch op {
	case "min":
		return a.MinNum(b)
	case "max":
		return a.MaxNum(b)
	case "minmag":
		return a.MinNumMag(b)
	default:
		return a.MaxNumMag(b)
	}
}

func executeDecimal128MinMaxOperation(op string, a, b Decimal128BID) (Decimal128BID, ExceptionFlags) {
	switch op {
	case "min":
		return a.MinNum(b)
	case "max":
		return a.MaxNum(b)
	case "minmag":
		return a.MinNumMag(b)
	default:
		return a.MaxNumMag(b)
	}
}

func decTestFlagsWithSubnormalClass(flags ExceptionFlags, class DecimalClass) ExceptionFlags {
	switch class {
	case DecimalClassNegativeSubnormal, DecimalClassPositiveSubnormal:
		flags |= FlagSubnormal
	}
	return flags
}
