// Code generated by testgen; DO NOT EDIT.
package bid754

import (
	"fmt"
	"strings"
)

func executeDecTestClassOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	if len(tc.Operands) != 1 {
		return decTestExecResult{}, fmt.Errorf("%s requires 1 operand, got %d", tc.Operation, len(tc.Operands))
	}

	operand := decTestOperandString(tc.Operands[0])
	rndMode, err := decTestCaseRoundingMode(tc)
	if err != nil {
		return decTestExecResult{}, err
	}
	var result DecimalClass
	var parseFlags ExceptionFlags
	switch testType {
	case "decimal32":
		d, flags := parseDecTestDecimal32Operand(operand, rndMode)
		parseFlags = flags
		result = d.Class()
	case "decimal64":
		d, flags := parseDecTestDecimal64Operand(operand, rndMode)
		parseFlags = flags
		result = d.Class()
	case "decimal128":
		d, flags := parseDecTestDecimal128Operand(operand, rndMode)
		parseFlags = flags
		result = d.Class()
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}

	return decTestExecResult{Result: result.String(), Flags: parseFlags}, nil
}

func compareDecTestTokenResult(expected, actual string) bool {
	return strings.Trim(expected, "'\"") == strings.Trim(actual, "'\"")
}
