// Code generated by testgen; DO NOT EDIT.
package bid754

import "fmt"

func executeDecTestLogBOperation(tc decTestCase, testType string) (decTestExecResult, error) {
	if normalizeDecTestOperation(tc.Operation) != "logb" {
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
	if len(tc.Operands) != 1 {
		return decTestExecResult{}, fmt.Errorf("%s requires 1 operand, got %d", tc.Operation, len(tc.Operands))
	}
	if decTestOperandString(tc.Operands[0]) == "#" {
		return decTestExecResult{Result: "NaN", Flags: FlagInvalidOperation}, nil
	}
	rndMode, err := decTestCaseRoundingMode(tc)
	if err != nil {
		return decTestExecResult{}, err
	}

	switch testType {
	case "decimal32":
		a, parseFlags := parseDecTestDecimal32Operand(tc.Operands[0], rndMode)
		result, flags := a.LogB()
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: flags}, nil
	case "decimal64":
		a, parseFlags := parseDecTestDecimal64Operand(tc.Operands[0], rndMode)
		result, flags := a.LogB()
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: flags}, nil
	case "decimal128":
		a, parseFlags := parseDecTestDecimal128Operand(tc.Operands[0], rndMode)
		result, flags := a.LogB()
		flags |= parseFlags
		return decTestExecResult{Result: result.String(), Flags: flags}, nil
	default:
		return decTestExecResult{}, fmt.Errorf("%w: %s", errUnsupportedDecTestOperation, tc.Operation)
	}
}
