// Code generated by go-typegen; DO NOT EDIT.
// Source manifest: typegen_manifest.json.

package bid754

// EncodingFormat is the decimal encoding format selector.
type EncodingFormat int

// RoundingMode is the IEEE 754 rounding selector.
type RoundingMode int

// ExceptionFlags stores IEEE 754 exception bits.
type ExceptionFlags int

// Encoding formats.
const (
	EncodingBID EncodingFormat = iota // Binary Integer Decimal (Intel)
)

// Rounding modes.
const (
	RoundNearestEven    RoundingMode = iota // IEEE 754 default
	RoundNearestAway    RoundingMode = iota // Nearest, ties away from zero
	RoundTowardZero     RoundingMode = iota // Toward zero
	RoundTowardPositive RoundingMode = iota // Toward positive infinity
	RoundTowardNegative RoundingMode = iota // Toward negative infinity
)

// Exception flags.
const (
	FlagInexact          ExceptionFlags = 1 << iota // Inexact result
	FlagUnderflow        ExceptionFlags = 1 << iota // Underflow
	FlagOverflow         ExceptionFlags = 1 << iota // Overflow
	FlagDivisionByZero   ExceptionFlags = 1 << iota // Division by zero
	FlagInvalidOperation ExceptionFlags = 1 << iota // Invalid operation
	FlagSubnormal        ExceptionFlags = 1 << iota // Subnormal result
	FlagRounded          ExceptionFlags = 1 << iota // Rounded result
	FlagClamped          ExceptionFlags = 1 << iota // Exponent clamped
)

// Decimal32BID is a 32-bit BID decimal routed through the Go mechanical port path.
type Decimal32BID struct{ raw uint32 }

func Decimal32BIDFromBits(raw uint32) Decimal32BID { return Decimal32BID{raw: raw} }

// ToUint32 returns the raw 32-bit BID bit pattern.
func (d Decimal32BID) ToUint32() uint32 {
	return d.raw
}

// Decimal64BID is a 64-bit BID decimal routed through the Go mechanical port path.
type Decimal64BID struct{ raw uint64 }

func Decimal64BIDFromBits(raw uint64) Decimal64BID { return Decimal64BID{raw: raw} }

// ToUint64 returns the raw 64-bit BID bit pattern.
func (d Decimal64BID) ToUint64() uint64 {
	return d.raw
}

// Decimal128BID is a 128-bit BID decimal with 1:1 byte correspondence.
type Decimal128BID struct{ raw [16]byte }

func Decimal128BIDFromBytes(raw [16]byte) Decimal128BID { return Decimal128BID{raw: raw} }

// ToBytes returns the raw 128-bit BID bit pattern as 16 bytes.
func (d Decimal128BID) ToBytes() [16]byte {
	return d.raw
}
