// Code generated by testgen; DO NOT EDIT.
//go:build !cgo || !bid754_native

package bid754

import "fmt"

func nativeReadtestBID32FromString(input string, rounding int) (uint32, string) { return 0, "" }
func nativeReadtestBID64FromString(input string, rounding int) (uint64, string) { return 0, "" }
func nativeReadtestBID128FromString(input string, rounding int) ([16]byte, string) {
	return [16]byte{}, ""
}
func nativeReadtestBID32ToString(a uint32) (string, string)    { return "", "" }
func nativeReadtestBID64ToString(a uint64) (string, string)    { return "", "" }
func nativeReadtestBID128ToString(a [16]byte) (string, string) { return "", "" }
func nativeReadtestGeneratedBID32(function string, rounding int, operands []string) (uint32, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedBID64(function string, rounding int, operands []string) (uint64, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedBID128(function string, rounding int, operands []string) ([16]byte, string, error) {
	return [16]byte{}, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedSigned(function string, rounding int, operands []string) (int64, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedBinary32(function string, rounding int, operands []string) (uint32, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedBinary64(function string, rounding int, operands []string) (uint64, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedBinary128(function string, rounding int, operands []string) ([16]byte, string, error) {
	return [16]byte{}, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestGeneratedUnsigned(function string, rounding int, operands []string) (uint64, string, error) {
	return 0, "", fmt.Errorf("native readtest disabled")
}
func nativeReadtestBID32RoundIntegralExact(a uint32) uint32 { return 0 }
func nativeReadtestBID64RoundIntegralExact(a uint64) uint64 { return 0 }
