// Code generated by testgen; DO NOT EDIT.
//go:build !cgo || !bid754_native

package bid754

import "testing"

func TestGeneratedDectestSuites(t *testing.T) {
	t.Skip("generated dectest suites require cgo and bid754_native")
}
