// Code generated by testgen; DO NOT EDIT.
package bidgo

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"
)

// generatedBIDStringShardFiles lists the readtest shard files of every
// from_string/to_string suite, relative to generated/testspec, in
// generation order.
var generatedBIDStringShardFiles = []string{
	"readtest/bid64_from_string.json",
	"readtest/bid128_from_string.json",
	"readtest/bid64_to_string.json",
	"readtest/bid128_to_string.json",
	"readtest/bid32_to_string.json",
	"readtest/bid32_from_string.json",
	"readtest/bid32_from_string_ieee754_overflow_cdiverge.json",
	"readtest/bid32_from_string_ieee754_overflow_cmatch.json",
	"readtest/bid32_from_string_underflow_boundary_cmatch.json",
	"readtest/bid64_from_string_ieee754_overflow_cdiverge.json",
	"readtest/bid64_from_string_ieee754_overflow_cmatch.json",
	"readtest/bid128_from_string_ieee754_overflow_cmatch.json",
	"readtest/bid32_from_string_ieee754_exponent_cdiverge.json",
	"readtest/bid64_from_string_ieee754_exponent_cdiverge.json",
	"readtest/bid128_from_string_ieee754_exponent_cdiverge.json",
}

type generatedStringShard struct {
	Format   string                     `json:"format"`
	Function string                     `json:"function"`
	Kind     string                     `json:"kind"`
	Cases    []generatedStringShardCase `json:"cases"`
}

type generatedStringShardCase struct {
	ID       string   `json:"id"`
	Line     int      `json:"line"`
	Operands []string `json:"operands"`
	Expected string   `json:"expected"`
	Status   string   `json:"status"`
	Rounding int      `json:"rounding"`
}

type generatedStringReadCase struct {
	ID       string
	Line     int
	Format   string
	Function string
	Kind     string
	Operands []string
	Expected string
	Status   string
	Rounding int
}

type generatedBIDStringCounts struct {
	Total                int
	FromString           int
	ToString             int
	Decimal32            int
	Decimal64            int
	Decimal128           int
	Decimal32FromString  int
	Decimal64FromString  int
	Decimal128FromString int
	Decimal32ToString    int
	Decimal64ToString    int
	Decimal128ToString   int
}

var expectedGeneratedBIDStringCounts = generatedBIDStringCounts{
	Total:                354,
	FromString:           291,
	ToString:             63,
	Decimal32:            136,
	Decimal64:            101,
	Decimal128:           117,
	Decimal32FromString:  116,
	Decimal64FromString:  89,
	Decimal128FromString: 86,
	Decimal32ToString:    20,
	Decimal64ToString:    12,
	Decimal128ToString:   31,
}

func TestGeneratedBIDStringVectors(t *testing.T) {
	readCases := loadGeneratedBIDStringReadCases(t)
	var counts generatedBIDStringCounts
	for _, tc := range readCases {
		if tc.Kind != "from_string" && tc.Kind != "to_string" {
			continue
		}
		countGeneratedBIDStringCase(&counts, tc)
		t.Run(tc.ID, func(t *testing.T) {
			switch tc.Kind {
			case "from_string":
				gotBits, flags, err := generatedBIDStringFromString(tc)
				if err != nil {
					t.Fatalf("from_string dispatch: %v", err)
				}
				if strings.HasPrefix(strings.TrimSpace(tc.Expected), "[") {
					if normalizeGeneratedBIDStringBits(gotBits) != normalizeGeneratedBIDStringBits(tc.Expected) {
						t.Fatalf("%s line %d: bits got %s, want %s", tc.Function, tc.Line, gotBits, tc.Expected)
					}
				} else {
					equal, err := generatedBIDStringDecimalRowEqual(tc.Format, tc.Expected, gotBits, tc.Rounding)
					if err != nil {
						t.Fatalf("compare from_string decimal result: %v", err)
					}
					if !equal {
						t.Fatalf("%s line %d: bits got %s, want exact cohort parsed from %q", tc.Function, tc.Line, gotBits, tc.Expected)
					}
				}
				if normalizeGeneratedBIDStringStatus(flags) != normalizeGeneratedBIDStringStatus(tc.Status) {
					t.Fatalf("%s line %d: status got %s, want %s", tc.Function, tc.Line, normalizeGeneratedBIDStringStatus(flags), normalizeGeneratedBIDStringStatus(tc.Status))
				}
			case "to_string":
				got, flags, err := generatedBIDStringToString(tc)
				if err != nil {
					t.Fatalf("to_string dispatch: %v", err)
				}
				equal, roundTripStatus, err := generatedBIDStringToStringRowEqual(tc.Format, tc.Expected, got, tc.Rounding)
				if err != nil {
					t.Fatalf("compare to_string result: %v", err)
				}
				if !equal {
					t.Fatalf("%s line %d: got %q, want exact cohort parsed from %q", tc.Function, tc.Line, got, tc.Expected)
				}
				flags, err = combineGeneratedBIDStringStatus(flags, roundTripStatus)
				if err != nil {
					t.Fatalf("combine to_string status: %v", err)
				}
				if normalizeGeneratedBIDStringStatus(flags) != normalizeGeneratedBIDStringStatus(tc.Status) {
					t.Fatalf("%s line %d: status got %s, want %s", tc.Function, tc.Line, normalizeGeneratedBIDStringStatus(flags), normalizeGeneratedBIDStringStatus(tc.Status))
				}
			}
		})
	}
	if counts != expectedGeneratedBIDStringCounts {
		t.Fatalf("generated BID string read case counts changed: got %+v, want %+v", counts, expectedGeneratedBIDStringCounts)
	}
}

// TestGeneratedBIDStringToStringComparatorStrength anchors the generated
// comparator to Intel readtest.c: expected and produced strings are parsed by
// the backend at the row rounding mode and compared as exact BID cohorts, and
// flags from parsing the produced string are accumulated into operation flags.
func TestGeneratedBIDStringToStringComparatorStrength(t *testing.T) {
	equal, _, err := generatedBIDStringToStringRowEqual("decimal64", "+15E+0", "+150E-1", 0)
	if err != nil {
		t.Fatalf("wrong-cohort comparison: %v", err)
	}
	if equal {
		t.Fatal("wrong-cohort string accepted: +150E-1 must not match +15E+0")
	}

	equal, status, err := generatedBIDStringToStringRowEqual("decimal64", "15", "+15E+0", 0)
	if err != nil {
		t.Fatalf("exact-cohort spelling comparison: %v", err)
	}
	if !equal {
		t.Fatal("exact-cohort spelling variant rejected")
	}
	if normalizeGeneratedBIDStringStatus(status) != "00" {
		t.Fatalf("exact-cohort round-trip status = %q, want 00", status)
	}

	equal, status, err = generatedBIDStringToStringRowEqual("decimal64", "5000000000000000E-15", "5.0000000000000000001", 0)
	if err != nil {
		t.Fatalf("inexact round-trip comparison: %v", err)
	}
	if !equal {
		t.Fatal("inexact produced string did not round to the expected cohort")
	}
	if normalizeGeneratedBIDStringStatus(status) != "20" {
		t.Fatalf("inexact round-trip status = %q, want 20", status)
	}
	combined, err := combineGeneratedBIDStringStatus("01", status)
	if err != nil {
		t.Fatalf("combine status: %v", err)
	}
	if normalizeGeneratedBIDStringStatus(combined) != "21" {
		t.Fatalf("combined status = %q, want 21", combined)
	}
}

func countGeneratedBIDStringCase(counts *generatedBIDStringCounts, tc generatedStringReadCase) {
	counts.Total++
	switch tc.Kind {
	case "from_string":
		counts.FromString++
	case "to_string":
		counts.ToString++
	}
	switch tc.Format {
	case "decimal32":
		counts.Decimal32++
		if tc.Kind == "from_string" {
			counts.Decimal32FromString++
		} else {
			counts.Decimal32ToString++
		}
	case "decimal64":
		counts.Decimal64++
		if tc.Kind == "from_string" {
			counts.Decimal64FromString++
		} else {
			counts.Decimal64ToString++
		}
	case "decimal128":
		counts.Decimal128++
		if tc.Kind == "from_string" {
			counts.Decimal128FromString++
		} else {
			counts.Decimal128ToString++
		}
	}
}

func loadGeneratedBIDStringReadCases(t *testing.T) []generatedStringReadCase {
	t.Helper()
	_, currentFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("resolve generated string vector test path")
	}
	baseDir := filepath.Join(filepath.Dir(currentFile), "..", "..", "..", "devtools", "generated", "testspec")
	var readCases []generatedStringReadCase
	for _, shardFile := range generatedBIDStringShardFiles {
		path := filepath.Join(baseDir, filepath.FromSlash(shardFile))
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read string shard %q: %v", path, err)
		}
		var shard generatedStringShard
		if err := json.Unmarshal(data, &shard); err != nil {
			t.Fatalf("parse string shard %q: %v", path, err)
		}
		for _, tc := range shard.Cases {
			readCases = append(readCases, generatedStringReadCase{
				ID:       tc.ID,
				Line:     tc.Line,
				Format:   shard.Format,
				Function: shard.Function,
				Kind:     shard.Kind,
				Operands: tc.Operands,
				Expected: tc.Expected,
				Status:   tc.Status,
				Rounding: tc.Rounding,
			})
		}
	}
	return readCases
}

func generatedBIDStringFromString(tc generatedStringReadCase) (string, string, error) {
	if len(tc.Operands) != 1 {
		return "", "", fmt.Errorf("%s expects 1 operand, got %d", tc.Function, len(tc.Operands))
	}
	return generatedBIDStringParseValue(tc.Format, tc.Operands[0], tc.Rounding)
}

func generatedBIDStringParseValue(format, input string, rounding int) (string, string, error) {
	switch format {
	case "decimal32":
		got, flags := Bid32FromStringRaw(input, rounding)
		return fmt.Sprintf("[%08x]", got), fmt.Sprintf("%02X", flags), nil
	case "decimal64":
		got, flags := Bid64FromString(input, rounding)
		return fmt.Sprintf("[%016x]", got), fmt.Sprintf("%02X", flags), nil
	case "decimal128":
		got, flags := Bid128FromString(input, rounding)
		return formatGeneratedBIDStringBits128(got), fmt.Sprintf("%02X", flags), nil
	default:
		return "", "", fmt.Errorf("unsupported format %q", format)
	}
}

func generatedBIDStringToString(tc generatedStringReadCase) (string, string, error) {
	if len(tc.Operands) != 1 {
		return "", "", fmt.Errorf("%s expects 1 operand, got %d", tc.Function, len(tc.Operands))
	}
	switch tc.Format {
	case "decimal32":
		raw, err := parseGeneratedBIDStringUintBits(tc.Operands[0], 32)
		if err != nil {
			return "", "", err
		}
		return Bid32ToString(uint32(raw)), "00", nil
	case "decimal64":
		raw, err := parseGeneratedBIDStringUintBits(tc.Operands[0], 64)
		if err != nil {
			return "", "", err
		}
		return Bid64ToString(raw), "00", nil
	case "decimal128":
		raw, err := parseGeneratedBIDStringBits128(tc.Operands[0])
		if err != nil {
			return "", "", err
		}
		return Bid128ToString(raw), "00", nil
	default:
		return "", "", fmt.Errorf("unsupported format %q", tc.Format)
	}
}

func generatedBIDStringDecimalRowEqual(format, expected, gotBits string, rounding int) (bool, error) {
	expectedBits, _, err := generatedBIDStringParseValue(format, expected, rounding)
	if err != nil {
		return false, err
	}
	return normalizeGeneratedBIDStringBits(expectedBits) == normalizeGeneratedBIDStringBits(gotBits), nil
}

func generatedBIDStringToStringRowEqual(format, expected, got string, rounding int) (bool, string, error) {
	expectedBits, _, err := generatedBIDStringParseValue(format, expected, rounding)
	if err != nil {
		return false, "", err
	}
	gotBits, roundTripStatus, err := generatedBIDStringParseValue(format, got, rounding)
	if err != nil {
		return false, "", err
	}
	return normalizeGeneratedBIDStringBits(expectedBits) == normalizeGeneratedBIDStringBits(gotBits), roundTripStatus, nil
}

func combineGeneratedBIDStringStatus(a, b string) (string, error) {
	flagsA, err := strconv.ParseUint(normalizeGeneratedBIDStringStatus(a), 16, 32)
	if err != nil {
		return "", fmt.Errorf("parse status %q: %w", a, err)
	}
	flagsB, err := strconv.ParseUint(normalizeGeneratedBIDStringStatus(b), 16, 32)
	if err != nil {
		return "", fmt.Errorf("parse status %q: %w", b, err)
	}
	return fmt.Sprintf("%02X", uint32(flagsA|flagsB)), nil
}

func parseGeneratedBIDStringUintBits(input string, bits int) (uint64, error) {
	trimmed := strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(input), "["), "]")
	trimmed = strings.ReplaceAll(trimmed, ",", "")
	return strconv.ParseUint(trimmed, 16, bits)
}

func parseGeneratedBIDStringBits128(input string) (BID_UINT128, error) {
	var raw BID_UINT128
	literal := strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(input), "["), "]")
	var hiText, loText string
	if strings.Contains(literal, ",") {
		parts := strings.SplitN(literal, ",", 2)
		hiText = strings.TrimSpace(parts[0])
		loText = strings.TrimSpace(parts[1])
	} else {
		compact := strings.ReplaceAll(literal, ",", "")
		if len(compact) > 32 || len(compact) <= 16 {
			return raw, fmt.Errorf("invalid 128-bit hex literal %q", input)
		}
		hiText = compact[:16]
		loText = compact[16:]
	}
	hi, err := strconv.ParseUint(hiText, 16, 64)
	if err != nil {
		return raw, err
	}
	lo, err := strconv.ParseUint(loText, 16, 64)
	if err != nil {
		return raw, err
	}
	raw.lo = lo
	raw.hi = hi
	return raw, nil
}

func formatGeneratedBIDStringBits128(raw BID_UINT128) string {
	return fmt.Sprintf("[%016x%016x]", raw.hi, raw.lo)
}

func normalizeGeneratedBIDStringBits(input string) string {
	trimmed := strings.ToLower(strings.TrimSpace(input))
	trimmed = strings.TrimSuffix(strings.TrimPrefix(trimmed, "["), "]")
	trimmed = strings.ReplaceAll(trimmed, ",", "")
	trimmed = strings.TrimLeft(trimmed, "0")
	if trimmed == "" {
		trimmed = "0"
	}
	return "[" + trimmed + "]"
}

func normalizeGeneratedBIDStringStatus(input string) string {
	trimmed := strings.ToUpper(strings.TrimSpace(input))
	trimmed = strings.TrimPrefix(trimmed, "0X")
	if trimmed == "" {
		return "00"
	}
	if len(trimmed)%2 != 0 {
		trimmed = "0" + trimmed
	}
	return trimmed
}

func TestGeneratedParserExponentCancellationRegression(t *testing.T) {
	type expCancelCase struct {
		id       string
		width    int
		neg      bool
		fracZeros int
		expLZ    int
		expMag   int
		integerZeros int
		hi, lo   uint64
	}
	cases := []expCancelCase{
		{"d32_q0_short", 32, false, 4, 0, 5, 0, 0x0, 0x32800001},
		{"d64_q0_short", 64, false, 4, 0, 5, 0, 0x0, 0x31c0000000000001},
		{"d128_q0_short", 128, false, 4, 0, 5, 0, 0x3040000000000000, 0x1},
		{"d128_q0_short_neg", 128, true, 4, 0, 5, 0, 0xb040000000000000, 0x1},
		{"d128_lz0_7dig", 128, false, 999999, 0, 1000000, 0, 0x3040000000000000, 0x1},
		{"d128_lz1_7dig_confirmed", 128, false, 999999, 1, 1000000, 0, 0x3040000000000000, 0x1},
		{"d128_lz2_7dig", 128, false, 999999, 2, 1000000, 0, 0x3040000000000000, 0x1},
		{"d32_n10485760", 32, false, 10485759, 0, 10485760, 0, 0x0, 0x32800001},
		{"d64_n10485760", 64, false, 10485759, 0, 10485760, 0, 0x0, 0x31c0000000000001},
		{"d128_n10485760", 128, false, 10485759, 0, 10485760, 0, 0x3040000000000000, 0x1},
		{"d32_neighbor_999999", 32, false, 999998, 0, 999999, 0, 0x0, 0x32800001},
		{"d32_neighbor_9999999", 32, false, 9999998, 0, 9999999, 0, 0x0, 0x32800001},
		{"d32_neighbor_10000000", 32, false, 9999999, 0, 10000000, 0, 0x0, 0x32800001},
		{"d32_neighbor_10485759", 32, false, 10485758, 0, 10485759, 0, 0x0, 0x32800001},
		{"d32_neighbor_10485761", 32, false, 10485760, 0, 10485761, 0, 0x0, 0x32800001},
		{"d32_negative_1000000", 32, true, 999999, 1, 1000000, 0, 0x0, 0xb2800001},
		{"d32_integer_1000000_negative_false", 32, false, 0, 1, -1000000, 1000000, 0x0, 0x2f8f4240},
		{"d32_integer_1000000_negative_true", 32, true, 0, 1, -1000000, 1000000, 0x0, 0xaf8f4240},
		{"d32_negative_10485760", 32, true, 10485759, 1, 10485760, 0, 0x0, 0xb2800001},
		{"d32_integer_10485760_negative_false", 32, false, 0, 1, -10485760, 10485760, 0x0, 0x2f8f4240},
		{"d32_integer_10485760_negative_true", 32, true, 0, 1, -10485760, 10485760, 0x0, 0xaf8f4240},
		{"d32_quantum_-101", 32, false, 1000100, 1, 1000000, 0, 0x0, 0x1},
		{"d32_quantum_90", 32, false, 999909, 1, 1000000, 0, 0x0, 0x5f800001},
		{"d64_neighbor_999999", 64, false, 999998, 0, 999999, 0, 0x0, 0x31c0000000000001},
		{"d64_neighbor_9999999", 64, false, 9999998, 0, 9999999, 0, 0x0, 0x31c0000000000001},
		{"d64_neighbor_10000000", 64, false, 9999999, 0, 10000000, 0, 0x0, 0x31c0000000000001},
		{"d64_neighbor_10485759", 64, false, 10485758, 0, 10485759, 0, 0x0, 0x31c0000000000001},
		{"d64_neighbor_10485761", 64, false, 10485760, 0, 10485761, 0, 0x0, 0x31c0000000000001},
		{"d64_negative_1000000", 64, true, 999999, 1, 1000000, 0, 0x0, 0xb1c0000000000001},
		{"d64_integer_1000000_negative_false", 64, false, 0, 1, -1000000, 1000000, 0x0, 0x2fe38d7ea4c68000},
		{"d64_integer_1000000_negative_true", 64, true, 0, 1, -1000000, 1000000, 0x0, 0xafe38d7ea4c68000},
		{"d64_negative_10485760", 64, true, 10485759, 1, 10485760, 0, 0x0, 0xb1c0000000000001},
		{"d64_integer_10485760_negative_false", 64, false, 0, 1, -10485760, 10485760, 0x0, 0x2fe38d7ea4c68000},
		{"d64_integer_10485760_negative_true", 64, true, 0, 1, -10485760, 10485760, 0x0, 0xafe38d7ea4c68000},
		{"d64_quantum_-398", 64, false, 1000397, 1, 1000000, 0, 0x0, 0x1},
		{"d64_quantum_369", 64, false, 999630, 1, 1000000, 0, 0x0, 0x5fe0000000000001},
		{"d128_neighbor_999999", 128, false, 999998, 0, 999999, 0, 0x3040000000000000, 0x1},
		{"d128_neighbor_9999999", 128, false, 9999998, 0, 9999999, 0, 0x3040000000000000, 0x1},
		{"d128_neighbor_10000000", 128, false, 9999999, 0, 10000000, 0, 0x3040000000000000, 0x1},
		{"d128_neighbor_10485759", 128, false, 10485758, 0, 10485759, 0, 0x3040000000000000, 0x1},
		{"d128_neighbor_10485761", 128, false, 10485760, 0, 10485761, 0, 0x3040000000000000, 0x1},
		{"d128_negative_1000000", 128, true, 999999, 1, 1000000, 0, 0xb040000000000000, 0x1},
		{"d128_integer_1000000_negative_false", 128, false, 0, 1, -1000000, 1000000, 0x2ffe314dc6448d93, 0x38c15b0a00000000},
		{"d128_integer_1000000_negative_true", 128, true, 0, 1, -1000000, 1000000, 0xaffe314dc6448d93, 0x38c15b0a00000000},
		{"d128_negative_10485760", 128, true, 10485759, 1, 10485760, 0, 0xb040000000000000, 0x1},
		{"d128_integer_10485760_negative_false", 128, false, 0, 1, -10485760, 10485760, 0x2ffe314dc6448d93, 0x38c15b0a00000000},
		{"d128_integer_10485760_negative_true", 128, true, 0, 1, -10485760, 10485760, 0xaffe314dc6448d93, 0x38c15b0a00000000},
		{"d128_quantum_-6176", 128, false, 1006175, 1, 1000000, 0, 0x0, 0x1},
		{"d128_quantum_6111", 128, false, 993888, 1, 1000000, 0, 0x5ffe000000000000, 0x1},
	}
	build := func(c expCancelCase) string {
		var sb strings.Builder
		if c.neg {
			sb.WriteByte('-')
		}

        if c.integerZeros > 0 {
            sb.WriteByte('1')
            sb.WriteString(strings.Repeat("0", c.integerZeros))
            sb.WriteByte('e')
        } else {
            sb.WriteString("0.")
            sb.WriteString(strings.Repeat("0", c.fracZeros))
            sb.WriteString("1e+")
        }
        exp := c.expMag
        if exp < 0 { sb.WriteByte('-'); exp = -exp }
        sb.WriteString(strings.Repeat("0", c.expLZ))
        sb.WriteString(strconv.Itoa(exp))
		return sb.String()
	}
	modes := []int{BID_ROUNDING_TO_NEAREST, BID_ROUNDING_DOWN, BID_ROUNDING_UP, BID_ROUNDING_TO_ZERO, BID_ROUNDING_TIES_AWAY}
	for _, c := range cases {
		s := build(c)
		for _, m := range modes {
			var hi, lo uint64
			var fl uint32
			switch c.width {
			case 32:
				b, f := Bid32FromStringRaw(s, m)
				hi, lo, fl = 0, uint64(b), f
			case 64:
				b, f := Bid64FromString(s, m)
				hi, lo, fl = 0, b, f
			default:
				r, f := Bid128FromString(s, m)
				hi, lo = Bid128Words(r)
				fl = f
			}
			if hi != c.hi || lo != c.lo || fl != 0 {
				t.Errorf("%s mode=%d: got %#x,%#x fl=%#x; want exact cohort %#x,%#x fl=0", c.id, m, hi, lo, fl, c.hi, c.lo)
			}
		}
	}
}
