package apiemit

import (
	"fmt"
	"os"
	"strings"
)

// crateAllowAttr is the crate-level lint allowance the generated implementation
// and compat modules rely on. It is kept at the crate root rather than duplicated onto each module
// declaration, because several generated modules (e.g. tables.rs) already carry
// their own inner allow of a subset of these lints, and a second allow of the
// same lint on the same module is a clippy::duplicated_attributes warning.
//
// The public API surface is NOT left covered by this allowance: the api module
// re-tightens it with `#![forbid(unsafe_code)]` and
// `#![deny(arithmetic_overflow, overflowing_literals)]` (a module-level deny
// overrides a crate-level allow), which is the stronger, explicitly verified form
// of the "keep the overflow allow off the public surface" rule
// (devtools/scripts/verify_rust_overflow_policy.sh checks both halves).
const crateAllowAttr = `#![allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unused_mut,
    unused_parens,
    unused_variables,
    dead_code,
    unused_assignments,
    unused_imports,
    arithmetic_overflow,
    overflowing_literals
)]`

// internalModules are the generated/compat modules re-exported for repository
// integration tests, benches, and generated verification harnesses. They are
// doc(hidden) non-stable surface, not part of the semver contract. Order is
// fixed for byte-reproducibility.
var internalModules = []string{"gen_types", "gen_constants", "tables", "generated", "bid_codec"}

// emitLibRs writes the crate root as a generated artifact: it re-exports the
// generated public API and keeps the internal modules as doc(hidden) compat
// surface.
func emitLibRs(path string) error {
	if err := os.WriteFile(path, []byte(buildLibRs()), 0o644); err != nil {
		return fmt.Errorf("apiemit: write crate root %q: %w", path, err)
	}
	return nil
}

func buildLibRs() string {
	var b strings.Builder
	b.WriteString(marker() + crlf)
	b.WriteString(`//! # bid754
//!
//! IEEE 754-2019 decimal floating-point (BID encoding), generated from the Go
//! mechanical port of Intel BID C.
//!
//! The public API is generated by ` + "`devtools/tools/go2rs/apiemit`" + ` and re-exported
//! here at the crate root: the fixed-width value types (` + "`Decimal32`" + `,
//! ` + "`Decimal64`" + `, ` + "`Decimal128`" + `), the exception-flag, rounding-mode, class, and
//! context types, the ` + "`ZERO`/`ONE`/`PI`/`E`" + ` constants, and the wrapper
//! methods that route through the generated port. All three widths expose the
//! full operation surface (arithmetic and its flag-carrying pairs, comparison,
//! conversion, rounding, and the IEEE-quiet ` + "`PartialEq`/`PartialOrd`" + `
//! operators).
//!
//! The ` + "`gen_types`" + `, ` + "`gen_constants`" + `, ` + "`tables`" + `, ` + "`generated`" + `, and ` + "`bid_codec`" + `
//! modules are ` + "`#[doc(hidden)]`" + ` non-stable compatibility surface: they exist so
//! repository integration tests, benches, and generated verification harnesses
//! can call the generated implementation directly. Do not depend on them as a
//! semver contract.
//!
//! Standalone BID component encode/decode helpers live in the separate
//! ` + "`bid754-codec-rs`" + ` crate; the ` + "`bid_codec`" + ` module embedded here only backs
//! this crate's generated vector verification path.

`)
	// Crate-level allowance for the generated implementation/compat modules. The
	// public API module (generated::api) re-denies the overflow lints and forbids
	// unsafe, so this does not relax the public surface.
	b.WriteString(crateAllowAttr + crlf)
	b.WriteString(crlf)
	b.WriteString("// Public API surface (generated by devtools/tools/go2rs/apiemit)." + crlf)
	b.WriteString("pub use generated::api::*;" + crlf)
	b.WriteString(crlf)
	b.WriteString("// Non-stable internal compatibility surface (doc(hidden))." + crlf)
	for _, mod := range internalModules {
		b.WriteString("#[doc(hidden)]" + crlf)
		b.WriteString("pub mod " + mod + ";" + crlf)
	}
	b.WriteString(crlf)
	b.WriteString(`/// Non-stable raw parse entrypoint kept for the generated bid_string_vectors
/// harness and the repo benches, which need the explicit-rounding, raw
/// bits-and-flags port form (the public ` + "`Decimal64::parse_raw`" + ` uses default
/// rounding and typed results). Not part of the stable public API.
#[doc(hidden)]
pub fn bid64_from_string_raw(s: impl AsRef<str>, rnd_mode: i32) -> (u64, u32) {
    generated::bid64_from_string::bid64_from_string(s, i64::from(rnd_mode))
}
`)
	return b.String()
}
