// Package publicroute is the static half of the public-API routing gate: it
// enforces, outside the generation path (portprovenance-style: hand-written,
// exhaustive, unused entries fail), that the checked-in public-API routing
// inventory stays faithful to the source and that every public wrapper actually
// routes through the Go mechanical port.
//
// Four checks, each exhaustive:
//
//  1. Census re-validation: the symbol set recorded in the checked-in
//     public_api_routing_inventory.json equals the exported func/method/var set of
//     the module-root package `bid754` read independently from source (both
//     directions). A hand commit that adds or removes a public symbol without
//     regenerating the inventory, or an inconsistent inventory edit, fails here.
//
//  2. Inventory->shim agreement: for every mapped symbol, the FULL set of port
//     functions reachable from the wrapper's body through the package-level Go
//     plumbing (method -> ...Port helper -> bidgo.Fn) is compared exactly. A
//     simple wrapper's reachable set must be exactly the singleton of the port
//     function the inventory records; a composed wrapper (mode dispatch, predicate
//     composition, checked constructors) must match its pinned complete
//     callee set exactly AND the inventory's representative function is pinned per
//     entry, so changing either the shim or the inventory representative fails.
//
//  3. Chain cross-check (FM9 connection guarantee): every port function any
//     mapped wrapper actually reaches (the full reachable set, not just the
//     inventory representative) must be exercised by a regular verification
//     domain under its EXACT Go name: the goport readtest dispatch inventory's
//     go_function set, or the bidgo functions the generated FFI bit-compare
//     artifact literally calls. A reachable function absent from both must
//     either be machine-proven variant-equivalent to a surface sibling by
//     bidgo body structure (the base calls the surface WithFlags sibling, the
//     surface sibling calls the base, or both delegate to the same single
//     value-path function), or be covered by the dedicated flagless-variant
//     equivalence gate. There is no silent name normalization: variant
//     equivalence is proven, not assumed.
//
//  4. FM7 native-path check: no file on the public runtime path (a
//     non-test root file that participates in the default build, i.e. does not
//     require the bid754_native tag) may `import "C"` or reference a
//     native-only symbol. The set of cgo files is pinned exhaustively so a new
//     cgo file must justify itself and stay gated out of the public build. As a
//     strict corroborator this check also loads the typed public build, so
//     a public file that references a native-only symbol (undefined in Config A)
//     fails the type-check, not just the AST name scan.
//
// Resolution boundary (what is semantic vs syntactic):
//
//   - Checks 2 and 3 resolve identifiers and calls by go/types OBJECT IDENTITY
//     (typedload_test.go): reachability edge-following, bidgo-call detection,
//     bidgo body-callee resolution, and the variant-equivalence value flow all
//     key off resolved *types.Func objects over the Config A public build and
//     the bidgo package type-checked from source. Import aliases, unrelated
//     package aliases, package-function-name shadowing, and same-named locals
//     in bidgo bodies therefore cannot pass. The resolver identity corpus
//     (resolver_identity_corpus_test.go) pins this closure.
//   - Checks 1 and 4 stay go/ast on purpose: census is declaration ENUMERATION
//     (identifier resolution is not involved, and it must union symbols across
//     build-tag variants go/types checks one configuration at a time); the cgo
//     cgo and native-only-symbol checks operate on files that `import "C"`, which
//     go/types cannot type-check from source.
//   - Bounded structural residuals (reported as residual, not "verified by
//     types"): the FFI-surface extraction stays AST and is bounded by
//     verify-generated byte pins; the flagless-variant equivalence gate pair
//     extraction reads a bidgo external test package and stays AST; a value
//     passed through unsafe.Pointer bit reinterpretation has no call/method
//     object and is opaque to both AST and go/types, the same accepted residual
//     the value-flow tracker documents.
package publicroute

import (
	"encoding/json"
	"go/ast"
	"go/build/constraint"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

const (
	publicSrcDirRel    = "../../../bid754-go"
	bidgoDirRel        = "../../../bid754-go/internal/bidgo"
	inventoryPathRel   = "../../generated/testspec/public_api_routing_inventory.json"
	goportInventoryRel = "../../generated/testspec/goport_readtest_dispatch_inventory.json"
	// ffiBitcompareRel is the generated FFI bit-compare artifact; the bidgo
	// functions it literally calls are the FFI domain's Go-side surface. The
	// spec file names under generated/testspec/ffi are C spellings and would
	// require a silent name normalization, so they are not used here.
	ffiBitcompareRel = "../../../bid754-go/generated_ffi_bitcompare_native.go"
	// equivalenceGateFileRel is the hand-written flagless-variant equivalence
	// gate inside the bidgo package; check 3 verifies by AST that every
	// sibling-equivalence-covered function is actually pinned there as a
	// {flagless, WithFlags} pair.
	equivalenceGateFileRel = "../../../bid754-go/internal/bidgo/flagless_variant_equivalence_test.go"
)

var equivalenceGateTargetVarNames = []string{
	"flaglessVariantEquivalenceTargets32",
	"flaglessVariantEquivalenceTargets64",
}

// valueTypeWidths maps the module-root value receiver types to their bidgo
// width prefix; method symbols on them are keyed "Recv.Method" in both the
// inventory and the independent source census.
var valueTypeWidths = map[string]string{
	"Decimal32BID":  "32",
	"Decimal64BID":  "64",
	"Decimal128BID": "128",
}

// ---------------------------------------------------------------------------
// Shared loaders
// ---------------------------------------------------------------------------

type inventoryRow struct {
	Symbol        string `json:"symbol"`
	Kind          string `json:"kind"`
	Status        string `json:"status"`
	BidgoFunction string `json:"bidgo_function"`
	Reason        string `json:"reason"`
}

type inventoryDoc struct {
	Total    int            `json:"total"`
	Mapped   int            `json:"mapped"`
	Excluded int            `json:"excluded"`
	Symbols  []inventoryRow `json:"symbols"`
}

func loadInventory(t *testing.T) inventoryDoc {
	t.Helper()
	raw, err := os.ReadFile(inventoryPathRel)
	if err != nil {
		t.Fatalf("read %s: %v", inventoryPathRel, err)
	}
	var doc inventoryDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal %s: %v", inventoryPathRel, err)
	}
	if len(doc.Symbols) == 0 {
		t.Fatalf("%s contains no symbols", inventoryPathRel)
	}
	return doc
}

// rootGoFiles returns the base names of the non-test .go files directly under
// the bid754-go module root (the public package `bid754`). Generated files are
// included: a generated artifact that exports a symbol widens the public
// surface just like a hand-written one.
func rootGoFiles(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(publicSrcDirRel)
	if err != nil {
		t.Fatalf("read %s: %v", publicSrcDirRel, err)
	}
	var files []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		files = append(files, name)
	}
	sort.Strings(files)
	if len(files) == 0 {
		t.Fatalf("no non-test .go files found under %s", publicSrcDirRel)
	}
	return files
}

func parseRootFile(t *testing.T, name string) *ast.File {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filepath.Join(publicSrcDirRel, name), nil, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	return file
}

func receiverTypeName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	expr := recv.List[0].Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}

// ---------------------------------------------------------------------------
// Build-constraint helpers (public runtime path vs bid754_native oracle path)
// ---------------------------------------------------------------------------

func fileBuildConstraint(t *testing.T, file *ast.File) constraint.Expr {
	t.Helper()
	for _, cg := range file.Comments {
		if cg.Pos() >= file.Package {
			continue
		}
		for _, c := range cg.List {
			if constraint.IsGoBuild(c.Text) {
				expr, err := constraint.Parse(c.Text)
				if err != nil {
					t.Fatalf("parse build constraint %q: %v", c.Text, err)
				}
				return expr
			}
		}
	}
	return nil
}

// requiresNative reports whether a file is gated behind the bid754_native build
// tag: it is compiled when bid754_native is set (all other tags satisfied) but
// not when bid754_native is off. Such files are the native oracle/benchmark
// path, excluded from the public runtime build. A file with no constraint, or
// one that still compiles with bid754_native off, is on the public runtime path.
func requiresNative(expr constraint.Expr) bool {
	if expr == nil {
		return false
	}
	nativeOff := func(tag string) bool { return tag != "bid754_native" }
	allOn := func(string) bool { return true }
	return !expr.Eval(nativeOff) && expr.Eval(allOn)
}

// ---------------------------------------------------------------------------
// Check 1: census re-validation
// ---------------------------------------------------------------------------

// sourceExportedSymbols reads the exported functions, methods, and package
// variables of the module-root package `bid754` directly from source, mirroring
// the generator's loadPublicAPISigs population (all non-test files, generated
// included, build tags ignored so native and stub variants collapse to one
// entry). Reimplemented here independently so the comparison against the inventory
// is a real cross-check, not a shared-code tautology.
func sourceExportedSymbols(t *testing.T) map[string]string {
	t.Helper()
	symbols := map[string]string{}
	for _, name := range rootGoFiles(t) {
		file := parseRootFile(t, name)
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if !d.Name.IsExported() {
					continue
				}
				if d.Recv == nil {
					symbols[d.Name.Name] = "func"
					continue
				}
				recv := receiverTypeName(d.Recv)
				if recv == "" {
					t.Fatalf("%s: cannot resolve receiver type for method %q", name, d.Name.Name)
				}
				symbols[recv+"."+d.Name.Name] = "method"
			case *ast.GenDecl:
				if d.Tok != token.VAR {
					continue
				}
				for _, spec := range d.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for _, ident := range vs.Names {
						if ident.IsExported() {
							symbols[ident.Name] = "var"
						}
					}
				}
			}
		}
	}
	if len(symbols) == 0 {
		t.Fatal("no exported public symbols found in source; wrong path?")
	}
	return symbols
}

func TestPublicAPIInventoryMatchesSourceCensus(t *testing.T) {
	inventory := loadInventory(t)
	source := sourceExportedSymbols(t)

	inventorySymbols := map[string]string{}
	for _, row := range inventory.Symbols {
		if _, dup := inventorySymbols[row.Symbol]; dup {
			t.Errorf("inventory lists symbol %q more than once", row.Symbol)
		}
		inventorySymbols[row.Symbol] = row.Kind
	}

	// Source symbols missing from the inventory require regeneration.
	for sym, kind := range source {
		inventoryKind, ok := inventorySymbols[sym]
		if !ok {
			t.Errorf("exported source symbol %q (%s) is absent from the routing inventory; regenerate public_api_routing_inventory.json", sym, kind)
			continue
		}
		if inventoryKind != kind {
			t.Errorf("symbol %q kind mismatch: source=%s inventory=%s", sym, kind, inventoryKind)
		}
	}
	// Inventory symbols missing from source also require regeneration.
	for sym, kind := range inventorySymbols {
		if _, ok := source[sym]; !ok {
			t.Errorf("routing inventory lists symbol %q (%s) that no longer exists in source; regenerate public_api_routing_inventory.json", sym, kind)
		}
	}
	if inventory.Total != len(inventorySymbols) {
		t.Errorf("inventory total field = %d but it lists %d distinct symbols", inventory.Total, len(inventorySymbols))
	}
}

// ---------------------------------------------------------------------------
// Shared helper
// ---------------------------------------------------------------------------
//
// The public-runtime call graph that checks 2 and 3 walk is resolved by
// go/types object identity in typedload_test.go (routeResolver): reachability,
// bidgo-call detection, and bidgo body-callee resolution all key off resolved
// objects, not identifier text. The resolver identity corpus
// (resolver_identity_corpus_test.go) pins the alias, unrelated-package,
// shadowing, and foreign-receiver cases the retired go/ast name-based resolvers
// missed.

func sortedSet(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------------------
// Check 2: inventory -> shim agreement (exact reachable-set comparison)
// ---------------------------------------------------------------------------

// composedValueMethodCallees pins the complete width-independent
// bidgo callee set of every value-type method whose shim is NOT a single-port
// delegation, together with the inventory's expected representative. Every other
// mapped value-type method is "simple": its reachable set must be exactly the
// singleton {inventory bidgo_function}. Entries here must actually be composed
// (a pinned set of at least two port functions) and must be exercised by at
// least one width; a stale or reasonless entry fails.
var composedValueMethodCallees = map[string]struct {
	Ops         []string // expected callees as Bid<width>+op, exact set
	InventoryOp string   // inventory bidgo_function must be Bid<width>+InventoryOp
	Reason      string
}{
	// The public rounding-mode parameter dispatches across the five per-mode
	// Intel port entrypoints; the inventory records the round-to-nearest-even
	// representative (the same representative the census mode_dispatch
	// override family validates).
	"ConvertToInt8":        {Ops: []string{"ToInt8Ceil", "ToInt8Floor", "ToInt8Int", "ToInt8Rnint", "ToInt8Rninta"}, InventoryOp: "ToInt8Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int8 ports; RN representative in the inventory"},
	"ConvertToInt8Exact":   {Ops: []string{"ToInt8Xceil", "ToInt8Xfloor", "ToInt8Xint", "ToInt8Xrnint", "ToInt8Xrninta"}, InventoryOp: "ToInt8Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int8 exact (X) ports; RN representative in the inventory"},
	"ConvertToInt16":       {Ops: []string{"ToInt16Ceil", "ToInt16Floor", "ToInt16Int", "ToInt16Rnint", "ToInt16Rninta"}, InventoryOp: "ToInt16Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int16 ports; RN representative in the inventory"},
	"ConvertToInt16Exact":  {Ops: []string{"ToInt16Xceil", "ToInt16Xfloor", "ToInt16Xint", "ToInt16Xrnint", "ToInt16Xrninta"}, InventoryOp: "ToInt16Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int16 exact (X) ports; RN representative in the inventory"},
	"ConvertToInt32":       {Ops: []string{"ToInt32Ceil", "ToInt32Floor", "ToInt32Int", "ToInt32Rnint", "ToInt32Rninta"}, InventoryOp: "ToInt32Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int32 ports; RN representative in the inventory"},
	"ConvertToInt32Exact":  {Ops: []string{"ToInt32Xceil", "ToInt32Xfloor", "ToInt32Xint", "ToInt32Xrnint", "ToInt32Xrninta"}, InventoryOp: "ToInt32Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int32 exact (X) ports; RN representative in the inventory"},
	"ConvertToInt64":       {Ops: []string{"ToInt64Ceil", "ToInt64Floor", "ToInt64Int", "ToInt64Rnint", "ToInt64Rninta"}, InventoryOp: "ToInt64Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int64 ports; RN representative in the inventory"},
	"ConvertToInt64Exact":  {Ops: []string{"ToInt64Xceil", "ToInt64Xfloor", "ToInt64Xint", "ToInt64Xrnint", "ToInt64Xrninta"}, InventoryOp: "ToInt64Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_int64 exact (X) ports; RN representative in the inventory"},
	"ConvertToUint8":       {Ops: []string{"ToUint8Ceil", "ToUint8Floor", "ToUint8Int", "ToUint8Rnint", "ToUint8Rninta"}, InventoryOp: "ToUint8Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint8 ports; RN representative in the inventory"},
	"ConvertToUint8Exact":  {Ops: []string{"ToUint8Xceil", "ToUint8Xfloor", "ToUint8Xint", "ToUint8Xrnint", "ToUint8Xrninta"}, InventoryOp: "ToUint8Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint8 exact (X) ports; RN representative in the inventory"},
	"ConvertToUint16":      {Ops: []string{"ToUint16Ceil", "ToUint16Floor", "ToUint16Int", "ToUint16Rnint", "ToUint16Rninta"}, InventoryOp: "ToUint16Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint16 ports; RN representative in the inventory"},
	"ConvertToUint16Exact": {Ops: []string{"ToUint16Xceil", "ToUint16Xfloor", "ToUint16Xint", "ToUint16Xrnint", "ToUint16Xrninta"}, InventoryOp: "ToUint16Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint16 exact (X) ports; RN representative in the inventory"},
	"ConvertToUint32":      {Ops: []string{"ToUint32Ceil", "ToUint32Floor", "ToUint32Int", "ToUint32Rnint", "ToUint32Rninta"}, InventoryOp: "ToUint32Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint32 ports; RN representative in the inventory"},
	"ConvertToUint32Exact": {Ops: []string{"ToUint32Xceil", "ToUint32Xfloor", "ToUint32Xint", "ToUint32Xrnint", "ToUint32Xrninta"}, InventoryOp: "ToUint32Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint32 exact (X) ports; RN representative in the inventory"},
	"ConvertToUint64":      {Ops: []string{"ToUint64Ceil", "ToUint64Floor", "ToUint64Int", "ToUint64Rnint", "ToUint64Rninta"}, InventoryOp: "ToUint64Rnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint64 ports; RN representative in the inventory"},
	"ConvertToUint64Exact": {Ops: []string{"ToUint64Xceil", "ToUint64Xfloor", "ToUint64Xint", "ToUint64Xrnint", "ToUint64Xrninta"}, InventoryOp: "ToUint64Xrnint", Reason: "RoundingMode parameter dispatches over the five per-mode to_uint64 exact (X) ports; RN representative in the inventory"},

	"Sign":              {Ops: []string{"IsSigned", "IsZero"}, InventoryOp: "IsSigned", Reason: "Sign() composes the zero predicate (returns 0 for zeros) with the sign predicate (+1/-1); the inventory records the sign predicate as the representative"},
	"SignalingEqual":    {Ops: []string{"SignalingGreaterEqual", "SignalingLessEqual"}, InventoryOp: "SignalingGreaterEqual", Reason: "signaling equality is composed as (x>=y) && (x<=y) over the two signaling comparison ports; the inventory records the greater-equal port as the representative"},
	"SignalingNotEqual": {Ops: []string{"SignalingGreaterEqual", "SignalingLessEqual"}, InventoryOp: "SignalingGreaterEqual", Reason: "negation of the composed signaling equality, reaching the same two signaling comparison ports; same representative as SignalingEqual"},
}

// composedPackageFuncCallees pins the complete bidgo callee set of
// every mapped package-level function whose body is NOT a single-port
// delegation. InventoryFnIsContract marks the string-route int constructors whose
// inventory bidgo_function is a parity value contract (result must equal the
// from-int port at RN) rather than a literal callee; for those the inventory
// function must NOT be reachable (if it becomes the literal callee the entry
// is stale). For all other entries the inventory function is pinned exactly.
var composedPackageFuncCallees = map[string]struct {
	Callees               []string
	InventoryFn           string // required inventory bidgo_function (when not a contract)
	InventoryFnIsContract bool
	Reason                string
}{
	"NewDecimal32":           {Callees: []string{"Bid32FromStringRaw", "Bid32IsNaN"}, InventoryFn: "Bid32FromStringRaw", Reason: "string constructor routes through the port parser; Bid32IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal32BIDDirect":  {Callees: []string{"Bid32FromStringRaw", "Bid32IsNaN"}, InventoryFn: "Bid32FromStringRaw", Reason: "string constructor routes through the port parser; Bid32IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal32WithFlags":  {Callees: []string{"Bid32FromStringRaw", "Bid32IsNaN"}, InventoryFn: "Bid32FromStringRaw", Reason: "flags-returning string constructor over the port parser; Bid32IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal32WithMode":   {Callees: []string{"Bid32FromStringRaw", "Bid32IsNaN"}, InventoryFn: "Bid32FromStringRaw", Reason: "explicit-rounding-mode string constructor over the port parser (the caller's mode replaces the default ties-to-even); Bid32IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"ParseDecimal32BIDRaw":   {Callees: []string{"Bid32FromStringRaw", "Bid32IsNaN"}, InventoryFn: "Bid32FromStringRaw", Reason: "flag-returning raw parser routes through the port parser; Bid32IsNaN distinguishes malformed text silently mapped to NaN so the public flag channel can report InvalidOperation"},
	"NewDecimal64":           {Callees: []string{"Bid64FromString", "Bid64IsNaN"}, InventoryFn: "Bid64FromString", Reason: "string constructor routes through the port parser; Bid64IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal64BIDDirect":  {Callees: []string{"Bid64FromString", "Bid64IsNaN"}, InventoryFn: "Bid64FromString", Reason: "string constructor routes through the port parser; Bid64IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal64WithFlags":  {Callees: []string{"Bid64FromString", "Bid64IsNaN"}, InventoryFn: "Bid64FromString", Reason: "flags-returning string constructor over the port parser; Bid64IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal64WithMode":   {Callees: []string{"Bid64FromString", "Bid64IsNaN"}, InventoryFn: "Bid64FromString", Reason: "explicit-rounding-mode string constructor over the port parser (the caller's mode replaces the default ties-to-even); Bid64IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"ParseDecimal64BIDRaw":   {Callees: []string{"Bid64FromString", "Bid64IsNaN"}, InventoryFn: "Bid64FromString", Reason: "flag-returning raw parser routes through the port parser; Bid64IsNaN distinguishes malformed text silently mapped to NaN so the public flag channel can report InvalidOperation"},
	"NewDecimal128":          {Callees: []string{"Bid128FromString", "Bid128IsNaN"}, InventoryFn: "Bid128FromString", Reason: "string constructor routes through the port parser; Bid128IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal128BIDDirect": {Callees: []string{"Bid128FromString", "Bid128IsNaN"}, InventoryFn: "Bid128FromString", Reason: "string constructor routes through the port parser; Bid128IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal128WithFlags": {Callees: []string{"Bid128FromString", "Bid128IsNaN"}, InventoryFn: "Bid128FromString", Reason: "flags-returning string constructor over the port parser; Bid128IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"NewDecimal128WithMode":  {Callees: []string{"Bid128FromString", "Bid128IsNaN"}, InventoryFn: "Bid128FromString", Reason: "explicit-rounding-mode string constructor over the port parser (the caller's mode replaces the default ties-to-even); Bid128IsNaN feeds invalidBIDStringInput's invalid-literal error contract"},
	"ParseDecimal128BIDRaw":  {Callees: []string{"Bid128FromString", "Bid128IsNaN"}, InventoryFn: "Bid128FromString", Reason: "flag-returning raw parser routes through the port parser; Bid128IsNaN distinguishes malformed text silently mapped to NaN so the public flag channel can report InvalidOperation"},
}

func setEquals(got map[string]bool, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	for _, w := range want {
		if !got[w] {
			return false
		}
	}
	return true
}

// representationPlumbingPortFuncs lists the bidgo functions that only convert
// between the public little-endian [16]byte value-type image and the port's
// BID_UINT128 word representation, with the reason each carries no decimal
// operation semantics. The shim layer reaches them on every 128-bit route
// because the conversion is explicit-endian plumbing (it replaced the
// native-endian unsafe reinterpretation that broke big-endian platforms), so
// checks 2 and 3 remove them from the reachable set before comparing against
// the inventory operation mapping. This cannot weaken the routing gate: a
// wrapper whose reachable set holds only plumbing still fails the exact-set
// comparison against its inventory operation. Exhaustive in the composed-map
// style: an entry that no mapped wrapper reaches, or with an empty reason,
// fails.
var representationPlumbingPortFuncs = map[string]string{
	"Bid128FromWords": "constructs BID_UINT128 from explicit (hi, lo) words; bit-pattern representation change only, no decimal operation semantics, exercised transitively by every 128-bit case of the generated verification domains that bit-compare wrapper results",
	"Bid128Words":     "reads the (hi, lo) words of BID_UINT128; bit-pattern representation change only, no decimal operation semantics, exercised transitively by every 128-bit case of the generated verification domains that bit-compare wrapper results",
}

// withoutRepresentationPlumbing removes the registered representation-plumbing
// functions from a resolved reachable set, recording which entries matched so
// the caller can fail stale registrations.
func withoutRepresentationPlumbing(reachable map[string]bool, used map[string]bool) map[string]bool {
	for fn := range reachable {
		if _, plumbing := representationPlumbingPortFuncs[fn]; plumbing {
			used[fn] = true
			delete(reachable, fn)
		}
	}
	return reachable
}

func TestPublicAPIInventoryMappingsMatchShimCalls(t *testing.T) {
	inventory := loadInventory(t)
	tb := loadTypedPublicBuild(t)
	resolver := tb.rootResolver()

	usedValueComposed := map[string]bool{}
	usedFuncComposed := map[string]bool{}
	usedPlumbing := map[string]bool{}

	for _, row := range inventory.Symbols {
		if row.Status != "mapped" {
			continue
		}
		var start *ast.FuncDecl
		switch row.Kind {
		case "method":
			start = tb.rootMethodsByName[row.Symbol]
		case "func":
			start = tb.rootFuncsByName[row.Symbol]
		default:
			t.Errorf("mapped symbol %q has unexpected kind %q", row.Symbol, row.Kind)
			continue
		}
		if start == nil {
			t.Errorf("mapped symbol %q not found among public-build declarations", row.Symbol)
			continue
		}
		reachable := withoutRepresentationPlumbing(resolver.reachablePortFuncs(start), usedPlumbing)

		// Composed value-type method?
		if row.Kind == "method" {
			recv, name, found := strings.Cut(row.Symbol, ".")
			if width, isValue := valueTypeWidths[recv]; found && isValue {
				if spec, composed := composedValueMethodCallees[name]; composed {
					usedValueComposed[name] = true
					if strings.TrimSpace(spec.Reason) == "" {
						t.Errorf("composedValueMethodCallees[%q] has an empty reason", name)
					}
					if len(spec.Ops) < 2 {
						t.Errorf("composedValueMethodCallees[%q] pins fewer than two callees; a single-callee wrapper is simple, remove the entry", name)
					}
					expected := make([]string, len(spec.Ops))
					for i, op := range spec.Ops {
						expected[i] = "Bid" + width + op
					}
					if !setEquals(reachable, expected) {
						t.Errorf("composed wrapper %q reaches %v, pinned callee set is %v; fix the shim, the inventory mapping, or this pinned entry with its reason", row.Symbol, sortedSet(reachable), expected)
					}
					if want := "Bid" + width + spec.InventoryOp; row.BidgoFunction != want {
						t.Errorf("composed wrapper %q: inventory records representative %q, pinned representative is %q", row.Symbol, row.BidgoFunction, want)
					}
					continue
				}
			}
		}

		// Composed package function?
		if spec, composed := composedPackageFuncCallees[row.Symbol]; composed {
			usedFuncComposed[row.Symbol] = true
			if strings.TrimSpace(spec.Reason) == "" {
				t.Errorf("composedPackageFuncCallees[%q] has an empty reason", row.Symbol)
			}
			if len(spec.Callees) < 2 {
				t.Errorf("composedPackageFuncCallees[%q] pins fewer than two callees; a single-callee wrapper is simple, remove the entry", row.Symbol)
			}
			if !setEquals(reachable, spec.Callees) {
				t.Errorf("composed wrapper %q reaches %v, pinned callee set is %v; fix the shim, the inventory mapping, or this pinned entry with its reason", row.Symbol, sortedSet(reachable), spec.Callees)
			}
			if spec.InventoryFnIsContract {
				if reachable[row.BidgoFunction] {
					t.Errorf("composedPackageFuncCallees[%q] declares the inventory function %q a non-callee contract, but it is reachable; remove the stale contract marking", row.Symbol, row.BidgoFunction)
				}
			} else if row.BidgoFunction != spec.InventoryFn {
				t.Errorf("composed wrapper %q: inventory records %q, pinned inventory function is %q", row.Symbol, row.BidgoFunction, spec.InventoryFn)
			}
			continue
		}

		// Simple wrapper: the reachable set must be exactly the inventory singleton.
		if len(reachable) != 1 || !reachable[row.BidgoFunction] {
			t.Errorf("simple wrapper %q must reach exactly {%s}, but reaches %v; fix the mapping (inventory generator/manifest) or pin it as a composed wrapper with a concrete reason", row.Symbol, row.BidgoFunction, sortedSet(reachable))
		}
	}

	for name := range composedValueMethodCallees {
		if !usedValueComposed[name] {
			t.Errorf("composedValueMethodCallees entry %q matched no mapped value-type method; remove the stale entry", name)
		}
	}
	for sym := range composedPackageFuncCallees {
		if !usedFuncComposed[sym] {
			t.Errorf("composedPackageFuncCallees entry %q matched no mapped package function; remove the stale entry", sym)
		}
	}
	for fn, reason := range representationPlumbingPortFuncs {
		if strings.TrimSpace(reason) == "" {
			t.Errorf("representationPlumbingPortFuncs[%q] has an empty reason", fn)
		}
		if !usedPlumbing[fn] {
			t.Errorf("representationPlumbingPortFuncs entry %q was reached by no mapped wrapper; remove the stale entry", fn)
		}
	}
}

// ---------------------------------------------------------------------------
// Check 3: chain cross-check (every reachable port function is verified)
// ---------------------------------------------------------------------------

// siblingEquivalenceCoveredPortFunctions lists the reachable port functions
// that are separately ported full implementations of an oracle-verified
// WithFlags sibling: no AST structure proves the equivalence (the two bodies
// are independent ports), so a dedicated hand-written runtime gate inside the
// bidgo package (equivalenceGateFileRel) asserts bit-exact value agreement
// against the sibling over a pinned corpus. Exhaustive and machine-checked:
// each entry must (a) still be off the goport/FFI surface and not
// AST-equivalence-provable (else stale), (b) have its WithFlags sibling ON the
// goport/FFI surface (that is what makes the equivalence gate transitive
// oracle coverage), and (c) appear in the equivalence gate's target list as a
// {flagless, WithFlags} identifier pair (verified by AST, no name matching).
var siblingEquivalenceCoveredPortFunctions = map[string]string{
	"Bid32Add": "separately ported flagless full implementation (bid32_add.go) of the oracle-verified Bid32AddWithFlags; the public value-only Decimal32BID.Add routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
	"Bid32Div": "separately ported flagless full implementation (bid32_div.go) of the oracle-verified Bid32DivWithFlags; the public value-only Decimal32BID.Div routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
	"Bid32Mul": "separately ported flagless full implementation (bid32_mul.go) of the oracle-verified Bid32MulWithFlags; the public value-only Decimal32BID.Mul routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
	"Bid32Sub": "separately ported flagless full implementation (bid32_add.go) of the oracle-verified Bid32SubWithFlags; the public value-only Decimal32BID.Sub routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
	"Bid64Div": "separately ported flagless full implementation (div64.go) of the oracle-verified Bid64DivWithFlags; the public value-only Decimal64BID.Div routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
	"Bid64Mul": "separately ported flagless full implementation (mul64.go) of the oracle-verified Bid64MulWithFlags; the public value-only Decimal64BID.Mul routes through it, and the hand-written bidgo flagless-variant equivalence gate pins flagless==WithFlags value bit-exactly over the edge+seeded corpus in all five modes",
}

// goportSurface returns the exact Go function names the goport readtest gate
// dispatches (the go_function column of the checked-in dispatch inventory).
func goportSurface(t *testing.T) map[string]bool {
	t.Helper()
	raw, err := os.ReadFile(goportInventoryRel)
	if err != nil {
		t.Fatalf("read %s: %v", goportInventoryRel, err)
	}
	var doc struct {
		Functions []struct {
			GoFunction string `json:"go_function"`
			Status     string `json:"status"`
		} `json:"functions"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal %s: %v", goportInventoryRel, err)
	}
	set := map[string]bool{}
	for _, fn := range doc.Functions {
		if fn.Status == "dispatched" && fn.GoFunction != "" {
			set[fn.GoFunction] = true
		}
	}
	if len(set) == 0 {
		t.Fatalf("%s has no dispatched functions", goportInventoryRel)
	}
	return set
}

// ffiSurface returns the exact bidgo function names the generated FFI
// bit-compare artifact literally calls. This is the FFI domain's Go-side
// surface (the artifact compares each of these calls bit-exactly against the
// native Intel function), extracted from the checked-in generated file that
// verify-generated byte-pins. The C-spelled spec file names under
// generated/testspec/ffi are NOT used: matching them would need a name
// normalization that silently conflates variants.
func ffiSurface(t *testing.T) map[string]bool {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, ffiBitcompareRel, nil, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", ffiBitcompareRel, err)
	}
	set := map[string]bool{}
	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
			if x, ok := sel.X.(*ast.Ident); ok && x.Name == "bidgo" {
				set[sel.Sel.Name] = true
			}
		}
		return true
	})
	if len(set) == 0 {
		t.Fatalf("%s calls no bidgo functions; the FFI surface extraction lost its subject", ffiBitcompareRel)
	}
	return set
}

// equivalenceGatePinnedPairs parses the hand-written bidgo flagless-variant
// equivalence gate and returns the flagless function names it pins: an entry
// of the gate's exhaustive target list counts only if the composite-literal
// element references BOTH the flagless identifier and its WithFlags sibling
// identifier (the actual function values the gate executes - a name string
// alone proves nothing).
func equivalenceGatePinnedPairs(t *testing.T) map[string]bool {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, equivalenceGateFileRel, nil, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse equivalence gate %s: %v", equivalenceGateFileRel, err)
	}
	targetVars := map[string]bool{}
	for _, name := range equivalenceGateTargetVarNames {
		targetVars[name] = true
	}
	pinned := map[string]bool{}
	found := map[string]bool{}
	ast.Inspect(file, func(n ast.Node) bool {
		vs, ok := n.(*ast.ValueSpec)
		if !ok {
			return true
		}
		for i, name := range vs.Names {
			if !targetVars[name.Name] || i >= len(vs.Values) {
				continue
			}
			found[name.Name] = true
			outer, ok := vs.Values[i].(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, elt := range outer.Elts {
				entry, ok := elt.(*ast.CompositeLit)
				if !ok {
					continue
				}
				idents := map[string]bool{}
				ast.Inspect(entry, func(m ast.Node) bool {
					if id, ok := m.(*ast.Ident); ok {
						idents[id.Name] = true
					}
					return true
				})
				for id := range idents {
					if !strings.HasSuffix(id, "WithFlags") && idents[id+"WithFlags"] {
						pinned[id] = true
					}
				}
			}
		}
		return true
	})
	for _, name := range equivalenceGateTargetVarNames {
		if !found[name] {
			t.Errorf("equivalence gate %s does not declare %s; the sibling-equivalence coverage lost its anchor", equivalenceGateFileRel, name)
		}
	}
	return pinned
}

func TestPublicAPIPortFunctionsAreVerifiedByADomain(t *testing.T) {
	inventory := loadInventory(t)
	tb := loadTypedPublicBuild(t)
	rootRes := tb.rootResolver()
	bidgoRes := tb.bidgoResolver()
	goport := goportSurface(t)
	ffi := ffiSurface(t)

	covered := func(fn string) bool { return goport[fn] || ffi[fn] }

	// Full reachable set per mapped symbol; the chain input is the union of
	// everything the wrappers actually route through, plus every inventory
	// representative (the parity contract functions must be verified too).
	targets := map[string]bool{}
	for _, row := range inventory.Symbols {
		if row.Status != "mapped" {
			continue
		}
		var start *ast.FuncDecl
		if row.Kind == "method" {
			start = tb.rootMethodsByName[row.Symbol]
		} else {
			start = tb.rootFuncsByName[row.Symbol]
		}
		if start == nil {
			t.Errorf("mapped symbol %q not found among public-build declarations", row.Symbol)
			continue
		}
		r := withoutRepresentationPlumbing(rootRes.reachablePortFuncs(start), map[string]bool{})
		for fn := range r {
			targets[fn] = true
		}
		if row.BidgoFunction != "" {
			targets[row.BidgoFunction] = true
		}
	}
	if len(targets) == 0 {
		t.Fatal("no reachable port functions found; the cross-check lost its subject")
	}

	gatePinned := equivalenceGatePinnedPairs(t)

	usedSiblingEquivalence := map[string]bool{}
	equivalenceProven := map[string]bool{}
	for _, fn := range sortedSet(targets) {
		if covered(fn) {
			continue
		}
		if how, ok := bidgoRes.proveVariantEquivalence(fn, covered); ok {
			equivalenceProven[fn] = true
			if _, hasEntry := siblingEquivalenceCoveredPortFunctions[fn]; hasEntry {
				t.Errorf("siblingEquivalenceCoveredPortFunctions entry %q is AST-equivalence-provable (%s); the runtime gate entry is redundant, remove it", fn, how)
			}
			t.Logf("port function %q covered by variant equivalence: %s", fn, how)
			continue
		}
		if reason, ok := siblingEquivalenceCoveredPortFunctions[fn]; ok {
			usedSiblingEquivalence[fn] = true
			if strings.TrimSpace(reason) == "" {
				t.Errorf("siblingEquivalenceCoveredPortFunctions[%q] has an empty reason", fn)
			}
			sibling := fn + "WithFlags"
			if !covered(sibling) {
				t.Errorf("siblingEquivalenceCoveredPortFunctions[%q]: sibling %q is not on the goport/FFI surface, so the equivalence gate has no oracle-verified side; the coverage claim is broken", fn, sibling)
			}
			if !gatePinned[fn] {
				t.Errorf("siblingEquivalenceCoveredPortFunctions[%q]: the flagless-variant equivalence gate (%s) does not pin the {%s, %s} pair; the gate does not cover this function", fn, equivalenceGateFileRel, fn, sibling)
			}
			continue
		}
		t.Errorf("reachable port function %q is not exercised by the goport readtest or FFI surface, has no AST-provable variant equivalence, and no sibling-equivalence entry -- a wrapper routes through an unverified port function", fn)
	}

	// Reverse completeness check over the gate's target list: the set of pairs the
	// equivalence gate pins must equal the set of sibling-equivalence
	// exceptions exactly. A gate target that no exception needs is stale (it
	// silently widens the runtime gate's claimed purpose), and a missing one
	// already fails the per-entry check above.
	for fn := range gatePinned {
		if _, needed := siblingEquivalenceCoveredPortFunctions[fn]; !needed {
			t.Errorf("equivalence gate pins %q but no siblingEquivalenceCoveredPortFunctions entry needs it; remove the stale gate target or register the exception with its reason", fn)
		}
	}

	for fn := range siblingEquivalenceCoveredPortFunctions {
		if !targets[fn] {
			t.Errorf("siblingEquivalenceCoveredPortFunctions entry %q is not reachable from any mapped wrapper; remove the stale entry", fn)
			continue
		}
		if covered(fn) {
			t.Errorf("siblingEquivalenceCoveredPortFunctions entry %q is now on the goport/FFI surface; remove the stale entry", fn)
			continue
		}
		if equivalenceProven[fn] {
			continue // already reported as redundant above
		}
		if !usedSiblingEquivalence[fn] {
			t.Errorf("siblingEquivalenceCoveredPortFunctions entry %q was not exercised; remove the stale entry", fn)
		}
	}
}

// ---------------------------------------------------------------------------
// Check 4: FM7 native-path check
// ---------------------------------------------------------------------------

// cgoNativeFiles pins the non-test root files that `import "C"`. Every one must
// be gated behind bid754_native (excluded from the public runtime build) and
// carry a concrete reason. Exhaustive: a new cgo file (or a removed one)
// fails until this list is updated, and a public-runtime file that imports C
// fails both this list and the no-C rule below.
var cgoNativeFiles = map[string]string{
	"c_bid_benchmark_native.go":                  "bid754_native-gated cgo benchmark harness comparing the Go port against native Intel BID; excluded from the public runtime build",
	"dectest_native.go":                          "generated bid754_native-gated native decTest reference oracle; excluded from the public runtime build",
	"generated_readtest_dispatch_native.go":      "generated bid754_native-gated native readtest dispatch oracle; excluded from the public runtime build",
	"generated_ffi_bitcompare_native.go":         "generated bid754_native-gated native FFI bit-compare oracle; excluded from the public runtime build",
	"generated_decnumber_differential_native.go": "generated bid754_native+bid754_decnumber_diff-gated decNumber 3.68 differential-oracle shim (test files cannot carry cgo preambles); excluded from the public runtime build",
}

func fileImportsC(file *ast.File) bool {
	for _, imp := range file.Imports {
		if imp.Path != nil && imp.Path.Value == `"C"` {
			return true
		}
	}
	return false
}

// topLevelDeclNames returns the package-level func (receiver-less), type, var,
// and const identifier names declared in file.
func topLevelDeclNames(file *ast.File) []string {
	var names []string
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Recv == nil {
				names = append(names, d.Name.Name)
			}
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					names = append(names, s.Name.Name)
				case *ast.ValueSpec:
					for _, ident := range s.Names {
						names = append(names, ident.Name)
					}
				}
			}
		}
	}
	return names
}

func TestPublicBuildFilesRouteThroughPortWithoutCgo(t *testing.T) {
	// Strict cross-check: the Config A public build must type-check with
	// zero errors. A public-runtime file that references a native-only symbol is
	// undefined in Config A, so the typed load fails here in addition to the AST
	// name scan below (which keeps a precise per-symbol diagnostic). The load is
	// cached (sync.Once), so this is shared with checks 2 and 3.
	loadTypedPublicBuild(t)

	type parsed struct {
		name        string
		file        *ast.File
		native      bool
		importsC    bool
		topLevelDef []string
	}
	var files []parsed
	for _, name := range rootGoFiles(t) {
		file := parseRootFile(t, name)
		files = append(files, parsed{
			name:        name,
			file:        file,
			native:      requiresNative(fileBuildConstraint(t, file)),
			importsC:    fileImportsC(file),
			topLevelDef: topLevelDeclNames(file),
		})
	}

	// Native-only symbols: package-level names declared in bid754_native-gated
	// files that no public-runtime file also declares (so they are not the dual
	// build/stub symbols). A public-runtime file must not reference them.
	nativeDecls := map[string]bool{}
	publicDecls := map[string]bool{}
	for _, f := range files {
		target := publicDecls
		if f.native {
			target = nativeDecls
		}
		for _, n := range f.topLevelDef {
			target[n] = true
		}
	}
	nativeOnly := map[string]bool{}
	for n := range nativeDecls {
		if !publicDecls[n] {
			nativeOnly[n] = true
		}
	}

	// Exhaustive check over the cgo file list.
	for name, reason := range cgoNativeFiles {
		if strings.TrimSpace(reason) == "" {
			t.Errorf("cgoNativeFiles[%q] has an empty reason", name)
		}
		var f *parsed
		for i := range files {
			if files[i].name == name {
				f = &files[i]
				break
			}
		}
		if f == nil {
			t.Errorf("cgoNativeFiles entry %q is not a non-test root file; remove the stale entry", name)
			continue
		}
		if !f.importsC {
			t.Errorf("cgoNativeFiles entry %q no longer imports \"C\"; remove the stale entry", name)
		}
		if !f.native {
			t.Errorf("cgoNativeFiles entry %q imports \"C\" but is not gated behind bid754_native; it would drag cgo onto the public runtime path", name)
		}
	}

	for _, f := range files {
		if f.importsC {
			if _, ok := cgoNativeFiles[f.name]; !ok {
				t.Errorf("root file %q imports \"C\" but is not in the complete cgoNativeFiles list; public runtime files must route through the Go mechanical port", f.name)
			}
			continue
		}
		if f.native {
			continue // native oracle path, not the public runtime path
		}
		// Public-runtime file: it must not reference a native-only symbol.
		ast.Inspect(f.file, func(n ast.Node) bool {
			ident, ok := n.(*ast.Ident)
			if !ok {
				return true
			}
			if nativeOnly[ident.Name] {
				t.Errorf("public-runtime file %q references native-only symbol %q; the public path must route through the Go mechanical port, not the bid754_native oracle", f.name, ident.Name)
			}
			return true
		})
	}
}
